rpc-jobs/jjb-setup.yml

This commit creates the initial JJB bootstrap job. This is based off
the change in [1], but moves the scl outside of the if statement and
removes the installation of virtualenv (since it should already be
installed).
[1] https://github.com/rcbops-qe/jenkins-jobs/pull/2
Connects https://github.com/rcbops/u-suk-dev/issues/960

Initial JJB job

---

rpc-jobs/jjb-setup.yml

The CIT Jenkins slave doesn't have the general label by default, so
whenever it is reconfigured, that label is removed.
ITs better to not specify a label, then jenkins will automatically
allocate a slave based on the configuration of slaves.
connects rcbops/u-suk-dev#1070

Remove node label from JJB job

---

pipeline-steps/common.groovy
rpc-jobs/multi-node-aio.yml

Based on the groovy script formatting in https://github.com/rcbops/rpc-gating/pull/4
I treated the pipeline as a job to just do the prepare step of the entire multi-node AIO, but we can change it into the full pipeline once the other pieces are complete. I also made the individual jobs that just run a single script, though I'm not sure if that's going to be our preferred method of running specific steps (instead of conditional stages).
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO_Prepare_Deployment/
Connects https://github.com/rcbops/u-suk-dev/issues/1047

Adding pipeline step and jobs for running multi-node aio setup

---

playbooks/allocate_pubcloud.yml

OnMetal servers take longer for SSH to be available, and the only way I've found to keep the Jenkins nodes from disconnecting after a few minutes is to wait before doing the first connection.
Connects rcbops/u-suk-dev#1115

Wait for server startup tasks to finish

---

scripts/jenkins_node.py

This minor update moves the creation of the jenkins instance into
\_\_main\_\_ so that the script can be run without having valid
jenkins environment vars set.

Create jenkins instance inside __main__

---

pipeline-steps/multi_node_aio_prepare.groovy
rpc-jobs/multi-node-aio.yml

- Updated to new public cloud methods
- Moved multi-node AIO prepare steps into a separate groovy file
- Added shell scripting for setting up the openstack_deploy config files
I started looking into creating a playbook similar to aio_config.yml for the configs, but I think I'd rather finish the other pipeline stages and come back and refactor.
Successful Run: https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO/30/
Connects rcbops/u-suk-dev#1092

Add multi-node AIO configs preparation

---

playbooks/install_jenkins_plugins.yml

The plugins workflow-durable-task-step and workflow-cps are
dependencies of workflow-aggregator, and therefore do not need to be
listed in playbooks/install_jenkins_plugins.yml.  Having them present
seems to cause workflow-related plugins to get re-installed each time
this playbook runs.

Remove plugin dependencies

---

pipeline-steps/common.groovy
pipeline-steps/tempest.groovy
rpc-jobs/RPC-AIO.yml
rpc-jobs/params.yml

* Runs tempest playbook
* Runs openstack-tempest-gate to execute tempest tests.
* Adds try/catch within the single use slave block so that artifacts
are retrieved before that node is destroyed
* Adds shell script for collecting and compressing relevant logs and
config. Compression is inconvenient but we don't have much space on
the Jenkins master.
* Adds tempest test result collection for display in the jenkins ui.
Connects rcbops/u-suk-dev#1130
Co-Authored-By: Matt Thompson <mattt@defunct.ca>

CIT Stages: Add tempest testing stage

---

rpc-jobs/install-jenkins-plugins.yml

CIT Jenkins has a python27-python-libs package w/ ssl that does not
support create_default_context and SSLContext, which are needed for
SNI handling.  ansible.module_utils.urls will fall back to using
urllib3 for SNI handling, however it uses a method that is no longer
available in urllib3.  As such, we have to install 1.18.1 specifically
so that ansible.module_utils.urls will detect the SNI support
correctly.
Side note, there is an ansible PR [1] to update
ansible.module_utils.urls accordingly.
[1] https://github.com/ansible/ansible/pull/19962
Connects https://github.com/rcbops/u-suk-dev/issues/1178

Install urllib3

---

pipeline-steps/tempest.groovy
rpc-jobs/RPC-AIO.yml
rpc-jobs/multi-node-aio.yml

I couldn't find a way for Jenkins to switch context from the host node to a VM on the host node, so I added some parameters in order to have the same commands work for both AIO and multi-node AIO. 
I did some separate work not in this PR to run openstack_tempest_gate.sh using ansible, similar to how this script does it: https://github.com/openstack/openstack-ansible/blob/stable/newton/scripts/run-tempest.sh If that's a more preferable way, I can close this PR and open one with those changes.
Connects https://github.com/rcbops/u-suk-dev/issues/1093

Multi-Node AIO: Tempest Tests

---

pipeline-steps/aio_prepare.groovy
playbooks/aio_config.yml

This commit oves from using the dev_pubcloud_user_key user/password
credential to using dev_pubcloud_username and dev_pubcloud_api_key
credential strings instead.
We also use the newly created credential dev_pubcloud_tenant_id
instead of dev_pubcloud_tennant.
Connects https://github.com/rcbops/u-suk-dev/issues/801

Credential cleanup

---

pipeline-steps/common.groovy
pipeline-steps/pubcloud.groovy

Currently we store the pyrax config as a credential but we should store
individual cloud credentials instead.  This commit builds a pyrax
config and writes it to temporary space using existing credentials.
Additionally, we remove some unnecessary indentation in create and
cleanup in pubcloud.groovy.
Connects https://github.com/rcbops/u-suk-dev/issues/801

Dynamically build pyrax config

---

pipeline-steps/horizon.groovy
rpc-jobs/multi-node-aio.yml

The Horizon integration test suite is no longer supported in Newton, and there's only a stable branch going back to Mitaka, so these particular tests will run only for Mitaka builds.
Connects https://github.com/rcbops/u-suk-dev/issues/1124

Add Mitaka Horizon selenium integration tests

---

pipeline-steps/pubcloud.groovy

Ran into an issue where I was trying to run just the clean up step on an old server, but it failed because the virtualenv wasn't installed in that particular workspace (since parallel runs create separate workspaces).

Install ansible before cleanup

---

pipeline-steps/multi_node_aio_prepare.groovy

The multi-node setup has a variables.sh file now that takes precedent over environment variables, so I'm removing that file completely. I've got a review open to fix setup-host.sh, so once that merges, I'll test this change out.
https://review.openstack.org/#/c/436700/
https://review.openstack.org/#/c/437040/
Connects https://github.com/rcbops/u-suk-dev/issues/1274

Remove variable file for multi node AIO setup

---

Jenkinsfile

Currently, we run as root which causes all the ansible roles, etc. to
get created as root user/group.  Subsequent runs of a job w/ this dirty
workspace will then fail when deleteDir runs as jenkins user is unable
to delete those files owned by root.

Don't run lint script as root

---

pipeline-steps/aio_prepare.groovy
playbooks/aio_config.yml
rpc-jobs/RPC-AIO.yml
rpc-jobs/params.yml

1. Adds the basic project and converts the job to a job-template so
that we have jobs for each series, etc.
2. Removes the PLAYBOOKS array and runs deploy_sh stage instead
3. Adds a few more parameters, such as DEPLOY_CEPH, etc.

Add project and job template

---

pipeline-steps/aio_prepare.groovy
pipeline-steps/common.groovy
playbooks/aio_config.yml

1. Updates aio_prepary.groovy to install ansible into a venv and run
aio_config.yml with that version of ansible.
2. Updates common.groovy to first install virtualenv before attempting
to use it.
3. Updates aio_config.yml to write the rackspace vars to
user_zzz_gating_variables.yml so we don't have to check if this is a
liberty, mitaka, etc. deployment.
Note that 1. is being done as different rpc-openstack versions use
different versions of ansible, and aio_config.yml did not run cleanly
across them all. The 2. task was done as a liberty deployment does not
have virtualenv installed when common.install_ansible() is executed.
Connects https://github.com/rcbops/u-suk-dev/issues/1270

AIO Prep Changes

---

scripts/ghstatus.py

This script is for adding direct links on github PRs.
Without this, the github context links to the parent job (kicked off by
the jenkinsfile). With this we can link directly to the swift or ceph
aio job.
Connects rcbops/u-suk-dev#1080

Add github status script

---

pipeline-steps/aio_prepare.groovy
pipeline-steps/common.groovy
pipeline-steps/maas.groovy
pipeline-steps/multi_node_aio_prepare.groovy
pipeline-steps/pubcloud.groovy
playbooks/aio-maas-cleanup.yml
playbooks/aio-maas-entities.yml
playbooks/aio_config.yml
playbooks/roles/maas-entities/tasks/main.yml
playbooks/vars/aio.yml
playbooks/vars/all.yml
playbooks/vars/onmetal.yml
rpc-jobs/multi-node-aio.yml

Add `deploy_maas` function which configures MaaS, creates entities, and runs the MaaS setup and verification playbooks.
Add MaaS entitiy cleanup playbook to the main cleanup function.
Connects https://github.com/rcbops/u-suk-dev/issues/1125

Add multi-node AIO MaaS deployment/verification

---

pipeline-steps/aio_prepare.groovy
pipeline-steps/common.groovy
pipeline-steps/deploy.groovy
rpc-jobs/RPC-AIO.yml
rpc-jobs/params.yml

1. Adds an UPGRADE_FROM_REF parameter to params.yml
2. Adds an upgrade stage to deploy.groovy and adds TERM=linux to deploy
environment vars which needs to be set by one of the upgrade scripts
3. Updates common.groovy to strip out ansible args that don't work
across all ansible versions
4. Updates RPC-AIO.yml to set a default STAGE var and overrides it on
upgrades with the necessary stage
5. Updates RPC-AIO.yml to exclude upgrades on certain series since we
don't test upgrades across all
5. Updates RPC-AIO.yml to manually apply an iptables rule, which is
necessary since we run deploy.sh with DEPLOY_OA=no and
DEPLOY_AIO=yes and then DEPLOY_OA=yes and DEPLOY_AIO=no (these
combinations means that it will never get applied via deploy.sh)
Connects …

Add Upgrade stage

---

playbooks/vars/aio.yml

Currently, ceph-osd.yml fails to run on an AIO.  It looks like it's
expecting these vars to be bools, and not strings.

Change vars from strings to bools

---

rpc-jobs/multi-node-aio.yml

We haven't converted the multi-node AIO job to a project yet, so we can't set the default values for rpc_params. This is a temporary fix so that the jobs can have normal default values again instead of things like {RPC_BRANCH}.

Set RPC parameters in multi-node AIO

---

rpc-jobs/RPC-AIO.yml

Note that we also add the tasks that need to run post upgrade inside
an if statement to ensure they don't run again outside of an upgrade
job.

Add maas stages to AIO job

---

playbooks/allocate_pubcloud.yml

Jobs should not fail when there is not enough quota, however most jobs
are long running, so if theres no quota on the first try, its unlikely
that the situation is different after 5x30s delay.
This commit sets 120x60s retries. After a couple of hours
there should be some quota - or there is a problem that requires human
intervention.

Patience required when waiting for quota

---

pipeline-steps/tempest.groovy

The tempest test results are in a different place for Mitaka and Liberty, so these results weren't getting published properly.
Mitaka: https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO/148/
Newton: https://rpc.jenkins.cit.rackspace.net/view/Multi-Node%20AIO/job/OnMetal_Multi_Node_AIO/147/

Copy from Mitaka/Liberty tempest results location

---

pipeline-steps/multi_node_aio_prepare.groovy

Environment variables are no longer being overridden by variables.sh, so I'm removing that workaround.
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO/157/execution/node/156/log/?consoleFull

Use variables.sh again for deployments

---

pipeline-steps/aio_prepare.groovy
rpc-jobs/RPC-AIO.yml
rpc-jobs/params.yml

Currently, all our builds include swift even when ceph is being used.  This commit explicitly removes swift from being deployed for the ceph job so that we have at least one job where swift is not being used.  This is necessary to partially cover the use case of swift not being present in an environment.

Remove swift from ceph job

---

rpc-jobs/sync-credential-store.yml
scripts/add_jenkins_cred.groovy
scripts/pull_passwords.py

This commit adds a job which is intended to run on a clean jenkins
deployment to sync passwords from the safe to jenkins' credential
store.  The list of passwords to sync is hard-coded in
pull_passwords.py and will need to be pulled out at a later date.
At time of writing add_jenkins_cred.groovy supports text or file
credential types.
As this is a bootstrap job, we have tried to limit the amount of
credentials that already need to be in place before this runs.  The
only one that will need to be manually created are
service_account_jenkins_ssh_key and rpc-jenkins-svc-github-key.
The former is the ssh key assigned to the service account jenkins user
(in jenkins itself) which gets used when running jenkins-cli.jar, and
the latter is the GitHub private key to install pwsafe.
Connects …

Password syncing

---

lint.sh

The lint job is currently failing because it cannot find classes that
are imported in scripts/add_jenkins_cred.groovy.  This commit adds a
temporary exclusion until we figure out how to best handle this
situation.

Skip linting scripts/add_jenkins_cred.groovy

---

pipeline-steps/multi_node_aio_prepare.groovy
rpc-jobs/multi-node-aio.yml

When we aren't setting this, the default kernel installed is 3.13.0-112-generic. Previous to https://github.com/openstack/openstack-ansible-ops/commit/9d9580d0912e9161cd16d6b61282204805c19ab1, 4.4.0-66-generic was used by default. With the 4.4.0-66-generic kernel, I'm no longer seeing the Trusty unreachable issues where some VMs are not available at the start of the RPC deployment.
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO/177/
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO/178/
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO/179/
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO_newton-trusty/8/
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO_mitaka-trusty/6/ …

Add DEFAULT_KERNEL parameter

---

Jenkinsfile

Prevents errors where jobs in repo don't match the live jobs.

Run JJB update job on merges to rpc-gating master

---

pipeline-steps/common.groovy
pipeline-steps/deploy.groovy
rpc-jobs/multi-node-aio.yml

This commit adds a function to common.groovy to calculate a reasonable #
for ANSIBLE_FORKS, and then modifies any functions that call deploy.sh
or openstack-ansible to pass in the env var ANSIBLE_FORKS.
The reason for doing this is that on rpc-openstack's liberty and mitaka
branches, deploy.sh does not correctly set forks when running
rpc-openstack playbooks.  This is resulting in a number of job failures
due to ssh connection failures because it's picking up the forks = 15
in rpcd/playbooks/ansible.cfg.
We also set env var ANSIBLE_SSH_RETRIES=3 when running deploy.sh or
openstack-ansible.  This env var is ansible 2.x and above only, so will
have no affect on liberty and mitaka branches.
Connects https://github.com/rcbops/u-suk-dev/issues/1406

Calculate and set ANSIBLE_FORKS

---

pipeline-steps/common.groovy
pipeline-steps/deploy.groovy

Upstream ansible doesn't have functionality for retrying failed ssh
connections before v2.
As we often see ssh connection failures, use a fork of ansible 1.9
that contains the ssh_retry connection plugin.
This only affects mitaka and below as newton and above use ansible v2.
Connects rcbops/u-suk-dev#1406

Use ssh_retry in ansible 1.9

---

rpc-jobs/RPC-AIO.yml

This commit adds the artifacts-14.0 branch to the periodic
tests. For the moment, Xenial is purposefully skipped as
the artifacts produced are Trusty only at this time.
Connects https://github.com/rcbops/u-suk-dev/issues/1336

Add artifacts AIO periodic testing

---

pipeline-steps/maas.groovy
rpc-jobs/multi-node-aio.yml

The MaaS and test stages don't depend on each other, so I'm running them in parallel so that they don't block each other. We should probably revisit the Blue Ocean plugin at some point so that we can more easily view parallel steps in the UI.
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO/171/
Connects https://github.com/rcbops/u-suk-dev/issues/1382

Run post-deployment steps in parallel

---

Jenkinsfile

The rpc-openstack and jjb-run jobs both create a docker image
tagged lint. Unfortunately they contain different packages. This causes
a race as one job may build its container, but the other job retags it
before the first job uses it.
The solution is to use different image tags for each job.
connects u-suk-dev#1313

Fix docker name conflict

---

rpc-jobs/RPC-AIO.yml

This prevents one axis from overriding another's value. The values from
each axis are combined to form the default value for the parameter.
This resolves an issue where tempest_service_available_swift was not set
for pr jobs because the pr axis overrides the user variables set by
the ceph axis.
Connects rcbops/u-suk-dev#1313
Related rcbops/rpc-gating#66

Use axis specific variables for user_vars

---

pipeline-steps/aio_prepare.groovy
pipeline-steps/common.groovy
pipeline-steps/deploy.groovy

Previously we applied vars that improve ssh connection stability
(forks, ansible_git_repo etc) to deploy_sh, but didn't apply those to
the upgrade step. This ensures that both get the same vars.
Connects rcbops/u-suk-dev#1406

Apply ssh env vars to upgrades

---

scripts/jenkins_node.py

Currently most slaves are short-lived, so they
do not need more than 1 executor. Having 15
causes the Jenkins dashboard to be rather long
to scroll down and my finger occasionally gets
a cramp. I'd rather avoid that.
So, for a better world, we're reducing the
executors for any slave nodes created to 2.

Reduce slave executors to 2

---

rpc-jobs/RPC-Artifact-Build.yml

In 3027b9acda764a5e38f2b77c6ca8799e68e852db I
unfortunately neglected to rename the file
name loaded for the artifact_build functions.
This fixes that.

Use the artifact_build.groovy file

---

rpc-jobs/RPC-Artifact-Build.yml

Seeing as artifact_build uses the common functions,
we should probably ensure the common stuff is loaded
first.

Artifacts: Change groovy pipeline load order

---

rpc-jobs/RPC-AIO.yml

The github pull request builder plugin can now trigger pipelines,
in a much simpler way than using a jenkinsfile/orgfolder as a parent
job.
connects rcbops/u-suk-dev#1379

Add GHPRB trigger to AIO jobs

---

playbooks/webhooks.yml

The webhook proxy was originally setup for use with the jenkins
github organisation folder plugin. Github pull request builder uses
a different hook target url which this commit adds to the proxy
configuration
connects rcbops/u-suk-dev#1313

Add github pull request builder to webhook proxy

---

rpc-jobs/RPC-AIO.yml
rpc-jobs/properties.yml

Triggering is currently failing with the following:
Mar 23, 2017 5:41:28 PM org.jenkinsci.plugins.ghprb.GhprbRootAction getTriggers
SEVERE: Failed to match signature for trigger on project: RPC-AIO_master-xenial-pr
java.lang.IllegalStateException: A GitHub project url is required.
...
This is a futile attempt at fixing.

Add github property for rpc-openstack

---

rpc-jobs/jjb-setup.yml

The `--delete-old` argument is an option of `update` and not `jenkins-jobs`.

Move delete-old to proper position

---

rpc-jobs/RPC-Artifact-Build.yml

Currently it's evaluated by JJB as a boolean which
is not properly catered for in the scripts. This
patch ensures that the value is always set to a
string for all jobs.
Connects https://github.com/rcbops/u-suk-dev/issues/1413

Make sure PUSH_TO_MIRROR is a string

---

rpc-jobs/RPC-Artifact-Build.yml

Currently the Artifact build jobs are only
triggered manually or periodically. This
adds PR triggers.
https://github.com/rcbops/u-suk-dev/issues/1413

Add PR trigger to artifact build jobs

---

rpc-jobs/multi-node-aio.yml

Removed the Horizon test stages from the default ones so that we can still run them if necessary.
Connects https://github.com/rcbops/u-suk-dev/issues/1482

Skip Horizon test stage

---

playbooks/vars/all.yml

This commit sets some openstack-ansible ansible overrides to fix a
number of tempest failures we see on the OnMetal jobs.  To summarise:
- use qemu instead of kvm (running nested virt (kvm) seems unstable and
we end up getting a number of job failures that we do not see on the
single node AIO or hardware labs)
- set reseller_admin_role in tempest.conf to match what gets created by
swift (this is only an issue on stable/mitaka, the default value is
already correct on later branches)
- disable personality in tempest.conf as our nova service by default
disallows file injection (again, only needed on stable/mitaka as
later versions of tempest seem to detect this correctly)
Ideally, we'll want to find the root cause of the kvm failures and try
to work around this so that we can continue to use …

Set overrides to fix OnMetal tempest failures

---

pipeline-steps/aio_prepare.groovy
pipeline-steps/common.groovy

This function will be re-used in other jobs which
may not want to have the AIO config done with it
so it's better to have in its own function.
Connects https://github.com/rcbops/u-suk-dev/issues/1500

Move rpc-op git prep into standalone function

---

pipeline-steps/artifact_build.groovy
rpc-jobs/RPC-Artifact-Build.yml

This patch aims to refactor the Artifact jobs so
that they more effectively use stages, and share
a common structure. The detailed steps are all in
the groovy file, whereas the pipeline logic is
formed into stages in the job dsl.
An additional job is also added to build apt
artifacts. This job runs on a jenkins slave rather
than a single-use node.
A common script to get the credentials into the
environment is used for all jobs.
Connects https://github.com/rcbops/u-suk-dev/issues/1451

Artifact job refactor

---

pipeline-steps/aio_prepare.groovy
pipeline-steps/artifact_build.groovy

In d7bbaa9aa726058290e22fa3bbf987ff8ff14a84 the namespace
for the prepareRpcGit was left out. This adds it.

Properly refer to prepareRpcGit

---

rpc-jobs/multi-node-aio.yml

Because pipeline jobs don't have an scm section where you can specify which branch and repo to watch, I made a separate trigger job to call the omna job. Pipelines use the repo and branch of the last build, so that git info is hardcoded into the trigger jobs.
Connects https://github.com/rcbops/u-suk-dev/issues/1358

Trigger multi-node AIO on post merge

---

rpc-jobs/RPC-AIO.yml
rpc-jobs/RPC-Artifact-Build.yml

The jobs in Jenkins are currently displaying the following error:
Not a positive integer
This commit wraps {NUM_TO_BUILD} in quotes which seems to resolve
this issue.

Fix JJB issue

---

pipeline-steps/artifact_build.groovy
rpc-jobs/RPC-Artifact-Build.yml

In order to update the git artifacts, another job is added
to the pipeline.
The three primary control points (pull, replace, push) for
all artifact jobs are added to allow fine grained control
of how the jobs behave and to provide the option of replacing
existing artifacts which may be needed from time to time.
Some adjustments are made to the job definition to make it
a little easier to read.
Connects https://github.com/rcbops/u-suk-dev/issues/1502
Connects https://github.com/rcbops/u-suk-dev/issues/1501
Connects https://github.com/rcbops/u-suk-dev/issues/1503

Add git artifact job and job control vars

---

rpc-jobs/RPC-AIO.yml

Timeout is set to 8 hours as upgrade jobs are typically <6hrs, so that
gives us 2 hours of buffer.
This is an absolute timeout as inactivity timeout isn't currently
supported for pipelines.
See: https://issues.jenkins-ci.org/browse/JENKINS-26521
Connects: rcbops/u-suk-dev#1492

Add timeout to AIO Job

---

rpc-jobs/RPC-AIO.yml
rpc-jobs/RPC-Artifact-Build.yml
rpc-jobs/defaults.yml
rpc-jobs/single_use_slave_template.yml

This PR moves a bunch of job defaults to global defaults.
There is a huge net benefit of doing this, however it does mean we can
remove the raft of default variables set in RPC-AIO.yml and
RPC-Artifact-Build.yml and should we need to change REGION quickly, for
example, we can do it on place versus 3.
This needs to be re-tested once the lint job is triggering again.
Connects https://github.com/rcbops/u-suk-dev/issues/1493

Create defaults file

---

pipeline-steps/aio_prepare.groovy
pipeline-steps/artifact_build.groovy
pipeline-steps/common.groovy
pipeline-steps/deploy.groovy

The RPC-AIO_mitaka-upgrade-pr job is currently failing when attempting
to upgrade to RPC_BRANCH.  This commit updates deploy.upgrade() to use
prepareRpcGit and updates common.prepareRpcGit() to accept the desired
branch as an argument.  We then move out the upgrade conditional logic
into aio_prepare.prepare().
Connects https://github.com/rcbops/u-suk-dev/issues/1506

Use prepareRpcGit in upgrade testing

---

playbooks/allocate_pubcloud.yml

It is possible for the rax module to return success despite not successfully creating instances. This commit adds a check to ensure that the requested number of instances are successfully booted.
Connects rcbops/u-suk-dev#1507

Fail if less than required num of instances booted

---

rpc-jobs/RPC-AIO.yml

This variable is on it's way to changing to jewel in RPCO,
see https://github.com/rcbops/rpc-openstack/pull/2117. However,
the newton+trusty+ceph job currently deploys hammer, and we will
like to keep it that way. This commit overrides ceph_stable_release
to hammer.
Connects https://github.com/rcbops/u-suk-dev/issues/1536

Override ceph_stable_release

---

rpc_jobs/multi_node_aio.yml
rpc_jobs/params.yml

This commit makes the openstack-ansible-ops params into the params.yml
file so we can re-use these by other jobs.  We also fix some incorrect
indenting in multi_node_aio.yml.

Make openstack-ansible-ops parameters re-usable

---

rpc_jobs/multi_node_aio.yml
rpc_jobs/params.yml

This commit moves more params in multi_node_aio.yml to params.yml, and
uses the rpc_repo_params macro instead of redefining within the job
template.

Update multi-node parameters

---

Dockerfile
pipeline_steps/common.groovy
rpc_jobs/rpc_gating_lint.yml

I forgot to use COPY instead of ADD. ADD is more likely to cause cache invalidations, so that's why Docker kept having to reinstall the python packages.
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#add-or-copy
Connects https://github.com/rcbops/u-suk-dev/issues/1539

Use COPY instead of ADD

---

rpc_jobs/jjb_setup.yml

This is safer and may prevent the loss of existing jobs when only
building a subset of jobs.

Default DELETE_OLD to false

---

constraints.txt
requirements.txt
rpc_jobs/periodic_cleanup.yml
scripts/periodic_cleanup.py

This job deletes instances that are older than a specified time (Default
48 hours). This is useful to keep us from hitting quota if an individual
job has a cleanup failure or a user forgets to remove an instance that
was kept for investigation.
Connects rcbops/u-suk-dev#1380

Add Periodic Cleanup Job

---

constraints.txt
pipeline_steps/common.groovy
pipeline_steps/maas.groovy
pipeline_steps/pubcloud.groovy
playbooks/setup_jenkins_slave.yml
playbooks/templates/cloudfiles.html.j2
playbooks/upload_to_cloud_files.yml

- Had to pin requests because of an issue in pyrax where requests==2.11.0 throws an InvalidHeader when it sets the TTL for the file in the header 
- Moved all the cloud account credentials into a common method
- Hardcoded DFW as the upload region since the CIT nodes are in DFW and we're currently only uploading from there
Connects https://github.com/rcbops/u-suk-dev/issues/1438

Push artifacts to Cloud Files

---

rpc_jobs/periodic_cleanup.yml

Some jobs are still failing on quota, so we need to reduce the amount
of time that instances can idle before they are cleaned up.

Reduce Timeout Age

---

pipeline_steps/multi_node_aio_prepare.groovy
playbooks/setup_jenkins_slave.yml
rpc_jobs/lem_multi_node_aio.yml
rpc_jobs/multi_node_aio.yml
rpc_jobs/params.yml

- adds MULTI_NODE_AIO_DIR and DATA_DISK_DEVICE params to osa_ops_params
and overrides these in the respective jobs
- removes old code from setup_jenkins_slave.yml that is no longer
used and changes a reference from ansible_default_ipv4.address to
ansible_host (this is necessary because we may try to use a host
behind a firewall and not wish to use the host's
ansible_default_ipv4.address address)
- creates rpc_multi_node_aio.yml which is specifically for building the
multi-node AIO on LEM nodes
Connects https://github.com/rcbops/u-suk-dev/issues/1368

First pass at a LEM multi-node AIO

---

rpc_jobs/rpc_artifact_build.yml

In order to be able to use apt artifacts successfully
to build the same tag in the same way today and next
year we need to fix the starting point to ensure that
the host OS does not have packages installed which are
later than the packages in the artifacted apt repo.
A 14.04.4 image has been prepared for Trusty and serves
as that starting point.
Connects https://github.com/rcbops/u-suk-dev/issues/1606

Use the 14.04.4 Trusty image for artifacting jobs

---

pipeline_steps/aio_prepare.groovy
pipeline_steps/artifact_build.groovy
pipeline_steps/common.groovy
pipeline_steps/deploy.groovy
rpc_jobs/rpc_aio.yml

When a job is triggered by a PR, the checkout must
universally include the change introduced by the PR.
Currently only the AIO job inherits the correct PR
checkout. This patch moves the PR resolving to the
general RPC-O repo checkout so that it becomes
universal.
Connects https://github.com/rcbops/u-suk-dev/issues/1607

Checkout PR repository correctly

---

playbooks/vars/aio.yml
playbooks/vars/all.yml
rpc_jobs/rpc_aio.yml

Currently, we have a few options that are configured differently
between our AIO build and our multi-node build which results in tests
being run differently.  This commit moves some of the AIO overrides
out to playbooks/vars/all.yml so that tempest will test and behave in a
more standard manner.
Connects https://github.com/rcbops/u-suk-dev/issues/1490

Standardise tempest testing

---

playbooks/vars/all.yml

This commit increases percent_used_critical_threshold to 95 from 85 as
the default value looks to be too low for the liberty->mitaka upgrade
job specifically.  That job runs longer (meaning more logs used, etc.)
and also has venvs for both liberty and mitaka and therefore consumes
more space than the other jobs.

Bump percent_used_critical_threshold

---

pipeline_steps/common.groovy
playbooks/setup_jenkins_slave.yml
rpc_jobs/rpc_aio.yml
rpc_jobs/rpc_artifact_build.yml

When a more restricted setup is used to ensure
that an artifacted deployment only uses the
prepared artifacts, the jobs fail as the jenkins
slave cannot install the JRE which comes from
the ubuntu updates repo.
This patch ensures that the slave is prepared
with the apt artifact repo source prior to
trying to install anything.
For the ``artifacts-14.0`` branch, this should
setup the artifacted apt repo and key. Without
doing so the job will fail to install the apt
packages. For any other branches (currently)
it should skip those tasks.
Connects https://github.com/rcbops/u-suk-dev/issues/1627

Configure apt artifact source when necessary

---

rpc_jobs/single_use_slave_template.yml

Macro expansion is only valid in job templates, not jobs.

Remove template macros from non template job

---

rpc_jobs/lem_multi_node_aio.yml

1. Adds a new stage for creating the logical volume for VMs, which
effectively allows you to re-move the stage from a job if the host
already has the logical volume created (running again will generate
a failure)
2. Cleans up STAGES and loads the kibana tests
Connects https://github.com/rcbops/u-suk-dev/issues/1369

Add LEM stage and cleanup stages

---

playbooks/vars/all.yml

The cinder-backup service is usable on an AIO deployment, but
deploying on a multi-node deployment seems to result in the service not
working.  I'm not a storage expert, but from looking briefly it appears
that the open-iscsi package is missing on the storage nodes, which
prevents the service from backing up a volume.  The package open-iscsi
gets installed by nova on the compute nodes, and since an AIO deploys
nova-compute, cinder-volume, and cinder-backup to the host itself this
explains why cinder-backup is functional there.
I will create an upstream bug and fix for this but in the mean time
it's probably best to just disable this from being tested.
Connects https://github.com/rcbops/u-suk-dev/issues/1643

Temporarily disable cinder-backup from being tested

---

playbooks/vars/aio.yml
playbooks/vars/all.yml
playbooks/vars/onmetal.yml

The RPC-AIO jobs are currently failing tempest runs because it's
attempting to test cinder-backup while cinder backup is not being
deployed.  This commit keeps cinder-backup disabled for the OnMetal
AIOs but re-enables it for the RPC-AIOs.
Side note, the OSA AIO boostrap sets tempest_volume_backup_enabled
to true, which is why disabling this service did not affect the
OnMetal AIOs.

Re-enable cinder-backup on RPC-AIO jobs

---

pipeline_steps/common.groovy
pipeline_steps/maas.groovy
playbooks/vars/all.yml
rpc_jobs/lem_multi_node_aio.yml
scripts/get_maas_token_and_url.py

The MaaS playbooks can either use a set of public cloud credentials or a
token and API URL. Customer deployments always require a token and API
URL. This commit adjusts how MaaS is deployed so that the existing
public cloud credentials are used to generate a token and API URL which
are then used by the playbooks instead.
This changes applies to all jobs deploying MaaS. Given that the use of
public cloud credentials in the playbooks is only for the benefit of
developers it makes sense for that to be the untested path.
This change does not directly address multi-physical-node deployments
using LEM however that can build on this work when it becomes a reality.
Connected https://github.com/rcbops/u-suk-dev/issues/1370

Use MaaS token and API URL

---

pipeline_steps/common.groovy
rpc_jobs/rpc_aio.yml
rpc_jobs/rpc_artifact_build.yml

Port of https://github.com/rcbops/jenkins-rpc/blob/master/scripts/gating_bash_lib.sh#L365-L384
Didn't run any tests against rpc-openstack because I didn't want to accidentally affect the open PRs there, but I did create a job and a test PR with rpc-gating:
Doc Change PR -> Skipping: https://rpc.jenkins.cit.rackspace.net/job/mkam-doc-pr-test/4/console
Not a Doc Change PR -> Not Skipping: https://rpc.jenkins.cit.rackspace.net/job/mkam-doc-pr-test/5/console
Doc Change, but job not triggered by a PR (like a periodic job) -> Not skipping: https://rpc.jenkins.cit.rackspace.net/job/mkam-doc-pr-test/9/console
Connects https://github.com/rcbops/u-suk-dev/issues/1633

Skip builds on doc change only PRs

---

pipeline_steps/pubcloud.groovy

The runOnPubCloud function didn't catch failures in the instance
creation stage, this commit ensures they are caught.
Connects rcbops/u-suk-dev#1650

Ensure cleanup when using runonpubcloud

---

rpc_jobs/periodic_cleanup.yml
scripts/jenkins_node.py
scripts/periodic_cleanup.py

This commit updates periodic_cleanup.py so we can pass a pattern to use
when cleaning up instances.  We also update the periodic cleanup job to
cleanup ra|ri instances.
Connects https://github.com/rcbops/u-suk-dev/issues/1655

Clean up new RPC-IRR instances

---

pipeline_steps/ssh_slave.groovy

Found that it was in the wrong location with this build: https://rpc.jenkins.cit.rackspace.net/job/mkam-RPC-AIO/22/console

Update virtualenv location for destroy slave step

---

lint.sh
rpc_jobs/lem_multi_node_aio.yml
scripts/extract_dsl.py
scripts/syntax.groovy
test-requirements.txt

This commit extracts groovy from JJB templates so they can be
checked for syntax. Previously JJB templates were only checked for
yaml syntax and JJB semantics so groovy errors could slip in.
This commit also reduces lint time by scanning all groovy files
with a single JVM rather than starting one up for each file.
Connects rcbops/u-suk-dev#1661

Check Groovy syntax with JJB templates

---

rpc_jobs/rpc_artifact_build.yml

The artifacts-14.0 branch has become dated and will be removed.
Its content was moved into a new branch in preparation for a PR
to rpc-openstack/master and some new fixes have gone into it
since then. The fixes in there haven't been applied into the
artifacts-14.0 branch and the periodics on that branch are now
interfering with the artifacts published by manual job execution
on the artifacts branch. To resolve this the jobs should be
switched over to the artifacts branch.
Also, now that we have two base images configured in the same
way for both Trusty and Xenial, switch to using them for the
jobs.
Connects https://github.com/rcbops/u-suk-dev/issues/1609

Switch artifact job branch and update base images

---

pipeline_steps/common.groovy

Github pull request builder automatically updates PRs, but we now also
need to provide that information to the relevant JIRA issue.

UG-586 Add functions for JIRA notification

---

rpc_jobs/rpc_artifact_build.yml

3c952fb introduced a bug where the common library was used before
being imported. This commit fixes that.

UG-586 fix artefact build ordering

---

pipeline_steps/common.groovy

Jobs have been hanging due to issues with the pip cache on the CIT node. This is a temporary fix to avoid this.
https://rpc.jenkins.cit.rackspace.net/view/IRR/job/RPC-IRR_rpc_maas-master-trusty-base/147/console
https://rpc.jenkins.cit.rackspace.net/job/mkam-OnMetal-Multi-Node-AIO/12/console

UG-606: Install ansible packages without using cache

---

constraints.txt
pipeline_steps/common.groovy
requirements.txt
scripts/jirautils.py

This adds the functionality to create JIRA issues for failed builds
but doesn't integrate it with any jobs, that will be added in a
subsequent PR.
Test job: https://rpc.jenkins.cit.rackspace.net/job/scratchpipeline/176/
Issue created by test job: https://rpc-openstack.atlassian.net/browse/UG-603

UG-599 Add JIRA issue creation

---

rpc_jobs/periodic_cleanup.yml

Periodic cleanup has the following rough structure:
```
node(){
clone rpc-gating
...
docker stuffs
...
cleanup shell scripts
}
```
The problem is that the workspace used after "docker stuffs" is not the
same workspace that is used for the initial clone. That means that the
cleanup shell scripts can't be found. As a workaround, this commit
moves the cleanup shell scripts to before the docker step.

UG-605 Fix script not found in periodic cleanup

---

pipeline_steps/artifact_build.groovy
rpc_jobs/rpc_artifact_build.yml

The node used for apt artifact builds only has one
executor. The job currently requires access to the
node before determining whether the stage is
necessary or not, resulting in any other jobs in
the pipeline waiting for a free executor.
This moves the stage check ahead of the node use
so that the node never needs to be used if the
stage is not included.

Process apt artifact stage before using node

---

pipeline_steps/common.groovy

We hit a similar issue previously, and this was a result of a stale lock dir in ~/.cache/pip.  I've since removed ~./pip/http/b/9/2/d/5/b92d5efeb2406de109c0263ebfbbe56d85532219b7d0aae49a57069a.lock which should hopefully resolve the hanging we were seeing.
Side note, we will need to find out what's causing this issue as this is the second time we've hit it.
Reverts rcbops/rpc-gating#194

Revert "UG-606: Install ansible packages without using cache"

---

pipeline_steps/common.groovy

The packages that are installed for gating purposes should not use the pip configuration set for RPC deployments.
AIO partial build: https://rpc.jenkins.cit.rackspace.net/job/mkam-RPC-AIO/2/console

Install gating python packages in isolated mode

---

rpc_jobs/irr_role_test.yml

We have seperated out the logstash role to allow changes for
log aggregation.  The role will eventually be moved upstream,
but will need a local role and functional testing until then.
Connected to issue/942

Add functional testing to the rpc-role-logstash repo

---

rpc_jobs/multi_node_aio.yml

Create jira issues instead of github issues when a post-merge mnaio
build fails.

UG-599 Add Jira Issue Creation to Multinode AIO

---

playbooks/vars/aio.yml
rpc_jobs/rpc_aio.yml

Disables cinder-backup on AIO as L->M has upstream bug that is
causing gating failures.
https://github.com/rcbops/rpc-openstack/issues/2258
Connects https://rpc-openstack.atlassian.net/browse/UG-615

UG-615 Disable cinder-backup

---

pipeline_steps/common.groovy
pipeline_steps/multi_node_aio_prepare.groovy
rpc_jobs/lem_multi_node_aio.yml
rpc_jobs/multi_node_aio.yml
rpc_jobs/params.yml

This change ensures the version of openstack-ansible being tested on
multi-node AIOs is the one defined by the submodule in rpc-openstack.
To override the OSA SHA, add a new commit to RPCO and then test that
version of RPCO.
This change removes the ability to specify the OSA SHA as a job
parameter. Affected jobs will now use the SHA specified by the version
of RPCO being tested instead of defaulting to the HEAD of the relevant
OSA branch, this should remove the chance of incorrect test results due
to a mismatch between what RPCO specifies the OSA SHA should be and what
Jenkins uses. This change also helps to enforce the principle that
configuration should be in code.

UG-551 Use OSA SHA defined by RPCO with multi-node

---

.gitignore
pipeline_steps/webhooks.groovy
playbooks/webhooks.yml
role_requirements.yml

The webhooks host is long-lived, to improve security the following
changes are applied:
- Restrict SSH access to specific IP addresses
- Replace use of lineinfile with template for modifying sshd_config to
prevent conflicting values for the same configuration option
- Enable the automatic installation of APT security package update

UG-528 Improve security of webhooks node

---

pipeline_steps/aio_prepare.groovy
pipeline_steps/deploy.groovy
rpc_jobs/rpc_aio.yml

In order to test the leapfrog upgrades from
kilo to newton, jobs have been added to allow
the deployment of kilo and the leapfrog
upgrade to the newton-14.1 branch.
The job for the kilo deployment is to test
any new PR's to Kilo, if need be, and also
to validate via a periodic job that Kilo can
actually deploy. This will help to differentiate
between failures due to a kilo deployment, or
failures due to the leapfrog upgrade process.
The stages in the leapupgrade jobs are
deliberately reduced to a minimum set. This
is a starting target - once the job is showing
success more stages will be added to find
other potential bugs.

Add Leapfrog upgrade AIO jobs

---

constraints.txt
pipeline_steps/common.groovy
playbooks/setup_jenkins_slave.yml
requirements.txt

This commit installs pip and setuptools using the ``get-pip.py`` script,
instead of using the distro's pip version.

UG-612 Install pip using get-pip.py

---

rpc_jobs/rpc_aio.yml

Kilo was never tested with new tests.
This commit ensure kilo PR will not be tested against code that
was never tested before.
By doing this, we sadly reduce the test coverage, but we are
in-line to the current deploys's testing.

[LA-312] Make kilo tests pass

---

playbooks/test_holland.yml

The value for rpc_release is set via group_vars for
all versions of RPC-O. The playbook should inherit
it from there instead of trying to override it.
This has been working so far due to the rpc_release
override set in user_*.yml files, but as we try to
cut down on those problems like this are likely to
arise.

Remove rpc_release from test_holland

---

scripts/docker_cleanup.sh

Removes images that are not the latest ubuntu that are more
than a day old.
This change is to resolve a found race condition in which the
cleanup job could run at a time and remove a newly created image
before the job it was created for ran the image.

UG-625 Adjust Docker cleanup

---

pipeline_steps/tempest.groovy
playbooks/vars/aio.yml
playbooks/vars/onmetal.yml
rpc_jobs/lem_multi_node_aio.yml
rpc_jobs/multi_node_aio.yml
rpc_jobs/params.yml
rpc_jobs/rpc_aio.yml

The run_tempest.yml playbook is now provided by the rpc-openstack
repository, relieving the tempest pipeline from complying and
maintaining upstream's different tempest execution mechanisms.
The new playbook is now run by ``tempest.groovy`` the same way that
``/opt/openstack_tempest_gate.sh`` was run previously.
Edit: 05/31/2017 - Currently blocked by:
Connects https://github.com/rcbops/u-suk-dev/issues/1680

RI-18 Modify tempest pipeline for new execution method

---

pipeline_steps/holland.groovy

This variable caused the rpc_release variable to
be undefined when executing the holland tests
for mitaka.

Remove ANSIBLE_CACHE_PLUGIN from Holland testing

---

constraints.txt
githooks.sh
lint.sh
requirements.txt
rpc_jobs/periodic_cleanup.yml
scripts/jenkins_node.py
scripts/periodic_cleanup.py

While entities tied to cloud instances are removed when those instances
are deleted, entities that are manually created are not. For instance
entities created for multi node aio VMs may not be cleaned up if a.
job is aborted.
This commit adds entity cleanup to the public cloud step of the
periodic cleanup job.
This commit also adds:
* multi region cloud server cleanup
* logging

UG-618 Add MaaS entity removal to periodic cleanup

---

pipeline_steps/tempest.groovy

AIO builds are currently failing with a "No such file or directory"
error when running tempest on the AIOs.  This appears to be a result of
running tempest unwrapped with quotes around the tempest command, which
bash does not like:
```
root@ranxp-16-8323:~# 'cd /tmp && ls -al'
-bash: cd /tmp && ls -al: No such file or directory
root@ranxp-16-8323:~#
```
This commit simply creates a temporary variable depending on whether we
are using a wrapper (and need to quote) or not.

Fix execution of tempest on AIO

---

README.md
rpc_jobs/rpc_aio.yml

In order to cater for a more complex test matrix,
the AIO job axes have been updated as follows.
series:
The branch information to inform the git checkout
executed by jenkins, eg: master.
image:
The image to execute the job on, eg: trusty.
scenario:
The scenario to configure when executing the job,
eg: swift, ceph.
action:
The action to execute, eg: deploy, minor upgrade,
major upgrade, leapfrog.
In order to prepare for the master branch
becoming Ocata, the trusty builds are excluded
for the branch.

Change AIO job axes for an increased test matrix

---

playbooks/vars/onmetal.yml

Add quotations and an empty string to tempest vars
for multi-node AIO builds because they are not
surrounded by quotes in the run_tempest.yml playbook.

UG-629 Temporary fix for multi-node AIO tempest vars

---

rpc_jobs/rpc_aio.yml

Previously, we only set UPGRADE_FROM_REF on upgrade context, however
it is now set in the series and this is breaking the kibana tests.
This commit only uses UPGRADE_FROM_REF when we're on the first step of
a major upgrade.

Fix how kibana_branch is determined

---

scripts/docker_cleanup.sh

Updates docker script to remove images on double digit hours. This
is needed as the `docker images -a` does not switch to include
days at 24 hours.
The `egrep` is required as the version of docker on the build node
does not include the `--format` flag in the cli that would allow
use of the `.CreatedAt` template to better filter images to delete.

UG-625 Docker Cleanup tweak

---

scripts/periodic_cleanup.py

Periodic cleanup jobs are currently failing due to an extra key
being in string formatting. Removes extra key causing error.

Removes incorrect key error

---

rpc_jobs/rpc_aio.yml

Ceph doesn't work on kilo, it won't work during leapfrog.
On top of it, leapfrog is only meant for Trusty builds.

[LA-325] Filter leapfrog jobs

---

rpc_jobs/rpc_artifact_build.yml

The master branch for rpc-o is now Ocata, and trusty
is no longer supported for Ocata.

AR-191 Remove trusty artifact builds from rpc-o master

---

pipeline_steps/artifact_build.groovy
rpc_jobs/rpc_artifact_build.yml

Currently all the artifact jobs do the resource
allocation prior to checking whether the patch
is a docs-only check. This wastes resources
unnecessarily.
Also, the docs check is currently trying to
check the wrong place, resulting in the tests
not being executed.
This ensures that the docs check is done on the
CIT slave prior to processing any stages. It
also ensures that the check is executed in the
right folder.

AR-191 Do docs check without resource allocation

---

pipeline_steps/deploy.groovy
rpc_jobs/rpc_aio.yml

In order to test minor upgrades, an additional
action is added, with the test implementing a
newton r14.0.0 release upgrade to the head of
newton-14.1.

ISU-38 Add minor upgrade AIO action

---

playbooks/setup_jenkins_slave.yml

The need for this is nicely documented in the file itself.  At present,
some jobs do not have these environment vars set and are therefore not
getting the defaults as expected.

Set vars correctly when unset in environment

---

playbooks/vars/onmetal.yml

Reverts rcbops/rpc-gating#226
The quotations have been added in rpc-openstack in all branches, so the temporary fix is no longer needed.

Revert "UG-629 Temporary fix for multi-node AIO tempest vars"

---

pipeline_steps/maas.groovy

This function was converted from one that takes user name and api key
argument to one that supplies its own creds via a with_credentials
block. However the code that used those creds was not updated to read
the env rather than supplied args. This commit fixes that.

UG-619 fix maas utils function

---

rpc_jobs/rpc_artifact_build.yml

Only the Apt and Pipeline jobs need to not
be concurrent. All others can be done in
parallel. This should help speed up feedback
for PR's.
The pipeline jobs should not be concurrently
run because any one job will produce artifacts.

Allow concurrent artifact PR tests

---

playbooks/vars/aio.yml
playbooks/vars/onmetal.yml

This option should be set within the RPC-O project should we need to
have the service disabled. Hard coding it here makes it next to
impossible to test changes that may use this feature within the gate.

Removing the hard coded cinder backup option

---

rpc_jobs/irr_role_test.yml

The context field is now being used to pass in an OpenStack release name
into the gate job. This will be used to ensure the role are able to gate
on all major releases presently supported by RPC.

add additional context for irr gate jobs

---

rpc_jobs/irr_role_test.yml

The flavor used in the irr gates was wrong, its now been fixed.

fixed flavor

---

pipeline_steps/common.groovy
pipeline_steps/pubcloud.groovy
pipeline_steps/ssh_slave.groovy
playbooks/setup_jenkins_slave.yml

External slaves do not have access to the Jenkins API, so operations
that require that access must use a node() block that allocates
an internal slave.

UG-619 Run Jenkins API operations internally

---

playbooks/vars/all.yml

This var is correctly set in rpc-openstack now, there should no longer
be a need to override this in rpc-gating.

UG-651 Remove nova_cross_az_attach override

---

lint.sh

This solves a docker related ip4/6 issue where JJB attempted to
connect to localhost on ::1 but no v6 stack is available. In order
to avoid the v6 issue this commit replaces localhost with 127.0.0.1.

UG-652 Add jjb config file to lint job

---

pipeline_steps/common.groovy
pipeline_steps/github.groovy
rpc_jobs/pull_request_issue_link.yml
scripts/ghutils.py

Add a line of the form Issue: Jira key to the
description of pull requests in tracked repositories.
This change adds a job to update pull requests. Developers only add an
issue key reference to commit messages. This job runs a script to update
the pull request description body with a link to the issue to simplify
accessing it.
Issue: [UG-607](https://rpc-openstack.atlassian.net/browse/UG-607)

UG-607 Ensure pull requests link to Jira issues

---

rpc_jobs/periodic_cleanup.yml

This commit addresses a problem where the Jenkins section of the
periodic cleanup job fails because its running on a slave that doesn't
have access to the Jenkins API.
When fixing this I realised that most of the cleanups are node
specific, so we actually need to run them against every node.
This job introduces a parallel stage to clean up various objects on
all slaves, then a second stage to run public cloud and Jenkins node
cleanups on a single internal slave.
Issue: [UG-658](https://rpc-openstack.atlassian.net/browse/UG-658)

UG-658 Clean up all slaves

---

rpc_jobs/irr_role_test.yml

Currently the trigger phrase and the status
context do not match, making it very hard to
figure out the trigger phrase.
This patch makes them match so that it is
more intuitive.
'repo' is removed from the trigger phrase
as the web hooks will not accept triggers
from any repo other than the originating
one anyway.

Make the recheck trigger phrase more sensible

---

rpc_jobs/rpc_artifact_build.yml

The artifact build jobs do not need more than
a general1-8 for doing the builds, so set this
to the flavor used in order to free up
additional quota for other jobs.
Issue: [AR-197](https://rpc-openstack.atlassian.net/browse/AR-197)

AR-197 Set flavor for artifact jobs

---

rpc_jobs/long_running_slave.yml

We don't care about small blips in cpu utilisation, but if cpu is
pinned for an extended period (30 minutes) then that may indicate
a stuck job/process which needs investigating.
Issue: [UG-660](https://rpc-openstack.atlassian.net/browse/UG-660)

UG-660 Increase consecutive count for slave alerts

---

rpc_jobs/rpc_artifact_build.yml

For the apt artifact creation, rpc-repo is
primarily a publishing point and a place to
store a backup of the database. We should
therefore not be pulling the data from it
every time we run a job, but instead just
execute the job on the long-running node
which has the current database.
Issue: [AR-106](https://rpc-openstack.atlassian.net/browse/AR-106)

AR-106 Do not pull apt data from rpc-repo

---

webhooktranslator/tests/MaaS_payload_example.json
webhooktranslator/tests/test_webhooktranslator.py
webhooktranslator/webhooktranslator/webhooktranslator.py

This change adds a link to the intelligence dashboard for an alert.
This will allow a user to see historical data related to the alert.
This change also adds a real sample MaaS webhook payload as reality
doesn't quite match the sample given in the docs.
Tests are also udpated to reflect the new sample payload.

Add dashboard link to MaaS Jira tickets

---

pipeline_steps/common.groovy
pipeline_steps/webhooks.groovy
playbooks/webhooks.yml
rpc_jobs/webhook.yml

Useful for re-running parts of a job that usually allocates its own
resources. The first usage is for reconfiguring the long running
webhooks node.
Issue: [UG-618](https://rpc-openstack.atlassian.net/browse/UG-618)

UG-618 Allow manual specification of job node inventory

---

pipeline_steps/aio_prepare.groovy
rpc_jobs/rpc_aio.yml

This commit adds a check for a capabilities file which indicates
that the branch being tested handles its own configuration.
Once all branches contain this functionality, then the rpc-gating
functionality for configuring rpc-o can be completely removed.
This commit also ensures that the JJB axes are passed through to the
job's environment, so that in repo scripts can make configuration
choices based on the scenario being tested.

UG-646 Skip aio config if handled in repo

---

pipeline_steps/deploy.groovy
rpc_jobs/rpc_aio.yml

The requirement to add the checksum in this way
is only necessary for Liberty and earlier. Also,
this should be done in the rpc-o scripts, not
the gating scripts.
This action is already present in both kilo [1] and liberty [2].
[1] https://github.com/rcbops/rpc-openstack/pull/2370
[2] https://github.com/rcbops/rpc-openstack/pull/2369
Issue: [UG-641](https://rpc-openstack.atlassian.net/browse/UG-641)

UG-641 Remove addChecksumRule

---

pipeline_steps/irr_role_tests.groovy
rpc_jobs/irr_role_test.yml

At present the IRR tests do not include API tests becuase the creds used
for maas were passed into the the job. This change allows the job to pass
in environment variables which contain the needed credentials and will
enable us to test additional API interactions from within any IRR test.
Issue: [UG-618](https://rpc-openstack.atlassian.net/browse/UG-618)

Include creds for maas testing

---

pipeline_steps/irr_role_tests.groovy
rpc_jobs/irr_role_test.yml

The IRR jobs may need the basic cloud credentials available to them for
varying reasons. This change ensures the cloud creds are passed in and
allowing the job to do what it needs within the test itself.
Issue: [UG-618](https://rpc-openstack.atlassian.net/browse/UG-618)

Simply pass in cloud creds into the IRR job

---

pipeline_steps/irr_role_tests.groovy

Currently the IRR jobs use a top level stage, with a few nested stages.
This doesn't display well in either UI, so isn't particularly useful.
This commit adds a run_tests.sh stage, which will allow anyone
viewing a job via blue ocean to skip passed all the Jenkins related
logs and get straight to the test execution output.
Note: Nothing has changed apart from indentation, and additional/removal of stage blocks.

Tidy IRR stages

---

rpc_jobs/influx.yml

InfluxDB host currently doesn't have any influx specific open
ports. This should open the influxdb ports listed in [1].
[1]: https://docs.influxdata.com/influxdb/v1.2/administration/ports/

[LA-346] Set default influxdb ports to open

---

pipeline_steps/influx.groovy

Because the shell used by default isn't bash, we can't do the
smart grep and inclusion.
This should fix it.

[LA-347] Inventory with log_hosts not generated

---

pipeline_steps/influx.groovy

$ is parsed in the job, and $INVENTORY is undefined.
That leads to issues like [1] and [2].
[1] /var/lib/jenkins/workspace/Influx-Setup/rpc-maas@tmp/durable-3d035db5/script.sh: line 7: syntax error near unexpected token `;'
[2] /var/lib/jenkins/workspace/Influx-Setup/rpc-maas@tmp/durable-3d035db5/script.sh: line 7: `; then’

[LA-347] Escape $ in influx step

---

pipeline_steps/aio_prepare.groovy

As this stage is run on a single use slave, rpc-openstack is cloned
to /opt rather than the workspace. This commit fixes the path
and includes log messages for each situation.

UG-646 Fix capabilities file detection path

---

pipeline_steps/influx.groovy
rpc_jobs/influx.yml

The log hosts group is added to the inventory to ensure the influx
plays run correctly. Use of unstash is removed so that override
inventory can be used in future.
Issue: [LA-347](https://rpc-openstack.atlassian.net/browse/LA-347)

LA-347 Fix inventory mangling

---

pipeline_steps/common.groovy

As gating playbooks are run from shared long running nodes, IPs will
gradually be added to the known hosts file. These IPs will be recycled
by public cloud and cause intermittent host key failures.
Issue: [LA-347](https://rpc-openstack.atlassian.net/browse/LA-347)

LA-347 Skip host key checking

---

pipeline_steps/influx.groovy
playbooks/allocate_pubcloud.yml
rpc_jobs/influx.yml

As the influx db instance will be long running, it needs some
actual creds, rather than using publicly accessible defaults.
Issue: [LA-347](https://rpc-openstack.atlassian.net/browse/LA-347)

LA-347 Supply influx creds

---

rpc_jobs/defaults.yml
rpc_jobs/params.yml
rpc_jobs/rpc_aio.yml

This commit de-dupes the STAGES param, allowing us to tweak specific
STAGES depending on action and trigger.
More specifically, with this change in place we can gate [1], which
allows us to remove the deployment of the rpc support role on PR
builds.
Note that `DEPLOY_SUPPORT_ROLE` will only be available once [1]
merges, however setting this in this PR saves us the extra PR once
[1] lands.
[1] https://github.com/rcbops/rpc-openstack/pull/2343

De-dupe STAGES param

---

pipeline_steps/common.groovy
pipeline_steps/github.groovy

Adds lint step to verify Jira Issue included in commit. Required to
verify that commit attached to an existing Jira Issue.
Updates get_jira_issue_key function to only view last commit for
Jira issue key which can be included in either subject or body.
Adds git to Dockerfile which is required for new linter function.
Issue: [UG-640](https://rpc-openstack.atlassian.net/browse/UG-640)
Issue: [LA-320](https://rpc-openstack.atlassian.net/browse/LA-320)

UG-640 Add Jira Issue to linting

---

pipeline_steps/deploy.groovy
rpc_jobs/defaults.yml
rpc_jobs/params.yml
rpc_jobs/rpc_aio.yml

The function `upgrade` is modified to enable resources, e.g. compute
instances, to be created prior to a leapfrog upgrade. These resources
will be used elsewhere to monitor the end-user impact of the upgrade.
Three parameters are exposed to control the number of resources that are
created:
- LEAPFROG_TEST_NETWORKS
- LEAPFROG_TEST_SERVERS
- LEAPFROG_TEST_VOLUMES
Depends-on: https://rpc-openstack.atlassian.net/browse/LA-321
Issue: [LA-323](https://rpc-openstack.atlassian.net/browse/LA-323)

LA-323 Add configurable resource load to leapfrog

---

pipeline_steps/aio_prepare.groovy

These used to be added to vars files by rpc-gating, this is now done
within rpc-o, so we need to ensure that the token is passed as an
environment variable.

UG-646 Pass MaaS token+url to bootstrap

---

pipeline_steps/aio_prepare.groovy

Reverts rcbops/rpc-gating#296
This doesn't work as it tried to read from rpc-gating on the wrong node. Reverting and will try another approach. 

Revert "UG-646 Pass MaaS token+url to bootstrap"

---

pipeline_steps/multi_node_aio_prepare.groovy
rpc_jobs/hw_multi_node_aio.yml
rpc_jobs/multi_node_aio.yml

Took out some of the no longer necessary prepare steps so that there is less to port over to rpc-openstack.
- Run networking configuration before deployment
Previously, the prerouting configuration had to occur
after deployments to prevent the rules from
interfering with the setup. This is no longer the case,
so it can run with the multi-node setup.
- Remove deploy node increases
The default memory and vcpu has been increased
in the templates.
Issue: [UG-648](https://rpc-openstack.atlassian.net/browse/UG-648)

UG-648 Reduce multi-node AIO setup steps

---

pipeline_steps/common.groovy
pipeline_steps/maas.groovy
rpc_jobs/hw_multi_node_aio.yml
rpc_jobs/multi_node_aio.yml
rpc_jobs/rpc_aio.yml

Previously these vars were added to overrides via the rpc-gating
aio_config playbook. This configuration is now done in rpc-o, so we
need to ensure the token and url variables are available in the
environment for the rpc-o scripts to use.
This is the second attempt, first attempt:
* introduction: https://github.com/rcbops/rpc-gating/pull/296
* revert: https://github.com/rcbops/rpc-gating/pull/297
The first attempt failed because it attempted to run a script from
rpc-gating on a single use slave that didn't have a checkout of
rpc-gating. This version ensures that the the script is run on a
long-running slave that will have the appropriate checkout.

UG-646 Supply MaaS env vars to RPC scripts

---

pipeline_steps/common.groovy
pipeline_steps/maas.groovy
rpc_jobs/hw_multi_node_aio.yml
rpc_jobs/multi_node_aio.yml
rpc_jobs/rpc_aio.yml

Reverts rcbops/rpc-gating#298
Fails because install_ansible hasn't been called so deps aren't available. 

Revert "UG-646 Supply MaaS env vars to RPC scripts"

---

rpc_jobs/rpc_aio.yml

From a product standpoint, deploying a ceph
cluster using RPC-O is not a supported
configuration. It is therefore a pointless
waste of time and resources to test this
configuration.
Issue: [RE-46](https://rpc-openstack.atlassian.net/browse/RE-46)

RE-46 Remove ceph scenario from newton

---

rpc_jobs/rpc_aio.yml

From a product standpoint, deploying a ceph
cluster using RPC-O in newton and above is
not a supported configuration. It is therefore
a pointless waste of time and resources to
test this configuration for minor upgrades
for newton and above.
Issue: [RE-46](https://rpc-openstack.atlassian.net/browse/RE-46)

RE-46 Remove ceph scenario from minorupgrade

---

pipeline_steps/deploy.groovy
rpc_jobs/rpc_aio.yml

K (for leapfrog), N14.1 (for leapfrog + intraseries), N14.0 (for
intraseries), and master should now send metrics to the long
running influxdb instance.
Issue: [LA-314](https://rpc-openstack.atlassian.net/browse/LA-314)

[LA-314] Send data to long running influx for AIO

---

rpc_jobs/irr_role_test.yml

Due to job taking longer to provision resources and the fact that the
IRR jobs are testing more things now, specifically the maas repo, it's
likley that we'll need more time for the tests. This change increases
the job timeout to 3 hours from 2.
Issue: [LA-345](https://rpc-openstack.atlassian.net/browse/LA-345)

Increase gate timeout for IRR

---

pipeline_steps/common.groovy
pipeline_steps/deploy.groovy
pipeline_steps/holland.groovy
pipeline_steps/kibana.groovy
pipeline_steps/maas.groovy

Previously, we had to ssh onto the vm
and run commands for multi-node AIO.
Now that we can run directly on the deploy
node, this code is no longer needed.
Issue: [UG-667](https://rpc-openstack.atlassian.net/browse/UG-667)

UG-667 Remove code to run commands on vm

---

pipeline_steps/influx.groovy

When Grafana will support SQlite, we will be able to deploy
the dashboards using this PR.
Issue: https://rpc-openstack.atlassian.net/browse/LA-332
Issue: [LA-332](https://rpc-openstack.atlassian.net/browse/LA-332)

Install Grafana

---

rpc_jobs/rpc_aio.yml

Tempest, Kibana, and Holland should be tested after the leapfrog.
NOTE: Holland only gets added to STAGES in periodics, not PRs.  This
also means we do not need to explicitly add Holland to STAGES
for leapfrog jobs.
Issue: [LA-344](https://rpc-openstack.atlassian.net/browse/LA-344)

[LA-344] Include more tests in leapfrog

---

rpc_jobs/rpc_aio.yml

The RPC-AIO_kilo-trusty-leapfrogupgrade-swift-periodic job is failing
constantly because we're not setting UPGRADE_FROM_REF appropriately for
this job.  This commit deletes this job since this job is effectively
testing the same thing as
RPC-AIO_newton141-trusty-leapfrogupgrade-swift-periodic.

Delete kilo leapfrog periodic

---

pipeline_steps/influx.groovy

For security and playbook run reasons, we should defined an admin
password for grafana.

LA-356 Grafana needs an admin password to be set

---

pipeline_steps/tempest.groovy

Master/Ocata places tempests result in a different path than pre-
Ocata. This updates command to attempt to find the location of
the >=Ocata `tempest_results.xml` file if exists and includes that
in path of results files that are attempted to be copied.
Issue: [UG-666](https://rpc-openstack.atlassian.net/browse/UG-666)

UG-666 Updates tempest results location

---

pipeline_steps/influx.groovy
rpc_jobs/influx.yml

This allows SSH logins from anywhere, which will be useful for debugging
during the early stages of influxdb setup.

LA-356 Allow SSH Whitelist to be disabled

---

rpc_jobs/params.yml
rpc_jobs/rpc_aio.yml

Influx parameters were defined for the appropriate branches, and
the shell scripts have been adapted. Now it's time to link the
two together.

LA-356 Wire Influx to its usage

---

pipeline_steps/influx.groovy

Target nodes should now be named influx_hosts, due to the latest
changes in rpc-maas.

LA-356 Rename target nodes for influx

---

rpc_jobs/influx.yml

This way we avoid issues with an old pip version.
It should be alright if no blacklist/whitelist.

Run on any available node

---

rpc_jobs/hw_multi_node_aio.yml
rpc_jobs/multi_node_aio.yml

Some mnaio builds are failing because we're attempting to test holland,
but we're not deploying the rpc support role.  This commit flips on
DEPLOY_SUPPORT_ROLE so that holland is deployed for testing.

UG-634 Enable DEPLOY_SUPPORT_ROLE on multi-node builds

---

rpc_jobs/rpc_aio.yml

We previously removed the PR leapfrog jobs by using a triple
axis exclude, which doesn't seem to work.
Issue: LA-366 
Issue: [LA-366](https://rpc-openstack.atlassian.net/browse/LA-366)

LA-366 Re-introduce leapfrog PR.

---

rpc_jobs/rpc_artifact_build.yml

In order to prevent git confusion when re-using
tag structures we delete the workspace after
we're done using it.
Issue: [RE-51](https://rpc-openstack.atlassian.net/browse/RE-51)

RE-51 Delete workspace after use

---

rpc_jobs/rpc_aio.yml

Most of the upgrade jobs use the target branch as the trigger branch,
for exmaple changes to newton-14.1 have an upgrade test from kilo
to ensure the changes don't break upgrades.
However the kilo leapfrog job tests changes to kilo with a leapfrog
to newton-14.1 This alternate dirction upgrade requires some variable
changes to succeed.
In this commit the kibana branch variables are set to sensible
values for the kilo-newton leap job, as the defaults do not work.
Mostly because UPGRADE_FROM_REF is not set for kilo.
Issue: [La-366](https://rpc-openstack.atlassian.net/browse/La-366)

La-366 Ensure kibana branches make sense

---

rpc_jobs/rpc_artifact_build.yml

The extraneous deleteDir was a mistake
left behind in the previous commit, and
it causes the git checkout to be deleted
when it's still required.
Issue: [RE-51](https://rpc-openstack.atlassian.net/browse/RE-51)

RE-51 Remove extraneous deleteDir

---

pipeline_steps/common.groovy

If virtualenv is old, it will create a venv containing an old
version of pip, which may not have the isolated flag, which we make
use of.
Issue: [RE-49](https://rpc-openstack.atlassian.net/browse/RE-49)

RE-49 Ensure the required version of virtualenv

---

pipeline_steps/common.groovy

Requirements is  bash variable so should be escaped to avoid being interpolated by groovy.
Issue: [RE-49](https://rpc-openstack.atlassian.net/browse/RE-49)

RE-49 Fix dollar escapes in create_workspace_venv

---

pipeline_steps/common.groovy
requirements.txt

When we setup the venv, we set it up without
the host's versions of pip, setuptools and wheel
(if possible) so that we can independently set
the version we want.
In order to ensure that we do not try to upgrade
or downgrade pip/setuptools/wheel in an existing
venv, we remove it from the requirements.
We only force a re-installation of pip, setuptools
and wheel into the venv if the pip version is not
available or incorrect.
This patch does a revert of some of the changes
in 73ad014
Issue: [RE-51](https://rpc-openstack.atlassian.net/browse/RE-51)

RE-51 Force known pkg version in workspace venv

---

playbooks/templates/cloudfiles.html.j2

This will prevent insecure script/resource warning is modern browsers.
`ssl_url` is provided by the rax_files module:
https://github.com/ansible/ansible-modules-core/blob/devel/cloud/rackspace/rax_files.py#L280

Use SSL for artefact link

---

rpc_jobs/params.yml
rpc_jobs/rpc_aio.yml

Maas deploy or not should be defined with a single env var.
We shouldn't have steps for maas, the orchestration inside the
project (for example rpc-o leapfrog, or rpc-o deploy) should
handle its deploy.
Gating should only be aware of what to do in a job, not handling
the job's work itself.
Issue: [LA-373](https://rpc-openstack.atlassian.net/browse/LA-373)

LA-373 Deploy Maas with an env var

---

rpc_jobs/rpc_aio.yml

The env var set for maas was overriden into the job, wh
We remove the override, and all the references to maas for the
AIO job.
Issue: [LA-373](https://rpc-openstack.atlassian.net/browse/LA-373)

LA-373 Env var for maas should not be overriden

---

constraints.txt
pipeline_steps/common.groovy
pipeline_steps/holland.groovy
pipeline_steps/influx.groovy
pipeline_steps/maas.groovy
pipeline_steps/pubcloud.groovy
pipeline_steps/ssh_slave.groovy
pipeline_steps/webhooks.groovy
requirements.txt
rpc_jobs/hardening.yml
rpc_jobs/hw_multi_node_aio.yml
rpc_jobs/influx.yml
rpc_jobs/install_jenkins_plugins.yml
rpc_jobs/irr_role_test.yml
rpc_jobs/jjb_setup.yml
rpc_jobs/long_running_slave.yml
rpc_jobs/multi_node_aio.yml
rpc_jobs/params.yml
rpc_jobs/periodic_cleanup.yml
rpc_jobs/pull_request_issue_link.yml
rpc_jobs/rpc_aio.yml
rpc_jobs/rpc_artifact_build.yml
rpc_jobs/rpc_gating_lint.yml
rpc_jobs/single_use_slave_template.yml
rpc_jobs/sync_credential_store.yml
rpc_jobs/webhook.yml
vars

This pull request ensures that MaaS variables are supplied to the rpc deploy process, so that it can configure MaaS for the deployment.
The majority of this change is dedicated to moving node allocation to a common function. This ensures that nodes are allocated in a consistent way, and that the gating utility virtualenv is build exactly once per node.
This PR also prepares rpc-gating for use as a Jenkins shared library, so that we can use implicitly library loading, rather than having to explicitly load every groovy script in every job.

UG-646 Common node allocation

---

pipeline_steps/tempest.groovy

Command to find the tempest results file works for
versions older than ocata as well, so running
multiple attempts to copy the file results in
duplicate results published to Jenkins.
Issue: [RE-102](https://rpc-openstack.atlassian.net/browse/RE-102)

RE-102 Use only find command for copying tempest results

---

scripts/tmp_cleanup.sh
scripts/workspace_cleanup.sh

To reduce disk usage on restricted CIT slaves, we reduce the workspace
retention period.
Added regex to pip cleanup to ensure tmp dirs aren't missed.
Issue: [UG-668](https://rpc-openstack.atlassian.net/browse/UG-668)

UG-668 Reduce workspace retention

---

pipeline_steps/common.groovy
rpc_jobs/webhook.yml

MaaS alert JIRA issues are being created in the UG project which is
now legacy. This commit updates the defaults to ensure that new issues
are created in the RE project.
Issue: [UG-668](https://rpc-openstack.atlassian.net/browse/UG-668)

UG-668 Create issues in RE project by default

---

rpc_jobs/multi_node_aio.yml

The commit 3be71623803ccd1d69f46e183f9750ab134f34f5 refactored the
management of nodes and now handles the clean up of workspaces. Work on
multi_node_aio.yml, that was in progress when the commit merged, has
re-introduced the use of deleteDir in the template and is causing
failures.
Given that the function `common.use_node` ensures the workspace is
deleted at the beginning and end of the job, this commit removes that
functionality from multi_node_aio.yml.
Issue: [LA-376](https://rpc-openstack.atlassian.net/browse/LA-376)

LA-376 Remove use of deleteDir in multi_node_aio

---

rpc_jobs/rpc_aio.yml

In order to enable the use of the monitoring
to measure uptime during the minor upgrade,
we need to test an upgrade from a start point
that includes the new rpc-maas implementation.
This patch changes the start point to the head
of the newton-14.0 branch.
Issue: [ISU-94](https://rpc-openstack.atlassian.net/browse/ISU-94)

ISU-94 Change newton141 upgrade start ref

---

pipeline_steps/common.groovy
playbooks/webhooks.yml
rpc_jobs/hardening.yml
rpc_jobs/hw_multi_node_aio.yml
rpc_jobs/influx.yml
rpc_jobs/install_jenkins_plugins.yml
rpc_jobs/irr_role_test.yml
rpc_jobs/jjb_setup.yml
rpc_jobs/long_running_slave.yml
rpc_jobs/multi_node_aio.yml
rpc_jobs/params.yml
rpc_jobs/periodic_cleanup.yml
rpc_jobs/pull_request_issue_link.yml
rpc_jobs/rpc_aio.yml
rpc_jobs/rpc_artifact_build.yml
rpc_jobs/rpc_gating_lint.yml
rpc_jobs/single_use_slave_template.yml
rpc_jobs/sync_credential_store.yml
rpc_jobs/webhook.yml

Currently the rpc-gating library is loaded implicitly, jenkins injects
it into the groovy environment before the script is started. The
problem with this approach is that the verison of rpc-gating used
cannot be overridden.
This version uses the RPC_GATING_BRANCH parameter to set the
version of rpc-gating that is loaded. This will return our ability
to test other jobs (such as RPC AIOs) against changes to gating.
This approach also makes it explicit in each job where the library
is coming from. Once this merges, we'll turn off implicit loading
in Jenkins global config.

UG-646 add library statement to every job

---

pipeline_steps/pubcloud.groovy

The instance_name was being passed to the delete
methods but global variable instance_name was
being used instead.
Issue: [RE-105](https://rpc-openstack.atlassian.net/browse/RE-105)

RE-105 Use instance_name argument for deletion

---

rpc_jobs/multi_node_aio.yml

Define the variable `environment_vars` to prevent leapfrog upgrades
failing due to its absence.
A recent change appears to have broken leapfrog upgrades on multi-node
AIOs which was not detected due to the inherent race that exists with
the current testing and merging process. `environment_vars` was no
longer defined when `deploy.upgrade_leapfrog` is run causing a failure.
In reality this failure has exposed a hidden bug because
`environment_vars` should not be defined as a by-product of some other
part of the code and so this change should now address the underlying
issue.
Issue: [RE-106](https://rpc-openstack.atlassian.net/browse/RE-106)

RE-106 Specify leapfrog upgrades environment_vars

---

playbooks/allocate_pubcloud.yml

Duplicate instances is not the only situation that triggers this.
message.
Issue: [RE-108](https://rpc-openstack.atlassian.net/browse/RE-108)

RE-108 Clarify duplicate instances message

---

rpc_jobs/periodic_cleanup.yml

12 Hours is too short for debugging mnaio issues.

Increase instance age limit to 24 hours

---

pipeline_steps/common.groovy
pipeline_steps/github.groovy
pipeline_steps/horizon.groovy
pipeline_steps/kibana.groovy
pipeline_steps/maas.groovy
pipeline_steps/ssh_slave.groovy
playbooks/setup_jenkins_slave.yml
rpc_jobs/build_gating_venv.yml
rpc_jobs/sync_credential_store.yml

RPC-Gating currently builds a venv in the workspace of every node
that is used as part of a job. This is useful as we can rely on the
right version of various tools to be available, however it is network
intensive and slow. This commit reduces the time taken by using a pre
built venv when one is available.
* Adds a job to build a tar containing the rpc-gating venv and ansible
roles. This tar is pushed to rpc-repo, and named with the SHA of
rpc-gating it was built with. The most recent ten tars are kept.
This job is triggered by pushes to rpc-gating, so new versions
will automatically built as changes are merged.
* Adds functionality to common.install_ansible to check for a venv tar
if one exists, it is downloaded, expanded and fixed. Otherwise the
venv is built locally.
Jobs won't be …

RE-103 Store rpc-gating venvs

---

rpc_jobs/params.yml

The MNAIO tooling we use for multi-node tests is
currently using the head of the openstack-ansible-ops
repo, so any patch upstream could break our tests.
This patch sets the branch to use to the current
head of master's SHA.
Issue: [RE-136](https://rpc-openstack.atlassian.net/browse/RE-136)

RE-136 Pin openstack-ansible-ops repo

---

rpc_jobs/jjb_setup.yml

05ab12c9ad4bce1e67563548068a1fd6926d2fd1 has introduced a bug. The
parameter `RPC_GATING_BRANCH` is required but undefined. This commit
adds `rpc_gating_params` from the params file which includes the
required variable.
Issue: [RE-142](https://rpc-openstack.atlassian.net/browse/RE-142)

RE-142 Fix Merge-Trigger-JJB job

---

pipeline_steps/multi_node_aio_prepare.groovy

A repo can only be cloned at a ref that has been fetched, as there
is no tag for the SHA we are using, it can't be fetched directly.
This commit clones master, then checks out the required SHA as a
second step.
Issue: [RE-143](https://rpc-openstack.atlassian.net/browse/RE-143)

RE-143 Separate Clone and checkout steps

---

rpc_jobs/hw_multi_node_aio.yml
rpc_jobs/multi_node_aio.yml
rpc_jobs/rpc_aio.yml

The newton-14.0 branch for rpc-openstack has been
removed, so the jenkins jobs for it should also be
removed.
Issue: [RE-148](https://rpc-openstack.atlassian.net/browse/RE-148)

RE-148 Remove newton-14.0 branch from gating

---

rpc_jobs/hardening.yml
rpc_jobs/hw_multi_node_aio.yml
rpc_jobs/multi_node_aio.yml
rpc_jobs/params.yml

Currently, jobs that use pipeline_steps/multi_node_aio_prepare.groovy
are failing if they do not have the COMPUTE_NODES and VOLUME_NODES
parameters defined.  Since these parameters are necessary for anything
using pipeline_steps/multi_node_aio_prepare.groovy, we add the params
to rpc_jobs/params.yml instead.
Issue: [RE-145](https://rpc-openstack.atlassian.net/browse/RE-145)

RE-145 Move mnaio params to params.yml

---

rpc_jobs/rpc_artifact_build.yml

Currently only the newton-14.1 branch is used.
This patch sets it to work with any branch
prefixed with the word 'newton' to cover the
mainline development branch and the 'newton-rc'
branch.
Issue: [RE-151](https://rpc-openstack.atlassian.net/browse/RE-151)

RE-151 Set artifact jobs for all newton branches

---

pipeline_steps/deploy.groovy
rpc_jobs/hw_multi_node_aio.yml
rpc_jobs/multi_node_aio.yml
rpc_jobs/rpc_aio.yml

This branch is now finalised, so the jobs are no longer required.
Issue: [RE-170](https://rpc-openstack.atlassian.net/browse/RE-170)

RE-170 Remove newton-14.1 jobs

---

pipeline_steps/pubcloud.groovy
pipeline_steps/ssh_slave.groovy

Stages should be used for organising a job, jenkins internals
(such as allocating instances) should not be exposed as stages.
This is important because nested stages are not well supported, though
work is in progress to improve that for blue ocean.

RE-133 Convert allocation stages into steps

---

rpc_jobs/rpc_aio.yml

Currently, if we're running an upgrade job, we run prepareRpcGit()
using UPGRADE_FROM_REF, which isn't correct.  This means we're
actually not running is_doc_update_pr() against the checkout for the PR
that triggered the job.
Issue: [RE-157](https://rpc-openstack.atlassian.net/browse/RE-157)

RE-157 Allow prepareRpcGit() to figure out branch

---

pipeline_steps/common.groovy

This allows us to avoid the CentOS slave, even when puppet sets it back to "Use as much as possible". CentOS slaves may be allocated using `internal_slave()`

Require pubcloud_multiuse label for shared_slave

---

pipeline_steps/aio_prepare.groovy

Currently, when we do a minor upgrade the initial checkout is of the
current branch, and not UPGRADE_FROM_REF.
Issue: [RE-156](https://rpc-openstack.atlassian.net/browse/RE-156)

RE-156 Checkout UPGRADE_FROM_REF on minor upgrade

---

pipeline_steps/pubcloud.groovy
playbooks/allocate_pubcloud.yml

* Removes pubcloud.create as its only used once
* Allows instance creation params to be supplied by environment
or argument.
* Hard codes keyname and count, as they weren't fully exposed previously
and may cause problems if changed.

RE-133 Make runonpubcloud take an image parameter

---

pipeline_steps/artifact_build.groovy

In #370 the runonpubcloud function was modified to take an image
parameter as we need to use different images in parallel. However
the artifact build groovy functions were not updated to supply the image
parameter and will still setting the image env var instead.
Setting the env var causes problems with parallelism as the env
is shared between parallel branches.

RE-133 Pass image param to runonpubcloud

---

rpc_jobs/rpc_aio.yml

Currently, the minorupgrade is upgrading r14.0.1 to newton, which is
actually skipping a minor release.  This commit changes rpc_aio.yml to
upgrade r14.1.0 to newton instead.
Issue: [RE-175](https://rpc-openstack.atlassian.net/browse/RE-175)

RE-175 Change minorupgrade to run from r14.1.0

---

pipeline_steps/aio_prepare.groovy
pipeline_steps/common.groovy
pipeline_steps/deploy.groovy
pipeline_steps/github.groovy
pipeline_steps/influx.groovy
pipeline_steps/irr_role_tests.groovy
pipeline_steps/kibana.groovy
pipeline_steps/maas.groovy
pipeline_steps/multi_node_aio_prepare.groovy
pipeline_steps/pubcloud.groovy
pipeline_steps/ssh_slave.groovy
pipeline_steps/webhooks.groovy
playbooks/allocate_pubcloud.yml
rpc_jobs/rpc_artifact_build.yml

In groovy untyped variables are almost global. In order to prevent
conflicts when using parallel, when need to ensure all variables are
typed and therefore scoped.
Also adds a random string to the vars file written by the venvplaybook
function to avoid conflicts.

RE-133 Ensure variables are typed/scoped

---

playbooks/allocate_pubcloud.yml

We've hit a rate limit in DFW, and having builds retry 120x is
excessive.  This commit drastically reduces to 5 retries to avoid us
exceeding our rate limit.

Reduce pubcloud build retry count

---

rpc_jobs/defaults.yml

We've hit a rate limit in DFW and have a critical patch that needs to
gate.  This PR temporarily flips all builds to IAD so we can get this
PR to gate.

Flip builds to IAD

---

rpc_jobs/single_use_slave_template.yml

The Single-Use-Slave-Example job currently does not clear out old
builds, which resulted in master jenkins running out of space.
This commit updates Single-Use-Slave-Example to discard builds when
there are more than 30.

RE-190 Discard builds when more than 30

---

pipeline_steps/common.groovy

The gating venv doesn't include the selinux module as its created on
ubuntu so this module must be copied in when unpacking the venv.

RE-193 Add python-selinux when unpacking venv

---

rpc_jobs/rpc_aio.yml

We need to:
- Avoid running tempest many times for no reason, 1 per branch
is enough during upgrades.
- Still install tempest if need be (for resource gen)
That shouldn't break stuff, while making our life easier.

Cleanup tempest execution

---

constraints.txt
influx-reports/influx-report.sh
influx-reports/influx.py
requirements.txt

Gating could ship this small tool to query influx db based
on env vars. When running a job, we could check for the presence
of the tool, and run it. That would output results to stdout.
On top of that, we could run the tool with parameters to have
artefacts (YAML/subunit) of the data.
Issue: [LA-372](https://rpc-openstack.atlassian.net/browse/LA-372)

LA-372 Influx reporting in gating tooling

---

pipeline_steps/common.groovy
pipeline_steps/irr_role_tests.groovy
pipeline_steps/pubcloud.groovy
rpc_jobs/ops_fabric_chatbot.yml
rpc_jobs/rpc_gating_lint.yml

This is my first attempt at adding a gate job for the
rcbops/ops-fabric-chatbot repo. I want this job to:
- Install any needed dependencies (ops-fabric-chatbot/install-deps.sh)
- Run tests (ops-fabric-chatbot/run-tests.sh)
I would like this job to fail if either of the above commands return
exit code != 0. A timeout of 5 minutes would be good, too, but I haven't
implemented that yet.
Issue: [TURTLES-67](https://rpc-openstack.atlassian.net/browse/TURTLES-67)

TURTLES-67 Add gate job for ops fabric chatbot

---

Dockerfile

The git-core package needs to be installed into the
container in order to handle git commands.
All packages are now installed in a single line to
be a little more optimal, and the 'apt-get update'
is done on a seperate line to ensure that a failed
update is exposed properly.

Add git-core to Dockerfile

---

rpc_jobs/rpc_gating_lint.yml

The RPC-Gating-Lint job is currently failing because we're attempting to
use git inside the container before it's been configured.  This commit
simply adds a configure_git() inside the container so it's properly
prepped.  There may be a more suitable place to put this so we don't
have to explicitly do this inside each container, however we can look at
that further in a subsequent patch.
Additionally, we have to cd into rpc-gating otherwise the lint.sh fails
due to the .venv in ${WORKSPACE}.  Oddly this cd was not required
before [1] merged so some behaviour has changed somewhere making this
necessary now.  Adding a simple dir() to change directory using groovy
logs the following to the console:
JENKINS-33510: working directory will be \
/var/lib/jenkins/workspace/RPC-Gating-Lint not \ …

RE-216 Configure git before checkout

---

pipeline_steps/common.groovy

Commit 7481a60 changed the way the git repo was
cloned, causing a 'remote already exists' error
when being executed on a long running slave.
This patch ensures that the remote is removed before
being added.
Issue: [RE-211](https://rpc-openstack.atlassian.net/browse/RE-211)

RE-211 Remove the origin before adding it

---

rpc_jobs/params.yml

The current SHA is broken (cobbler26 no longer available), and upstream
has completely rewritten the mnaio build tool which will require a
bunch of RE effort to integrate into rpc-gating.  As a stop gate, we're
going to use a fork of openstack-ansible-ops so we can continue to use
the mnaio jobs until we're able to bump to the head of
openstack-ansible-ops.
Issue: [RE-220](https://rpc-openstack.atlassian.net/browse/RE-220)

RE-220 Use fork of openstack-ansible-ops

---

pipeline_steps/multi_node_aio_prepare.groovy
pipeline_steps/ssh_slave.groovy

01eac2741173f3016e016f0cbcb31d986ff5c25c modified the process of
stashing the inventory. This change resulted in `connect_deploy_node`
creating a stash that neither used the default name nor passed the
correct name to `ssh_slave.connect`.
This change updates `connect_deploy_node` to use the default.
The setting of the default for `args.inventory` is also fixed so that
the value is correctly assigned.
Issue: [RE-188](https://rpc-openstack.atlassian.net/browse/RE-188)

RE-188 Fix stashing of multi-node inventory

---

pipeline_steps/common.groovy

Instead of checking the index file, try and download and unpack the
venv tar, if that succeeds unpack it, else create the venv locally.
This is to prevent problems where the tar is listed in the index
but is not fully written/synced, so the job attempts to download it
but either that or unpacking fails.
Issue: [RE-199](https://rpc-openstack.atlassian.net/browse/RE-199)

RE-199 Improve test for venv availability

---

rpc_jobs/single_use_slave_template.yml

The master was filling up with disk space as the rpc-gating dir
and workspace venv were collected along with the report files.
To avoid this, report files are moved to a subdirectory.
Issue: [RE-209](https://rpc-openstack.atlassian.net/browse/RE-209)

RE-209 Avoid archiving venv with html report

---

scripts/docker_cleanup.sh

This is likely to be more reliable than awking the output.
The awk version missed some containers as they didn't contain
"Exited" in the status field even though they were no longer running.
Issue: [RE-201](https://rpc-openstack.atlassian.net/browse/RE-201)

RE-201 Use docker cli's filtering instead of awk

---

pipeline_steps/deploy.groovy

The pre-upgrade role requires routers, etc. to exist and the removal
of tempest.tempest() from the initial deployment of a major upgrade has
resulted in our major upgrade jobs failing:
```
TASK: [rpc_pre_upgrade | Write file containing agent for each router] *********
[0;31mfatal: [localhost] => with_items expects a list or a set[0m
[0;31m
FATAL: all hosts have already failed -- aborting[0m
```
It looks like these tasks need to be updated to handle no routers in
an env, but at the same time we want to ensure we have resources so
these tasks are being exercised correctly.
Issue: [RE-223](https://rpc-openstack.atlassian.net/browse/RE-223)

RE-223 Deploy tempest resources for major upgrade

---

rpc_jobs/long_running_slave.yml

Double brackets are only required in job templates, not jobs.

Remove unnecessary double brackets

---

pipeline_steps/pubcloud.groovy

Cleanup errors are an RE problem, not an indication that the code
under test is bad.
Issue: [RE-224](https://rpc-openstack.atlassian.net/browse/RE-224)

RE-224 prevent cleanup errors from failing a build

---

rpc_jobs/rpc_aio.yml

Re-order the tests to ensure that Tempest runs
before Kibana, then Holland.
The deploy tests all verify that everything is
working for the source branch, so no need to
re-test for upgrades. Also, the MNAIO test
implementation does the more thorough test
regime of before and after.
The tests are now all consistent across all
'actions'. They always run in the same order,
always run for all tests and always use the
same settings. This is simpler to read and
understand what's going on.
Issue: [RE-225](https://rpc-openstack.atlassian.net/browse/RE-225)

RE-225 Re-order & make RPC-O AIO test consistent

---

rpc_jobs/rpc_aio.yml

RO periodic failure issues were not being created as the block that creates them was after a throw statement so was never reached.

Move issue creation to before throw statement

---

pipeline_steps/common.groovy
webhooktranslator/webhooktranslator/webhooktranslator.py

The Aglie Analytics tool is unable to filter on JIRA ticket labels, so
we need to ensrue gate failure tickets are created with a bespoke issue
type (Issue-releng-platform-alert) which we *can* filter on
Issue: [RE-359](https://rpc-openstack.atlassian.net/browse/RE-359)

RE-359 change gate failure ticket type to 'Issue-gate-failure'

---

pipeline_steps/common.groovy
playbooks/archive_artifacts.yml
rpc_jobs/multi_node_aio.yml

The change updates the `multi_node_aio.yml` so that multi-node builds
now have their log/config artefacts saved. To enable this to work
`archive_artifacts` has been modified to support both AIO and MNAIO
builds.
Issue: [LA-408](https://rpc-openstack.atlassian.net/browse/LA-408)

LA-408 Archive log/config artefacts for MNAIOs

---

rpc_jobs/ops_fabric_analytics.yml

This adds a gate job for the ops-fabric-analytics repo. I copied most of this from the chatbot gate PR.
I am not sure that I have API access to Jenkins, so I have not tested
this yet.
The goal of this gate is to return failed status if any of the tox (py35
or pep8 tests) fail. JUnit output is nice to have, but I would rather
have a working gate more quickly if possible.
The one part I'm not sure of is if tox exists in the container at
the time the tests are run.
Issue: [TURTLES-67](https://rpc-openstack.atlassian.net/browse/TURTLES-67)

TURTLES-67 Add ops fabric analytics service gate

---

rpc_jobs/hardening.yml
rpc_jobs/hw_multi_node_aio.yml
rpc_jobs/multi_node_aio.yml

Current MNAIO jobs are failing with:
```
--2017-09-08 00:53:50--  http://releases.ubuntu.com/16.04/ubuntu-16.04.2-server-amd64.iso
Resolving releases.ubuntu.com (releases.ubuntu.com)... 91.189.88.23, 2001:6b0:e:2018::1337
Connecting to releases.ubuntu.com (releases.ubuntu.com)|91.189.88.23|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-09-08 00:53:50 ERROR 404: Not Found.
```
Issue: [RE-398](https://rpc-openstack.atlassian.net/browse/RE-398)

RE-398 Use latest Ubuntu 16.04 ISO

---

pipeline_steps/deploy.groovy
playbooks/vars/all.yml
playbooks/vars/onmetal.yml

The running of `generate-resources.yml` is now managed by rpc-openstack,
the code to perform that function here is removed.
To ensure that Telegraf is properly installed during the upgrade phase
of an upgrade, the appropriate credentials are supplied to the upgrade
script.
To test instance networking a number have vars are set because pinging
using the floating IP address does not work with the default
configuration when using vxlan.
Issue: [LA-436](https://rpc-openstack.atlassian.net/browse/LA-436)

LA-436 Fix issues relating to testing instances

---

rpc_jobs/multi_node_aio.yml
rpc_jobs/rpc_aio.yml

Adds Kilo Leapfrog PRs to the exclude list for MultiAIO and AIO:
Issue: [RLM-204](https://rpc-openstack.atlassian.net/browse/RLM-204)

RLM-204 Move Kilo Leapfrog Jobs to Periodic Only

---

rpc_jobs/rpc_aio.yml

There is no trigger axis, so trigger: pr was ignored in 2e774d7.
Issue: [RLM-204](https://rpc-openstack.atlassian.net/browse/RLM-204)

RLM-204 Trigger axis is called ztrigger

---

rpc_jobs/rpc_aio.yml

Issues are not getting created in the RO project for aio build failures. Its not clear to me why, this commit adds logging to determine whether issue creation is attempted.

Add issue creation logging

---

rpc_jobs/rpc_aio.yml
rpc_jobs/rpc_gating_lint.yml

Currently the mechanism that creates a jira issue when a periodic
build fails is not working. The problem is a call:
common.create_jira_issue(project="RO")
This looks like a calll that passes a keyword argument, its not. Its
an assignment with a function call. In CPS groovy assignments return
null, so this is effectively common.create_jira_issue(null).
The fix is to remove project=.
Issue: [RLM-204](https://rpc-openstack.atlassian.net/browse/RLM-204)

RLM-204 Fix build failure issue creation

---

influx-reports/influx-report.sh

The use of python in the virtual env `.venv` was incorrectly removed.
This change adds it back so the script `influx.py` is run with the
required dependencies.
Issue: [LA-436](https://rpc-openstack.atlassian.net/browse/LA-436)

LA-436 Re-add Python path in influx-report.sh

---

pipeline_steps/common.groovy
pipeline_steps/multi_node_aio_prepare.groovy

This changes updates how the OSA SHA is identified, for use by the
openstack-ansible-ops multi-nodes scripts, so that it accounts for use
of a submodule or being specified in a file. This change is required due
to the RPCO commit 4d12456c1ab1111823e7b0cb8f01d37a4b2a7f4f.
Issue: [RE-451](https://rpc-openstack.atlassian.net/browse/RE-451)

RE-451 Fix bug getting OSA SHA on multi-node

---

playbooks/allocate_pubcloud.yml

This patch allows us to build RAX instances without automatic
updates applied by the Rackspace agent. Automatic updates are causing
problems with artifacting and general gate jobs.
The documentation for this option is here:
https://support.rackspace.com/how-to/cloud-server-configuration-options/
Issue: [RE-458](https://rpc-openstack.atlassian.net/browse/RE-458)

RE-458 Build RAX instances with build_config=core

---

rpc_jobs/multi_node_aio_leapfrog.yml

Adds multi-node AIO gate jobs for Kilo Leapfrog Testing.  Uses small resources only to limit the number of jobs, can be adjusted as we determine our testing needs.
Issue: [RLM-58](https://rpc-openstack.atlassian.net/browse/RLM-58)

RLM-58 Multi-node AIO gate jobs for Kilo Leapfrog testing

---

rpc_jobs/rpc_aio_leapfrog.yml

Creates a seperate rpc_aio_leapfrog job to avoid stepping on
existing jobs in place.  Tests desired kilo branches for leapfrogs
as periodic jobs.
Reopening as a branch on the main repo, closed https://github.com/rcbops/rpc-gating/pull/416
Issue: [RLM-58](https://rpc-openstack.atlassian.net/browse/RLM-58)

RLM-58: Adds periodic AIO leapfrog jobs for deployed versions of kilo

---

playbooks/allocate_pubcloud.yml
scripts/user_data_pubcloud.sh

The default public cloud image includes the unattended
upgrades package which automatically upgrades all
installed packages when booting the instance.
RPC-O instance builds must not automatically upgrade
packages on boot as the test may require the use of
the apt artifacts repo which has differing, often older,
packages than those available upstream.
This patch uses cloud-init to prevent unattended
upgrades executing on boot.
Issue: [RE-473](https://rpc-openstack.atlassian.net/browse/RE-473)
Issue: [RE-458](https://rpc-openstack.atlassian.net/browse/RE-458)

RE-458 Prevent unattended upgrades executing

---

rpc_jobs/rpc_aio.yml

This is required because the default issue type `Issue-releng-platform-alert` is not available in the RO project.
Test job: https://rpc.jenkins.cit.rackspace.net/job/scratchpipeline/413/console
Test job definition:
```
library "rpc-gating@master"
common.shared_slave(){
common.create_jira_issue("RO", env.BUILD_TAG, env.BUILD_URL, "Task")
}
throw new Exception("stop now")
```
Resulting Issue: https://rpc-openstack.atlassian.net/projects/RO/issues/RO-2471?filter=allopenissues&orderby=created+DESC%2C+priority+DESC%2C+updated+DESC

Set issue type for RPCO periodic failure issues.

---

rpc_jobs/jjb_setup.yml

Currently JJB runs whenever a commit is pushed to any branch in rcbops/rpc-gating. Everytime it runs it deploys master, so it should only run when master changes. 
This is especially annoying if you are testing a job from a different branch, as when you push to your branch the JJB job will be triggered and revert the job to its master state.

Prevent Unnecessary JJB Runs

---

rpc_jobs/periodic_cleanup.yml

These are built on PRs to rpc-gating as a way of testing the mechanism for booting instances and attaching them as Jenkins slaves. However sometimes cleanup fails, so we need to sweep these instances in the periodic cleanup job.

Clean up Single use slave example instances.

---

rpc_jobs/multi_node_aio.yml
rpc_jobs/multi_node_aio_leapfrog.yml
rpc_jobs/rpc_aio.yml
rpc_jobs/rpc_aio_leapfrog.yml

* Removes all kilo point release branch jobs from
AIO/Multi as we are not going to test test individual
point release of Kilo
* Sets up K->N, K->N-14.2.0, L->N, L-> N-14.2.0 Periodics
as these will be our primary gate jobs to know if things broke.
Since we're getting ready for Liberty, adding these now as well.
* Moves leapfrogupgrade items to the _leapfrog config files, so
we can avoid issues with the existing jobs and own changes in
our config
Issue: [RLM-214](https://rpc-openstack.atlassian.net/browse/RLM-214)

RLM-214 Leapfrog Gate Job Modifications

---

pipeline_steps/webhooks.groovy

CIT Jenkins is hosted internally with no forwarding for receiving
webhooks from github. To work around this we host a webhook proxy
in public cloud, this runs nginx, receives webhooks from github and
forwards them via an ssh tunnel to CIT Jenkins.
The ssh tunnel must be started on the Jenkins master and connect
out to the webhook proxy node as connections in the other direction
are not possible. The webhook setup job creates a script on the
Jenkins master that in turn creates an upstart job to manage the tunnel.
This commit improves the upstart job by removing the respawn limit
and adding a delay between respawn attempts.
Issue: [RE-577](https://rpc-openstack.atlassian.net/browse/RE-577)

RE-577 Improve respawn behaviour of webhook tunnel

---

pipeline_steps/common.groovy
pipeline_steps/irr_role_tests.groovy
pipeline_steps/pubcloud.groovy
playbooks/archive_artifacts.yml
playbooks/templates/cloudfiles.html.j2
playbooks/upload_to_cloud_files.yml
rpc_jobs/single_use_slave_template.yml

Artefacts, such as logs and configuration files, need to be stored for
finished builds. This commit changes some aspects of how this is done to
provide a cleaner separation between the responsibilities of RE and its
customers.
With this change `upload_to_cloud_files.yml` is now responsible for
taking the data to be archived, creating an appropriately named
compressed tarball, and uploading it to Cloud Files. This reduces the
responsibility of `archive_artifacts.yml`, the RPCO-specific artefact
script, to collecting all the required data into one directory.
`html_report_dest` is removed given there is no need to be able to
override it, the report file is created temporarily and is not something
that needs to be configured for a job.
The result of these changes is that any job must store …

RE-207 Standardise elements of archiving artefacts

---

playbooks/archive_artifacts.yml

Commit 13a82431 introduced a bug due to an extra pair of `}}` in an
Ansible var. This commit removes them to fix the collection of build
artefacts.
Issue: [RE-584](https://rpc-openstack.atlassian.net/browse/RE-584)

RE-584 Remove unnecessary brackets

---

rpc_jobs/irr_role_test.yml

In order to make the job definition easier to understand
the MaaS and Logstash jobs are broken out into seperate
projects.
Issue: [RE-557](https://rpc-openstack.atlassian.net/browse/RE-557)

RE-557 Improve IRR JJB readability

---

pipeline_steps/aio_prepare.groovy
rpc_jobs/multi_node_aio.yml
rpc_jobs/params.yml
rpc_jobs/rpc_aio.yml

Adds periodic and PR jobs to run ironic
deployments. PR jobs only run if trigger
phrase is used to reduce resource
consumption.
Issue: [RQE-237](https://rpc-openstack.atlassian.net/browse/RQE-237)

RQE-237 Add Ironic gate jobs

---

pipeline_steps/multi_node_aio_prepare.groovy
playbooks/vars/onmetal.yml
rpc_jobs/multi_node_aio.yml

Use deploy.sh and CONFIGURE_MNAIO if mnaio_config
exists in the rpc-openstack branch. Otherwise,
use current method for config prep, now done
on the deploy VM directly.
Issue: [RE-97](https://rpc-openstack.atlassian.net/browse/RE-97)

RE-97 Add support for rpco multi-node AIO config prep

---

rpc_jobs/rpc_aio.yml

Currently only the 'newton' branch is tested, leaving
out the 'newton-rc' branch. This patch updates the job
definition to ensure that the PR tests also run against
the 'newton-rc' branch or any other newton prefixed
name.
Issue: [RE-590](https://rpc-openstack.atlassian.net/browse/RE-590)

RE-590 Include all newton.* branches for PR tests

---

pipeline_steps/common.groovy

When updating release note hooks the deployment
tests do not need to execute. These files should
be tested in a lint, docs or reno specific test.
Issue: [RE-612](https://rpc-openstack.atlassian.net/browse/RE-612)

RE-612 Skip deploy test for reno hook files

---

pipeline_steps/irr_role_tests.groovy
pipeline_steps/pubcloud.groovy

Currently IRR jobs are failing as they write logs to WORKSPACE/logs,
but the artifact upload playbook is expecting them in
WORKSPACE/artifacts. This commit implements the first part of the
solution which is to skip upload if WORKSPACE/artifacts doesn't
exist.
The second half is to modify IRR jobs to write artifacts into
WORKSPACE/artifacts so they are archive correctly.
This commit also removes artifact compression from the IRR job
as that is now handled in pubcloud.uploadToCloudFiles.
Issue: [RE-613](https://rpc-openstack.atlassian.net/browse/RE-613)

RE-613 Skip artifact upload if dir not found

---

pipeline_steps/irr_role_tests.groovy

Recently we standardised the artifact location to WORKSPACE/artifacts
but also decided that projects should not rely on that, instead
they should read the RE_HOOK_ARTIFACTS_DIR environment variable
in order to determine the correct place to place artifacts.
This commit ensures that the artifacts and test result env vars
are available in IRR jobs.
Issue: [RE-613](https://rpc-openstack.atlassian.net/browse/RE-613)

RE-613 Set artifact environment vars in IRR jobs

---

pipeline_steps/irr_role_tests.groovy

The right env var is defined in https://rpc-openstack.atlassian.net/wiki/spaces/RE/pages/19005457/RE+for+Projects
Issue: [RE-613](https://rpc-openstack.atlassian.net/browse/RE-613)

RE-613 Fix env var spelling

---

pipeline_steps/common.groovy

When updating hooks for non-deploy tests the
deployment tests do not need to execute. These
files should be tested in a lint, docs or reno
specific test.
Issue: [RE-197](https://rpc-openstack.atlassian.net/browse/RE-197)

RE-197 Skip deploy test for non-deploy hook files

---

pipeline_steps/multi_node_aio_prepare.groovy
playbooks/vars/onmetal.yml
rpc_jobs/multi_node_aio.yml

This reverts commit 5421edb83c78118db8db7be0ccafae318bec31ee.
This is being done as we're holding off on implementing the other half
of this work in rpc-openstack, so reverting this change to simplify
things until this code is moved entirely out of rpc-gating.
Issue: [RE-97](https://rpc-openstack.atlassian.net/browse/RE-97)

RE-97 Revert "RE-97 Add support for rpco multi-node AIO config prep"

---

rpc_jobs/irr_role_test.yml

This axis will be used for the MaaS jobs to deploy with ceph
or no additional storage backend.
Note that this commit does not implement a ceph deploy for rpc-maas,
it provides a new environment variable (IRR_SCENARIO=deploy/ceph)
which rpc-maas/run_tests.sh can use to deploy and test the correct
scenario. This variable will also be provided to all the other IRR
jobs, but they can safely ignore it until they need multiple scenarios.
Issue: [HUM-330](https://rpc-openstack.atlassian.net/browse/HUM-330)

HUM-330 add ceph job for rpc-maas 

---

pipeline_steps/multi_node_aio_prepare.groovy
rpc_jobs/params.yml

To help alleviate memory usage on the MNAIO, disable metering services and moves to latest commit on osa_ops.
See https://github.com/rcbops/rpc-gating/pull/443/ for @mattt416 previous commit that was closed.
Issue: [RLM-221](https://rpc-openstack.atlassian.net/browse/RLM-221)

RLM-221 - Disable MNAIO Metering Services

---

rpc_jobs/dep_update.yml

The template was implemented in a previous PR, this commit introduces
a job for the newton branch.
Issue: [RE-197](https://rpc-openstack.atlassian.net/browse/RE-197)

RE-197 Add dep update job for rpco/newton

---

gating/pre_merge_test/run
pipeline_steps/artifact_build.groovy
pipeline_steps/common.groovy
pipeline_steps/irr_role_tests.groovy
rpc_jobs/multi_node_aio.yml
rpc_jobs/rpc_aio.yml
rpc_jobs/standard_job_premerge.yml

As documented in [1] this patch implements a standard
job for the pre_merge_test hook. It also implements
a job for the rpc-gating repository to execute it
which can replace the current Single-Use-Slave-Example
job.
The artifact publishing across all jobs now also uses
a common function - this removes the current duplication
and ensures consistency in the application. In order to
achieve this the collection of job artifacts for the
RPC-O jobs has been ranamed to be RPC-O spcific.
[1] https://rpc-openstack.atlassian.net/wiki/spaces/RE/pages/19005457/RE+for+Projects
Issue: [RE-506](https://rpc-openstack.atlassian.net/browse/RE-506)

RE-506 Implement pre_merge_test standard job

---

playbooks/setup_jenkins_slave.yml

Was having issues with some jobs timing out
and losing their connection to the slave.
Removing the ssh role seemed to fix the problem
so I tried the ClientAliveInterval and it seemed
to help correct the issue.
15 sec is probably too low for the server to hear
back from the client, so removing this to see if
it helps get rid of the
"hudson.remoting.RequestAbortedException:
java.io.IOException: Unexpected termination of the
channel" errors
https://rpc.jenkins.cit.rackspace.net/view/Leapfrog/job/OnMetal-Multi-Node-AIO_r14.2.0-kilo-trusty-leapfrogupgrade-small-periodic/
Was failing consistently until job #11. (#9 was testing removing the sshd role)
Issue: [RLM-219](https://rpc-openstack.atlassian.net/browse/RLM-219)

RLM-219 Remove ClientAliveInterval from sshd role

---

rpc_jobs/rpc_aio.yml
rpc_jobs/rpc_aio_leapfrog.yml

Attempts to free up resources on the AIO to allow Tempest tests to fully pass.

RLM-232 Don't deploy Telegraf on AIO installs

---

scripts/release.py

This change explicitly exposes the GitHub HTTPS URL to the
generate_release_notes project hook script. This removes the need for
the project to inspect the repo and prevents any impact if the cloned
repo configuration is changed.
Issue: [RE-621](https://rpc-openstack.atlassian.net/browse/RE-621)

RE-621 Supply project hook script with repo URL

---

rpc_jobs/standard_job_premerge.yml

The post script typically does the log collection, so
we make sure that it always runs for pre_merge_tests.
Issue: [RE-701](https://rpc-openstack.atlassian.net/browse/RE-701)

RE-701 Make post script always run for pre_merge_test

---

rpc_jobs/params.yml

The package, linux-image-generic, should be used by the MNAIO to ensure
we're testing with the supported LTS kernel for the distro being
deployed.
Upstream:
https://github.com/openstack/openstack-ansible-ops/commit/cc9294bb0d4191bf6a78ef15b02bcaed86cdd709
Issue: [RLM-228](https://rpc-openstack.atlassian.net/browse/RLM-228)

RLM-228 Change kernel to linux-image-generic

---

rpc_jobs/build_gating_venv.yml

This job is failing as files are changing whilst being tarred.
This should not happen as the job does not allow parallelism. Adding
a lock to debug and make serialisation explicit.
Added:
- `try(){ deleteDir() ... } finally { deleteDir()} `
- `lock('build_gating_venv')`
Other changes are indentation only
Issue: [RE-731](https://rpc-openstack.atlassian.net/browse/RE-731)

RE-731 Add lock around build gating venv job

---

job_dsl/release.groovy
rpc_jobs/release.yml
scripts/ghutils.py
scripts/release.py

This change addresses some issues with generating release notes:
- notes were being generated from a ref (branch), there was nothing to
guarantee this did not change when running the release code
- rpc-differ, and reno when support is added in rpc-openstack, require
the tag name to produce correctly worded notes
To ensure the tag is created at the start of the process, a new
function `publish_tag` is added to handle pushing the tag to the
repository. This removes that burden from `create_release` with the
added benefit that new tags are annotated (GitHub only creates
lightweight tags).
To enable the tag to be pushed the job now provides access to the
Jenkins GitHub SSH key.
`generate_release_notes` now sets `RE_HOOK_VERSION` to be the version
and not the ref, this is both more intuitive …

RE-621 Publish tag before generating release notes

---

pipeline_steps/common.groovy
pipeline_steps/webhooks.groovy
playbooks/phobos_tunnel.yml
playbooks/setup_jenkins_slave.yml
playbooks/templates/phobostunnel_service.j2
playbooks/webhooks.yml
rpc_jobs/webhook.yml

As internal routing between CIT jenkins and the Phobos environment
is not possible in the short term, a tunnel is added.
The deploy-phobos container in the phobos environment will connect
to the webhook proxy node via ssh. The ssh connection will carry
a reverse port forward such that any connections to port 2223 on
the webhook proxy  node will be forwarded to port 22 on deploy-phobos.
Jenkins will ssh to webhookproxy:2223 when it requires a connection
to deploy-phobos.
Issue: [RE-643](https://rpc-openstack.atlassian.net/browse/RE-643)

RE-643 Phobos <--> Webhook Proxy Tunnel

---

pipeline_steps/artifact_build.groovy

As the apt artifacts are built using a long-lived
node, the jenkins workspace should be used for the
git checkout the job does to prevent the constant
back-and-forth switching between branches from
interfering with each other.
The script being executed from rpc-openstack does
a symlink from the current directory to the expected
path of /opt/rpc-openstack so everything else should
continue to work as expected.
Issue: [RO-2796](https://rpc-openstack.atlassian.net/browse/RO-2796)

RO-2796 Use workspace for apt artifact checkout

---

rpc_jobs/rpc_aio.yml

Currently the minorupgrade tests are extending
test time for PR's and due to their non-voting
nature they're not being properly reviewed
anyway. This removes them from PR tests and
leaves them in place for periodics only.
Issue: [RLM-227](https://rpc-openstack.atlassian.net/browse/RLM-227)

RLM-227 Remove minorupgrades tests from PR's

---

rpc_jobs/jjb_setup.yml

Currently, Merge-Trigger-JJB fires irrespective of the branch on
rcbops/rpc-gating being pushed to.  We tried to circumvent this by
using GIT_BRANCH inside the pipeline script, however that environment
variable is not being passed in and therefore this job will never build
the Jenkins-Job-Builder job.
Since there is no clear way to get a pipeline script to only trigger
when a specific branch is being pushed to, we need to convert this job
to a freestyle job where we can specify the scm and specific branch(es)
we wish to build against (master, in this case).
NOTE: It's likely we'll need to delete the existing Merge-Trigger-JJB
job when this merges, as I don't believe JJB will change project
types on an existing job.
Issue: [RE-634](https://rpc-openstack.atlassian.net/browse/RE-634)

RE-634 Change Merge-Trigger-JJB to freestyle job

---

rpc_jobs/irr_role_test.yml

This builds out the Liberty specific test matrix and removes
11.0.0 from kilo as its not used anywhere and of no benifit
to us at this time.
Issue: https://rpc-openstack.atlassian.net/browse/RLM-225
Issue: [RLM-225](https://rpc-openstack.atlassian.net/browse/RLM-225)

Updated rpc-upgrades jobs

---

rpc_jobs/rpc_aio.yml
rpc_jobs/rpc_openstack.yml
rpc_jobs/standard_job_premerge.yml

This implements the standard pre_merge_hook for RPC-O.
Required merges for the jobs to work:
master: https://github.com/rcbops/rpc-openstack/pull/2582
newton: https://github.com/rcbops/rpc-openstack/pull/2586
mitaka: https://github.com/rcbops/rpc-openstack/pull/2588
liberty: https://github.com/rcbops/rpc-openstack/pull/2590
kilo: https://github.com/rcbops/rpc-openstack/pull/2591
Upgrade tests have been removed from PR tests as they will be replaced
by post merge tests due to the length of time they take to execute.
Issue: [RE-87](https://rpc-openstack.atlassian.net/browse/RE-87)
Issue: [RE-721](https://rpc-openstack.atlassian.net/browse/RE-721)
Issue: [RE-722](https://rpc-openstack.atlassian.net/browse/RE-722)
Issue: [RE-723](https://rpc-openstack.atlassian.net/browse/RE-723)
Issue: …

Use standard pre_merge_test hook for RPC-O

---

rpc_jobs/multi_node_aio.yml

Leapfrog was currently running after all tests.
This moves leapfrog to after deploy and before tests.
Also drops Kibana tests for now until we have a maintainer.
Issue: [RLM-264](https://rpc-openstack.atlassian.net/browse/RLM-264)

RLM-264 Move Leapfrog Upgrade before tests on MNAIO

---

rpc_jobs/params.yml

Bumps to head of master on https://github.com/openstack/openstack-ansible-ops/commit/835c2632f2b862600276d001313865605f34bdf5
MNAIO jobs needs the fix from https://github.com/openstack/openstack-ansible-ops/commit/d0cb21c139381fad1a526a29a9d3eb94bbe693de that provides more storage for the /var/lib/nova mount.
Issue: [RLM-261](https://rpc-openstack.atlassian.net/browse/RLM-261)

RLM-261 Bump to latest OSA_OPS for MNAIO fixes

---

rpc_jobs/rpc_aio_leapfrog.yml

Kibana is currently unmaintained and is causing
intermittent failures.  Remove the Kibana stages
from the gate jobs until we can find a maintainer
or correct the issues.
Issue: [RO-2781](https://rpc-openstack.atlassian.net/browse/RO-2781)

RO-2781 Remove Kibana stages from AIO jobs

---

rpc_jobs/multi_node_aio_leapfrog.yml
rpc_jobs/rpc_aio_leapfrog.yml

14.2.0-liberty job won't pass as 14.2.0 does not pull in the openstack-ansible-ops fixes for liberty.  Re-enable once next release is cut.
Issue: [RLM-262](https://rpc-openstack.atlassian.net/browse/RLM-262)

RLM-262 Disable 14.2.0-liberty job

---

job_dsl/release.groovy

I missed the fact that we already had a mailgun account setup, and had
DNS entries created for a domain created in a new mailgun account.
Rather than move the domain to the old mailgun account (which would
require updating the previously created DNS records), I've just added
new credentials in Jenkins for the new account.  We can remove the old
credentials or just leave them around in the event that we need to flip
over to another Mailgun account.
Issue: [RE-633](https://rpc-openstack.atlassian.net/browse/RE-633)

RE-633 Update mailgun creds

---

rpc_jobs/release.yml
scripts/ghutils.py
scripts/notifications.py

Issues:
The e-mail message body is set to the file path where the release notes
are saved. The command-line option `--body` is being incorrectly passed
the path instead of the actual text to use in the message.
In general, the sub-command `mailgun` should be run after
`generate_release_notes` and so the message body should not need to be
supplied however the click context object is not updated to include the
release notes and so the incorrectly supplied path is used instead.
Release notes should be formatted in GitHub Markdown, e-mail clients are
not guaranteed to present this in a reader-friendly format.
Change:
This change removes from `ghutils.create_release` the responsibility of
defining the message subject and consolidates all control of the e-mail
to the notifications file. To help …

RE-759 Fix notification e-mail message

---

gating/post_merge_test/run
lint.sh
pipeline_steps/common.groovy
rpc_jobs/standard_job_postmerge.yml

This commit implements the standard job for periodics.
It will also be the basis for merge triggered jobs, though that will
likely require a separate free-style job that triggers this one.
This commit also includes an implementation of the post_merge_test hook
for rpc-gating. That will create a periodic job that runs the lint
tests. That job can be used as an example for other projects.
Issue: [RE-507](https://rpc-openstack.atlassian.net/browse/RE-507)

RE-507 post merge job

---

rpc_jobs/standard_job_postmerge.yml

Currently, we're trying to create a directory called
env.ghprbGhRepository in the PM job, but this var is only available in
the PR jobs.  This commit slices up env.REPO_URL to determine the repo
name, and creates that instead.
Issue: [RE-784](https://rpc-openstack.atlassian.net/browse/RE-784)

RE-784 Remove env.ghprbGhRepository reference

---

rpc_jobs/rpc_aio.yml
rpc_jobs/rpc_octavia.yml
rpc_jobs/rpc_openstack.yml
rpc_jobs/standard_job_postmerge.yml
rpc_jobs/standard_job_premerge.yml
scripts/lint_naming_conventions.py

Currently, standard_job_postmerge.yml and standard_job_premerge.yml use
the project name in the job template name.  For rpc_openstack.yml as it
stands, this worked fine.  However, as we go to add post merge jobs into
that file we run into a problem where we cannot use duplicate project
names and need to start injecting additional identifiers into the
project names to avoid collision.  The downside here is that these
names are injected into the job names meaning we'll end up with a slew
of job names that are inconsistent and contain potentially redundant
information.
To address, this commit does the following:
1. Changes the job template name in standard_job_postmerge.yml to
`PM_{repo_name}-{branch}-{image}-{scenario}-{action}`.  The idea
here is that we specify a `repo_name` in each …

RE-784 Standardise pre and post job names

---

rpc_jobs/rpc_aio.yml

Kibana is unmaintained at this time and blocking forward progress within
the repo. This change comments out the Kibana tests. Once we have a
maintainer for this effort we can re-instate the Kibana tests assuming
they're able to be fixed.
Signed-off-by: Kevin Carter kevin.carter@rackspace.com
Issue: [RO-2781](https://rpc-openstack.atlassian.net/browse/RO-2781)

RO-2781 Remove the Kibana work from the gate

---

rpc_jobs/irr_role_test.yml

The rpc-upgrades jobs take longer than three hours. This change
adds two hours to the gate job so that it has enough time to
complete.

Add more time to the IRR jobs

---

rpc_jobs/standard_job_premerge.yml

In https://github.com/rcbops/rpc-gating/pull/492, we made the
environment variable RE_JOB_REPO_NAME accessible to jobs using the
post merge template.  This commit makes this variable accessible to
jobs using the pre merge template also.
Issue: [RE-784](https://rpc-openstack.atlassian.net/browse/RE-784)

RE-784 Add RE_JOB_REPO_NAME to pre merge template

---

rpc_jobs/rpc_aio.yml

PRs [1] [2] [3] [4] have been created to move rpc-openstack periodic
deploy testing in-repo, meaning we can exclude these jobs in
rpc_aio.yml once the associated PRs have merged.
[1] https://github.com/rcbops/rpc-openstack/pull/2612
[2] https://github.com/rcbops/rpc-openstack/pull/2613
[3] https://github.com/rcbops/rpc-openstack/pull/2614
[4] https://github.com/rcbops/rpc-openstack/pull/2615
Issue: [RE-784](https://rpc-openstack.atlassian.net/browse/RE-784)

RE-784 Disable remaining periodic deploy jobs

---

rpc_jobs/hardening.yml
rpc_jobs/multi_node_aio.yml

All mnaio jobs are currently failing since rpco no longer uses
submodules and mnaio rpc-gating code assumes we're checking out a
submodule.
This commit updates the hardening job to use newton branch instead, and
comments out the master jobs in multi_node_aio.yml until we're able to
deploy mnaios with and without submodules.
Issue: [RE-808](https://rpc-openstack.atlassian.net/browse/RE-808)

RE-808 Update master mnaio jobs

---

rpc_jobs/params.yml

Since PR https://github.com/rcbops/rpc-gating/pull/465 set the default
VM kernel from linux-image-4.4.0-66-generic to linux-image-generic,
we've been having increased build failures on Trusty deploys.
This PR simply reverts that commit to verify that using
linux-image-4.4.0-66-generic is required.
This reverts commit bfc7bcd3cbd81622afe9231ccade08da0dcd9260.
Issue: [RLM-228](https://rpc-openstack.atlassian.net/browse/RLM-228)

RLM-228 Revert commit bfc7bcd

---

playbooks/allocate_pubcloud.yml

Commas in the fallback region string are replaced with spaces, but then
the string is split on commas to form a list. Consequently the string
is not split and a single item list is produced. This list is not a
valid region, so attempts to use the fallback region fail.
This commit changes the allocate_pubcloud playbook to split the
fallback region list on spaces rather than commas to avoid the above
problem.
Issue: [RE-1019](https://rpc-openstack.atlassian.net/browse/RE-1019)

RE-1019 Fix fallback region split

---

rpc_jobs/standard_job_premerge_release.yml

This job template seems problematic in that jobs are currently failing
with:
```
+ python rpc-gating/scripts/release.py
Usage: release.py [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...
Options:
--org TEXT            Github Organisation that owns the target repo
[required]
--repo TEXT           Name of target repo  [required]
--pat TEXT            Github Personal Access Token  [required]
--debug / --no-debug
--help                Show this message and exit.
Commands:
add_issue_url_to_pr
clone
create_issue
create_pr
create_release
generate_release_notes
mail                    Send mail via local MTA
mailgun                 Send mail via mailgun api.
publish_tag
update_rc_branch        Update rc branch.
usage
+ --debug
```
While the `COMMAND` parameter YAML looks correct (>- to unfold …

RE-617 Update standard_job_premerge_release.yml

---

rpc_jobs/jjb_setup.yml

Currently the JJB job has two boolean params:
* ignore cache
* delete old
Enabling both of these is dangerous, as the cache may contain jobs
from a testing branch, which may not include current production jobs.
To avoid this situation, both params are removed. Ignore cache will
always be enabled, delete old will only be enabled when using
the master branch.
Issue: [RE-581](https://rpc-openstack.atlassian.net/browse/RE-581)

RE-581 JJB Job deletion fix

---

pipeline_steps/pubcloud.groovy
playbooks/instance_prep.yml

Ansible bombs without this in place on the OnMetal Xenial image as python 2.x isn't installed by default.  This leverages cloud-init to install the package.  Could also load this via the first ansible playbook as the first option we run using the raw module but this seems a bit cleaner.
python-yaml is installed at this time too since mnaio_inventory_generate.py fires early.
I could also maybe drop the apt-get update, but wasn't sure if a cache exists or not on these images.
Issue: [RLM-275](https://rpc-openstack.atlassian.net/browse/RLM-275)

RLM-275 Install python-minimal on xenial hosts for ansible

---

rpc_jobs/params.yml
rpc_jobs/phobos.yml

This job will be used to deploy RPC Openstack into the phobos
environment. It includes slack warnings for pending deploys and
Jira issue creation on failure.
Depends on:
Notes:
- ⚠️  Please review the deploy portion of this job in detail, as **it has not been tested**. This is because I wanted to have the code reviewed before running it against a production cluster.
- ✅  The verify portion of this job is currently [running every 20 minutes](https://rpc.jenkins.cit.rackspace.net/blue/organizations/jenkins/Phobos-Deploy/activity), and so far all runs of the latest version have succeeded. 
Issue: [RE-645](https://rpc-openstack.atlassian.net/browse/RE-645)

RE-645 Add phobos deployment job

---

playbooks/phobos_tunnel.yml
scripts/ghutils.py

RE now has access to the rpc.rackspace.com DNS domain, we therefore
do not need to use personal domains such as wherenow.org for anything.
This commit removes a reference to wherenow.org. The new domain
points to the same IP, so re-deploys will work as the do currently.
This PR also introduces get_webhooks to ghutils. 
Get_webhooks lists webhook config for repos, or can list all
webhooks whose url matches a regex. Useful for finding
webhooks that need to be updated when a service relocates.
Issue: [RE-809](https://rpc-openstack.atlassian.net/browse/RE-809)

RE-809 Remove references to wherenow.org

---

pipeline_steps/maas.groovy
rpc_jobs/params.yml
scripts/mnaio_inventory_generate.py

This is necessary to work around failures we're hitting as a result of
ansible 2.4.1.0 being installed.
Note that in addition to bumping the SHA, we also need to introduce a
new host var, `server_domain_name`.
Lastly, because openstack-ansible-ops now reverts to using ansible
2.3.2.0, we have to revert some of the python ansible code in
pipeline_steps/maas.groovy.  However, instead of reverting wholesale we
update it to work with both ansible < 2.4 and >= 2.4.
Issue: [RE-1046](https://rpc-openstack.atlassian.net/browse/RE-1046)

RE-1046 Bump openstack-ansible-ops

---

rpc_jobs/periodic_cleanup.yml
scripts/jenkins_node.py
scripts/periodic_cleanup.py

Previously instance_prefix was used to match instances that should
be cleaned up. The idea was that all jobs used a common prefix
(like rpc-aio) and we could use that prefix to identify temporary
nodes that had leaked.
However there are now too many jobs to accurately maintain the
prefix regex. It also failed to account for test jobs that could
create instances that didn't match the prefix.
This commit inverts the logic, removes instance_prefix and replaces
it with protected_prefix. All instances that don't match the
protected_prefix regex, will be subject to cleanup.
Issue: [RE-1020](https://rpc-openstack.atlassian.net/browse/RE-1020)

RE-1020 Introduce protected_prefix

---

rpc_jobs/rpc_artifact_build.yml

Nested parallelism causes unexpected behaviour and may cause
errors to go unreported. To work around this, the one usage of
nested parallelism is removed by flattening all the branches and
sub branches into a single parallel dictionary.
Issue: [RE-1102](https://rpc-openstack.atlassian.net/browse/RE-1102)

RE-1102 Remove nested parallelism from groovy

---

rpc_jobs/rpc_openstack.yml

These should have been added as part of RE-784 as we moved periodics
out of rpc_jobs/rpc_aio.yml and into rpc_jobs/rpc_openstack.yml.
Issue: [RE-1103](https://rpc-openstack.atlassian.net/browse/RE-1103)

RE-1103 Re-add missing RPCO periodics

---

pipeline_steps/multi_node_aio_prepare.groovy
pipeline_steps/pubcloud.groovy

Currently, we're using `include` when we stash instead of `includes`,
and this is including far too many files.
This commit simply corrects each stash to refer to `includes` instead.
Note that in multi_node_aio_prepare.groovy, we also update the stash to
point to the specific inventory file relative to the working directory,
rather than referring to `inventory_path`, which didn't seem to work.
Issue: [RE-652](https://rpc-openstack.atlassian.net/browse/RE-652)

RE-652 Correct stashing

---

rpc_jobs/standard_job_postmerge.yml

Currently, the PM template is using the `git` pipeline step but this
isn't initialising submodules, which is necessary by rpc-openstack.
This commit switches to the helper `clone_with_pr_refs` instead.
Issue: [RE-1103](https://rpc-openstack.atlassian.net/browse/RE-1103)

RE-1103 Update PM to use clone_with_pr_refs

---

rpc_jobs/phobos.yml

This is so the storage team who are a current user of phobos
are aware of potential disruption.
Issue: [RE-1111](https://rpc-openstack.atlassian.net/browse/RE-1111)

RE-1111 Notify #ceph and #rpc-engineering of phobos deploys

---

rpc_jobs/jjb_setup.yml

JJB can be restricted to building a subset of jobs, this option
must not be used with --delete-old, as then jobs not in that
subset will be deleted.
This commit ensures --delete-old is not enabled when building
a subset of jjb jobs.
Issue: [RE-1120](https://rpc-openstack.atlassian.net/browse/RE-1120)

RE-1120 Unset delete old when building subset

---

rpc_jobs/standard_job_postmerge.yml

Currently, builds that fail in the `Execute Run Script` stage do not
fail the build.  This commit sets the build to `FAILURE` in the catch
and re-throws the exception.  This is a similar pattern that exists in
standard_job_premerge.yml.
Issue: [RE-1116](https://rpc-openstack.atlassian.net/browse/RE-1116)

RE-1116 Correctly fail build when failure occurs

---

scripts/periodic_cleanup.py

Generators can only be iterated once, and in one case, we
were doing two membership tests on one generator, causing incorrect
results for the second test.
This commit removes all generator usage, even when it wouldn't
cause a problem, as the data set is small enough that we don't need
the optimisation. This may also prevent bugs being introduced in future.
Issue: [RE-1114](https://rpc-openstack.atlassian.net/browse/RE-1114)

RE-1114 Remove generator usage from cleanup script

---

pipeline_steps/pubcloud.groovy

This commit updates pubcloud.groovy to use the correct inventory passed
in through args.  Currently, we assume an inventory `inventory` which
is incorrect.
Issue: [RE-1121](https://rpc-openstack.atlassian.net/browse/RE-1121)

RE-1121 Use correct inventory

---

playbooks/allocate_pubcloud.yml

The when clause in the 'Provision a cloud instance' task was not updated
in the migration from rax module to os_server, and this is resulting in
an instance being created in all regions, rather than just the first.
This commit updates the when clause to work with os_server.
Co-Authored-By: git-harry <git-harry@live.co.uk>
Issue: [RE-1126](https://rpc-openstack.atlassian.net/browse/RE-1126)

RE-1126 Update when in server provisioning task

---

rpc_jobs/standard_job_postmerge.yml

Currently the post merge standard job is triggered by cron/timer only.
This commit adds a freestyle job which is triggered by pushes to github
which in turn triggers the post merge standard job.
The reason for this is that github push trigger is not reliable with
pipeline jobs (unless using orgfolder/multibranch pipeline which we
aren't).
Each project that wants to use a push trigger, will create a JJB
project to instantiate the job for their repo. Re-For-Projects
will be updated with instructions.
⚠️  Please also review the [documentation](https://rpc-openstack.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=19005457&selectedPageVersions=49&selectedPageVersions=47) when reviewing this PR.
Issue: [RE-678](https://rpc-openstack.atlassian.net/browse/RE-678)

RE-678 Add merge trigger job for post merge job

---

playbooks/allocate_pubcloud.yml

With the switch from ansible rax module to os_server, we now need to
explicitly enable config-drive in order for our user-data scripts to
run.  This commit simply flips it on in the `Provision a cloud
instance` task.
Issue: [RE-1134](https://rpc-openstack.atlassian.net/browse/RE-1134)

RE-1134 Enable config-drive for user-data

---

lint.sh

We've run into situations where long job names cause python scripts in
virtualenvs to fail.  This is due to a kernel limitation that imposes
the max number of characters that can exist in an interpreter line in a
script.
This commit adds a new check that scans all job name lengths and then
errors if any exceeds 77 chars.
Issue: [RE-53](https://rpc-openstack.atlassian.net/browse/RE-53)

RE-53 Add lint check to validate job name length

---

rpc_jobs/rpc_aio.yml

At present, we only test a major upgrade from liberty -> mitaka and
according to @claco this is not an upgrade that support would do going
forward.  As such, this commit removes all reference to majorupgrade in
rpc_aio.yml.
Issue: [RE-912](https://rpc-openstack.atlassian.net/browse/RE-912)

RE-912 Remove majorupgrade from matrix

---

rpc_jobs/rpc_upgrades.yml

Taking a first shot at making the new style RE jobs:
Adds AIO jobs for testing rpc-upgrades on PR and Post Merge (periodic):
- Tests AIO leaps to newton head from kilo/liberty/liberty releases
- Tests AIO leaps to newton release from kilo/liberty/liberty releases
Adds MNAIO jobs for testing rpc-upgrades on Post Merge (periodic):
- Tests MNAIO leaps to newton head from kilo head /liberty head/liberty releases
- Tests MNAIO leaps to newton release from kilo head/liberty head/liberty releases
Actions are set as the "UPGRADE_FROM_REF" and series is utilized as the destination leap version.  Open to suggestions and improvements on how to shim this into the existing layout as it's a bit different.  Most of the actions are commented out for now except for liberty while implementing the jobs in …

RLM-290 Adds new RE style jobs for rpc-upgrades

---

rpc_jobs/rpc_upgrades.yml

Currently we're inherting from defaults.yml, which only has a single
region in REGIONs.  This means builds will fail when that region is
full (which it is now).
Note that the onmetal flavour we're using is only available in IAD,
so we override REGIONS w/ just that region for mnaio builds.
Issue: [RE-1136](https://rpc-openstack.atlassian.net/browse/RE-1136)

RE-1136 Override REGIONS in rpc_upgardes.yml

---

playbooks/allocate_pubcloud.yml

The task "Provision a cloud instance" fails without trying the next
region under certain types of build failure, for example if the
requested image does not exist in the current region.
This change updates the when clause so that the next region will be
tried if no 'server' key is present in the result object.
Issue: [RE-1139](https://rpc-openstack.atlassian.net/browse/RE-1139)

RE-1139 Fix retry instance creation

---

rpc_jobs/standard_job_premerge.yml

Leap PM jobs seem to run around 4 hours so the PR
jobs should be similar.  Adding an extra hour for
buffer.
Issue: [RLM-352](https://rpc-openstack.atlassian.net/browse/RLM-352)

RLM-352 Bump timeout to 6 hours

---

rpc_jobs/defaults.yml
rpc_jobs/influx.yml
rpc_jobs/irr_role_test.yml
rpc_jobs/long_running_slave.yml
rpc_jobs/rpc_openstack.yml
rpc_jobs/rpc_upgrades.yml
rpc_jobs/single_use_slave_template.yml

This commit sets some sane defaults for REGIONS/FALLBACK_REGIONS in
defaults.yml and then removes and updates cruft in a number of other
JJB files.  Generally speaking, we want to use DFW and ORD for most
AIO builds, and IAD exclusively for MNAIO builds (so we can leverage
the onmetal v1 capacity).  From a latency/cost perspective, HKG and
SYD have been de-listed entirely.
Issue: [RE-1136](https://rpc-openstack.atlassian.net/browse/RE-1136)

RE-1136 Cleanup REGIONS/FALLBACK_REGIONS params

---

constraints.txt
requirements.txt

python-openstacksdk is required by the periodic clean-up job. It was
being installed as a dependency of python-ironicclient which is itself a
dependency of shade. python-ironicclient has now removed this dependency
causing jobs to fail. python-openstacksdk should be an explicit
requirement of this project and this commit makes that so.
Issue: [RE-1142](https://rpc-openstack.atlassian.net/browse/RE-1142)

RE-1142 Add python-openstacksdk to requirements

---

pipeline_steps/aio_prepare.groovy
pipeline_steps/deploy.groovy
rpc_jobs/rpc_aio.yml
rpc_jobs/rpc_upgrades.yml

This commit adds an additional minor upgrade job to rpc_upgrades so that
newton minor upgrades are tested on both trusty and xenial.
The rpc_aio code for testing minor upgrades is removed given this
testing is now the responsibility of rpc_upgrades.
Issue: [RE-913](https://rpc-openstack.atlassian.net/browse/RE-913)

RE-913 Add xenial minor upgrade to rpc_upgrades

---

rpc_jobs/rpc_upgrades.yml

Xenial should only be used as the base image for Newton deployments and
onwards. This change fixes the exclude to properly prevent pre-Newton
jobs using Xenial.
Issue: [RE-913](https://rpc-openstack.atlassian.net/browse/RE-913)

RE-913 Fix xenial excludes in rpc_upgrades

---

rpc_jobs/rpc_upgrades.yml

Reduces PR tests to kilo-newton and liberty-newton.
This provides a basic sanity check and then relies
on the PM jobs to surface issues.  Because the jobs
take several hours, it's currently overkill to test
every version on PR.
Also makes image names consistent and switches to
16.04 for mnaio host.
Issue: [RLM-366](https://rpc-openstack.atlassian.net/browse/RLM-366)

RLM-366 Reduces PR tests for rpc-upgrades

---

rpc_jobs/standard_job_postmerge.yml

This will prevent jira issues from being created when a build is
aborted.
Issue: [RO-3115](https://rpc-openstack.atlassian.net/browse/RO-3115)

RO-3115 Don't create issues for aborted builds

---

pipeline_steps/common.groovy
rpc_jobs/build_gating_venv.yml
rpc_jobs/standard_job_premerge.yml

This will lift the requirement that all rpc-gating PRs are from
rpc-gating, it will also ensure that we test merged heads, not the
head of the PR.
Issue: [RE-1177](https://rpc-openstack.atlassian.net/browse/RE-1177)

RE-1177 Allow library loading from PR merge refs

---

rpc_jobs/rpc_openstack.yml

This project defines additional jobs to replace functionality being
provided by Travis CI in rpc-openstack.
Issue: [RE-1163](https://rpc-openstack.atlassian.net/browse/RE-1163)

RE-1163 Add rpc-openstack newton tox jobs

---

pipeline_steps/common.groovy
rpc_jobs/defaults.yml
rpc_jobs/rpc_openstack.yml
rpc_jobs/standard_job_premerge.yml
rpc_jobs/unit/re_unit_tests.yml
rpc_jobs/unit/skip_build_check.yml

This patch introduces the ability in a standard job to define a skip
regex. If all the paths of all the files modified by the pull request
match the regex, the build is ended and marked a success. This allows
builds to be skipped when they aren't impacted by the pull request
changes.
The regex support is provided by Python's re module with the verbose
flag enabled [1], this allow for more readable multi-line regex to be
written without the whitespace impacted the expression. When defining
`skip_pattern` in YAML use `>-` so that the string does not include new
lines.
This change also adds a regex for rpc-openstack pull requests to fix the
functionality lost when those jobs were moved from using rpc_aio.yml to
standard_job_premerge.yml.
This facility can be applied to the project, or to an …

RE-787 Add PR build skipping for matching files

---

rpc_jobs/rpc_openstack.yml

The ironic test appears to be missing - it's tested
in the PR but not in the PM. This adds the missing
scenario.
Issue: [RO-3158](https://rpc-openstack.atlassian.net/browse/RO-3158)

RO-3158 Add ironic scenario for RPC-O master/pike

---

rpc_jobs/unit/re_unit_tests.yml

This change fixes an error where the unit test job fails due to a
missing comma in the definition of the tests.
Issue: [RE-787](https://rpc-openstack.atlassian.net/browse/RE-787)

RE-787 Fix missing comma in job definition

---

pipeline_steps/common.groovy
rpc_jobs/rpc_openstack.yml
rpc_jobs/standard_job_premerge.yml
rpc_jobs/unit/skip_build_check.yml

This change moves `skip_pattern` to being a parameter. This means that
it is no longer defined in the pipeline script generated from the `dsl`
section of the pre-merge job template. Making this change means that the
string definition in the project no longer needs to escape special
characters.
Making `skip_pattern` a parameter fixes the rpc-openstack pull request
build failures caused by the use of unescaped `"\"` and `"$"` in the
definition of `skip_pattern` for its projects.
The regex is now supplied to the search function using an environment
variable instead of interpolating the string into the script. This
prevents any issues with interpolating a bad string.
The appearance of the regex in the console log is improved by moving it
to a new line.
Switching to use a parameter means that …

RE-1203 Fix use of skip_pattern in job definitions

---

pipeline_steps/common.groovy
pipeline_steps/irr_role_tests.groovy
rpc_jobs/cloud_image_build.yml
rpc_jobs/standard_job_premerge.yml

A number of jobs are throwing an error on this function call, and it
appears the cause is three-fold:
1. A number of jobs are not passing in repo_path, meaning the default
of rpc-openstack is being used, and this is incorrect for a number
of non rpc-openstack-related jobs.
2. Jobs run inside a docker container are not cd'ing into the correct
directory (see JENKINS-33510).
3. safe_jira_comment calls get_jira_issue_key which is trying to do a
git log against an upstream branch, but upstream is not configured
as a remote.
This commit does the following to address:
1. Updates the git-log in get_jira_issue_key (called by
safe_jira_comment) to use origin instead of upstream, and also
prefixes ${ghprbSourceBranch} with origin.
2. Removes the dir() in get_jira_issue_key and cd's into the correct …

RE-1205 safe_jira_comment cleanup

---

lint.sh
playbooks/repo_server.yml
playbooks/setup_openstack_instances.yml
repo_server/instances.yml
repo_server/role_requirements.yml
rpc_jobs/periodic_cleanup.yml
rpc_jobs/repo_server.yml

This commit leverages the work done in [1] to continuously deploy
repo servers for artifact storage.
In order to do this, setup_openstack_instances.yml had to be
modified to provision block storage, which is required for storage of
artifacts.  This primarily involves:
- adjusting the initial unlock to only happen when the instance is
marked for deletion (state=absent), or when there are volumes defined
in instance_list
- adding the necessary tasks to deploy and attach the specified volumes
- adding an inventory refresh to provide an updated inventory for when
we need to query inventory to determine if an instance needs to be
locked
- finally, we check if the instance is in the inventory to determine if
it needs to be locked
To keep things simple for the first iteration, this PR does
not …

RE-1151 Add playbook / jobs to deploy repo servers

---

rpc_jobs/rpc_upgrades.yml

Enables MNAIO leap jobs to Newton, holding off on release until these are more stable.

RLM-727 Enables MNAIO leap jobs to Newton

---

rpc_jobs/standard_job_postmerge.yml

Since these jobs run once a day, it should be fine to retain two weeks
worth of logs for troubleshooting, investigating, etc.
Issue: [RE-1211](https://rpc-openstack.atlassian.net/browse/RE-1211)

RE-1211 Reduce num-to-keep for PM jobs

---

pipeline_steps/common.groovy
pipeline_steps/pubcloud.groovy
playbooks/allocate_pubcloud.yml
playbooks/save_pubcloud.yml
rpc_jobs/cloud_image_build.yml
rpc_jobs/rpc_openstack.yml
rpc_jobs/snapshot.yml
rpc_jobs/standard_job_postmerge.yml
rpc_jobs/standard_job_premerge.yml
scripts/create_cloud_image.py
scripts/jenkins_node.py
scripts/lint_support_groovy/cause.groovy
scripts/lint_support_groovy/causes.groovy
scripts/lint_support_groovy/ghrpbcause.groovy
scripts/lint_support_groovy/pushcause.groovy
scripts/lint_support_groovy/timercause.groovy

Please see individual commit messages, but the aims of this PR are to provide the RE infrastructure for teams to have snapshots created of their builds.
Hooks (see [RE For Projects](https://rpc-openstack.atlassian.net/wiki/spaces/RE/pages/19005457/RE+for+Projects) for more details):
* /gating/thaw/image_name: If this exists on the instance at the end of a job, (and the job uses pubcloud.runonpubcloud) then a snapshot will be created
* /gathing/thaw/run: If this exists when an instance is allocated, it will be executed. This can be used for things that need fixing when hostname/ip/etc have changed.
This PR also changes the RE_JOB_TRIGGER variable to have more granularity, the one usage of this in rpc-octavia is addressed in a PR to that repo. 
Issue: …

RE-35 Snapshot Support

---

pipeline_steps/pubcloud.groovy
playbooks/allocate_pubcloud.yml
playbooks/instance_prep.yml

Previously, instance_prep ran before we did any ansible tasks on a
server.  However, additional tasks were added to allocate_pubcloud that
run before instance_prep is executed, which results in jobs failing
when python does not exist in the base image.
This commit merges instance_prep with allocate_pubcloud.
Issue: [RE-35](https://rpc-openstack.atlassian.net/browse/RE-35)

RE-35 Merge instance_prep into allocate_pubcloud

---

job_dsl/release.groovy

When a PR is made from a fork, we need to ensure we are cloning from
the correct source repo where the PR branch exists
```ghprbAuthorRepoGitUrl``` always contains the source repo (fork) url,
in the format:
```https://github.com/external_org/repo_name.git```
Job showing successful clone of external fork (although the release job failed for other reasons):
https://rpc.jenkins.cit.rackspace.net/job/RE-Release-PR_rpc-openstack-master/211/console
Issue: [RE-1097](https://rpc-openstack.atlassian.net/browse/RE-1097)

[RE-1097] ensure correct source repo is used for PR

---

pipeline_steps/common.groovy

Running against the 6 hour mark for a full MNAIO deploy, leapfrog,
and QC.  Bumping it to 8 should provide breathing room for additional
items.
Issue: [RLM-820](https://rpc-openstack.atlassian.net/browse/RLM-820)

RLM-820 Increase timeout to 8 hours

---

rpc_jobs/standard_job_postmerge.yml

This change sets an empty default for jira_project_key, and updates the
conditional around create_jira_issue dependent on JIRA_PROJECT_KEY
being non-empty.  This subsequently allows users to make projects send
notifications or not depending on whether jira_project_key is set, and
should also prevent any errors from being thrown now due to missing
jira_project_key.
Issue: [RE-1144](https://rpc-openstack.atlassian.net/browse/RE-1144)

RE-1144 Set default for jira_project_key

---

rpc_jobs/phobos.yml

At the end of the RE-1200 deploy, a large spike in rabbitmq messages
was observed that built up over ~40 minutes before quickly clearing.
This caused the verification stage to fail. An immediate reverify
succeeded as the spike had subsided.
To avoid this situation in future, we extend maas retries to 15 minutes,
and retry the whole verification phase 3 times. This will allow for the
duration of a similar spike, and time for the alarm status to change in
MaaS.
Issue: [RE-1200](https://rpc-openstack.atlassian.net/browse/RE-1200)

RE-1200 override MaaS Verify retries

---

rpc_jobs/rpc_openstack.yml

The 'loose' mode of using artifacts has been introduced
to help with initial deployments where the packages on
the hosts may be newer than those in the apt artifacts
repo. This patch adds two more tests which facilitate
verifying that this mode works on a day to day basis.
The existing tests are not changed so that the jobs
retain their history and so that the merge trigger
jobs also do not need to change.
The PR to implement the changes being tested by this
job are in https://github.com/rcbops/rpc-openstack/pull/2739
Issue: [RLM-316](https://rpc-openstack.atlassian.net/browse/RLM-316)

RLM-316 Add PM deploy tests for artifact 'loose' mode

---

rpc_jobs/periodic_cleanup.yml

The periodic cleanup job is failing because it's attempting to delete
an instance called `webhook-proxy`, which is locked and cannot be
deleted.
We already have an instance called `WEBHOOK-PROXY` and a periodic
cleanup exclusion for this, so this commit simply adds an exclusion for
`webhook-proxy` also.
Issue: [RE-1225](https://rpc-openstack.atlassian.net/browse/RE-1225)

RE-1225 Exclude webhook-proxy from cleanup

---

rpc_jobs/rpc_openstack.yml

The RPC artifacting solution is not always going to be useful in all
customer environments. This change adds a job action which will instruct
the RPC-O gate to test without artifacts for the newton.* and master
branches.
Issue: [RLM-917](https://rpc-openstack.atlassian.net/browse/RLM-917)

[RLM-917] Add job to deploy without artifacts

---

pipeline_steps/aio_prepare.groovy
pipeline_steps/artifact_build.groovy
pipeline_steps/common.groovy
pipeline_steps/deploy.groovy
pipeline_steps/irr_role_tests.groovy
rpc_jobs/standard_job_postmerge.yml
rpc_jobs/standard_job_premerge.yml

This plugin uses Jenkins console notes to store color information,
this is hugely inefficient as it involves storing an encoded java
object in every line.
An alternative colourisation approach is to colourise on the client side
using javascript. This has already been implemented, so we can now
remove the server side implementation.
Issue: [RE-1191](https://rpc-openstack.atlassian.net/browse/RE-1191)

RE-1191 Remove usages of the ansicolor plugin

---

scripts/ansible_v2_3_2_0_1_contrib_inventory_openstack.py

The openstack.py bundled w/ ansible 2.3.2.0 does not set a hostvar for
ansible_host, and ansible 2.0 deprecated ansible_ssh_host in favour of
ansible_host.  Using the current inventory script causes problems with
stable/pike's version of repo_server since it uses ansible_host and not
ansible_ssh_host.
Issue: [RE-1228](https://rpc-openstack.atlassian.net/browse/RE-1228)

RE-1228 Patch openstack inventory script

---

rpc_jobs/rpc_openstack.yml

In order to improve consistency in job naming and cater
for artifacts being disabled, enabled in 'loose' mode [1][2]
and enabled in 'strict' mode, the configuration has been
updated to use the 'image' part of the job name instead
of mixing up the use of the 'action' and 'image' sections.
The reason to make use of the 'image' section is to allow
the testing of both Xenial and Trusty deployments in these
configurations.
The PR tests for deployment without artifacts have been
removed in order to reduce the PR tests to a minimal
functional set which is least likely to fail. The
variations are all tested in the PM jobs, so it's not
neceesary for the PR coverage too.
The regex for the branch matching for master PR tests is
also updated to cater for all branches prefixed with the
word 'master', …

RLM-316 Normalise job config for RPC-O artifact options

---

rpc_jobs/rpc_openstack.yml

The ironic tests are currently failing across the board
and until the issues are resolved they are just wasting
resources. Trusty is not intended to be a supported
platform for ironic deployments in RPC-O.
This patch removes all the trusty/ironic PM jobs.
Issue: [RE-1269](https://rpc-openstack.atlassian.net/browse/RE-1269)

RE-1269 Remove trusty/ironic PM tests

---

rpc_jobs/rpc_ceph.yml

This commit adds a periodic job for rpc-ceph.  A subsequent patch will
need to be committed to add the PR test and then to subsequently remove
rpc-ceph from irr_role_test.yml.
Issue: [RE-1275](https://rpc-openstack.atlassian.net/browse/RE-1275)

RE-1275 First pass at standardising rpc-ceph

---

rpc_jobs/rpc_ceph.yml

This commit updates rpc_jobs/rpc_ceph.yml by adding a pre-merge test.
Additionally, it updates the postmerge project by removing some
references to rpc-octavia.
Once we are sure this premerge test works we can remove rpc-ceph from
rpc_jobs/irr_role_test.yml.
Issue: [RE-1275](https://rpc-openstack.atlassian.net/browse/RE-1275)

RE-1275 Add rpc-ceph premerge standard jobs

---

rpc_jobs/irr_role_test.yml

This commit removes the legacy rpc-ceph IRR job.
Please do not merge until after [1] merges.
[1] https://github.com/rcbops/rpc-gating/pull/598
Issue: [RE-1275](https://rpc-openstack.atlassian.net/browse/RE-1275)

RE-1275 Remove rpc-ceph IRR job

---

rpc_jobs/rpc_openstack.yml

In order to facilitate ongoing testing during the soak period
this patch adds periodic MNAIO jobs for the {master,newton}-rc
branches.
The trusty_no_artifacts axis exclusion is removed from the
newton AIO PM job as that axis no longer exists.
Issue: [RLM-1159](https://rpc-openstack.atlassian.net/browse/RLM-1159)

RLM-1159 Add MNAIO PM jobs for {master,newton}-rc branches

---

rpc_jobs/rpc_artifact_build.yml

Currently the master-rc branch is ignored, but it should not be.
Issue: [RE-1285](https://rpc-openstack.atlassian.net/browse/RE-1285)

RE-1285 Ensure RPC-O artifact build tests fire for master-rc

---

rpc_jobs/rpc_role_logstash.yml

This commit creates a new file for rpc-role-logstash and uses the
standard pre and post gating templates.
A separate commit will be created to remote this role from
irr_role_test.yml.
Issue: [RE-1277](https://rpc-openstack.atlassian.net/browse/RE-1277)

RE-1277 Move logstash role to standard template

---

pipeline_steps/common.groovy
playbooks/phobos_vpn.yml
playbooks/templates/vpnc.conf.j2
playbooks/templates/vpnc.service.j2
rpc_jobs/unit/phobos_vpn.yml
rpc_jobs/unit/re_unit_tests.yml

The current method of connecting to phobos requires a webhook proxy
node and a deploy node. This multi hop approach can make it hard to
access some networks within phobos.
This commit adds a vpn connection direclty from a single use test node
to phobos.
Issue: [RE-1288](https://rpc-openstack.atlassian.net/browse/RE-1288)

RE-1288 Add phobos vpn connection

---

rpc_jobs/rpc_role_logstash.yml

This PR adds jobs which will replace rpc-role-logstash's Travis CI
usage.
Issue: [RE-1166](https://rpc-openstack.atlassian.net/browse/RE-1166)

RE-1166 Add lint jobs for rpc-role-logstash

---

rpc_jobs/rpc_maas.yml

These new jobs are designed to replace the IRR jobs for rpc-maas. Once
these jobs have been added the equivalent IRR jobs will be removed in a
separate commit.
Issue: [RE-1276](https://rpc-openstack.atlassian.net/browse/RE-1276)

RE-1276 Add rpc-maas projects using standard jobs

---

rpc_jobs/rpc_upgrades.yml

This PR adds jobs which will replace rpc-upgrades' Travis CI usage.
Issue: [RE-1162](https://rpc-openstack.atlassian.net/browse/RE-1162)

RE-1162 Add lint jobs for rpc-upgrades

---

rpc_jobs/rpc_maas.yml

rpc-maas jobs require cloud_creds to test the MaaS API, without this set
the tests pass because rpc-maas does not require those tests to be run.
Issue: [RE-1276](https://rpc-openstack.atlassian.net/browse/RE-1276)

RE-1276 Supply cloud_creds to rpc-maas jobs

---

.gitignore
job_dsl/dep_update.groovy
lint.sh
pipeline_steps/common.groovy
pipeline_steps/pubcloud.groovy
rpc_jobs/jjb_setup.yml
rpc_jobs/periodic_cleanup.yml
rpc_jobs/phobos.yml
rpc_jobs/standard_job_postmerge.yml
rpc_jobs/unit/jira.yml
rpc_jobs/unit/re_unit_tests.yml
scripts/dep_update.sh
scripts/jirautils.py

This PR will help reduce issue spam, by updating an existing issue if one exists instead of creating duplicate issues. It also adds a tool for closing all existing issues related to a particular build except the oldest one. 
Issue: [RE-1138](https://rpc-openstack.atlassian.net/browse/RE-1138)

RE-1138 Update existing issue on build failure

---

rpc_jobs/rpc_upgrades.yml

Adds all deployed Kilo versions to validate that they work
with rpc-upgrades.  This will enable us to fully use
rpc-upgrades for leaps and move away from the 14.2.0 newton
dependency.
Also bumps the minor job to the latest release.
Issue: [RLM-1290](https://rpc-openstack.atlassian.net/browse/RLM-1290)

RLM-1290 Add Kilo version specific jobs to newton release

---

rpc_jobs/rpc_upgrades.yml

Adds Mitaka to Newton Major job so we can get
an idea of it's current status and get it working in
rpc-upgrades.
Issue: [RLM-1291](https://rpc-openstack.atlassian.net/browse/RLM-1291)

RLM-1291 Adds Mitaka to Newton Major job

---

rpc_jobs/rpc_openstack.yml

Given that the MNAIO tooling currently deploys the latest packages
for the base OS, the strict mode test will fail on the RC branches
as soon as a newer apt package than the artifacted packages releases.
Therefore, until a mechanism is worked out to deploy the base OS
using artifacts, the strict mode tests are just going to deliver
failures for a well known reason. As such, they should be removed
for now.
Issue: [RE-1300](https://rpc-openstack.atlassian.net/browse/RE-1300)

RE-1300 Remove strict mode RPC-O MNAIO jobs for the RC branches

---

rpc_jobs/phobos.yml

A new room was recently spun up and we have been asked to send these
phobos deploy notifications to #rpc-ceph instead.
Issue: [RE-1301](https://rpc-openstack.atlassian.net/browse/RE-1301)

RE-1301 Send phobos msgs to #rpc-ceph

---

rpc_jobs/rpc_openstack.yml

The default PR test needs to be non-artifacted. This change updates the
PR image properties so that non-artifacted jobs can run as the default.
Issue: [RO-3870](https://rpc-openstack.atlassian.net/browse/RO-3870)

[RO-3870] Change the PR job to non-artifacted

---

rpc_jobs/phobos.yml

We are currently deploying newton-rc to phobos regularly, to prevent
mistkes, make this the default branch.
Issue: [RE-1287](https://rpc-openstack.atlassian.net/browse/RE-1287)

RE-1287 Set default Phobos deploy branch to newton-rc and add time trigger

---

rpc_jobs/rpc_openstack.yml

It is not used anymore.  Stop testing it so the code itself can be
removed.

remove the  release-script job

---

rpc_jobs/rpc_maas.yml

This change adds the jobs necessary to stop using Travis CI with
rpc-maas and is part of the work to move all projects to using the
standard jobs.
Issue: [RE-1164](https://rpc-openstack.atlassian.net/browse/RE-1164)

RE-1164 Add rpc-maas jobs to replace Travis CI

---

rpc_jobs/rpc_openstack.yml

1. As the MNAIO test jobs currently do not execute any
form of functional testing (eg: tempest), the AIO
test execution is added to the master-rc branch.
2. As the Ironic MNAIO test jobs appear to have stabilised
for the master branch, they're added to the master-rc
branch too.
3. As the MNAIO tests always deploy the latest base OS
packages, a strict mode deployment cannot work. As such
the strict mode MNAIO test execution for the newton
branch is removed.
Issue: [RO-3868](https://rpc-openstack.atlassian.net/browse/RO-3868)

RO-3868 Update RPC-O test matrix

---

pipeline_steps/common.groovy
rpc_jobs/standard_job_postmerge.yml

If a post-merge build is aborted by a user, the failure should not be
recorded in an issue. This change adds a new function to test if the
build was manually aborted, by looking for a specific interrupt action
as described in Jenkins issue JENKINS-28822 [1].
The code replaced in this commit does not work, the exception does not
have a `getCauses` method which results in `user` always being set to
`"SYSTEM"`.
[1] https://issues.jenkins-ci.org/browse/JENKINS-28822
Test builds (search for "build failure issue" to see log entry):
Script failure: https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-openstack-master-xenial_loose_artifacts-swift-deploy-gh-testing/10/consoleFull
User aborted: https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-openstack-master-xenial_loose_artifacts-swift-deploy-gh-testi …

RE-1210 Fix skipping aborted-build issue creation

---

rpc_jobs/unit/re_unit_tests.yml
rpc_jobs/unit/single_use_slave.yml

RE-1169 requires upgrading the jenkins docker workflow plugin, to ensure
that the container standard slave type is still functioning after
this change and future changes, an additional unit test is added.
Issue: [RE-1169](https://rpc-openstack.atlassian.net/browse/RE-1169)

RE-1169 Add unit test for container slaves

---

playbooks/setup_jenkins_slave.yml

This patch removes the jinja2 brackets from the when argument to
avoid Ansible warnings.
Issue: [RE-1210](https://rpc-openstack.atlassian.net/browse/RE-1210)

Fix warning for jinja2 brackets

---

pipeline_steps/artifact_build.groovy
rpc_jobs/rpc_artifact_build.yml

This stage is no longer required, so we can remove them.
Issue: [RE-1314](https://rpc-openstack.atlassian.net/browse/RE-1314)

RE-1314 Remove RPC-O container artifact build stage

---

pipeline_steps/common.groovy
rpc_jobs/ops_fabric_chatbot.yml

NOTE: The junit change in common.groovy is necessary because at present
no job output is being parsed.  It looks like this pipeline helper only
accepts a relative path, so we cd into the directory and then pass in
'*.xml'.
Issue: [RE-1169](https://rpc-openstack.atlassian.net/browse/RE-1169)

RE-1169 Standardise ops-fabric-chatbot jobs

---

rpc_jobs/rpc_upgrades.yml

Adds Major and Leap jobs for MNAIO and AIO to test
functionality and timing for both methods.
Also excludes Xenial Mitaka jobs since we only support
Trusty.
Issue: [RLM-1405](https://rpc-openstack.atlassian.net/browse/RLM-1405)

RLM-1405 Adds Major/Leap jobs for M2N

---

Dockerfile.standard_job
pipeline_steps/common.groovy
rpc_jobs/defaults.yml
rpc_jobs/params.yml
rpc_jobs/standard_job_postmerge.yml
rpc_jobs/standard_job_premerge.yml
rpc_jobs/unit/re_unit_tests.yml
rpc_jobs/unit/single_use_slave.yml

In most cases, it's irrelevant which base image we use for creating a
container, however an ops-fabric test requires an ubuntu:17.10
container and subsequent tests call python3.6, which is not available
in the standard ubuntu base container image we use for all tests.
This review introduces the following three new parameters:
SLAVE_CONTAINER_DOCKERFILE_REPO
SLAVE_CONTAINER_DOCKERFILE_PATH
SLAVE_CONTAINER_DOCKERFILE_BUILD_ARGS
SLAVE_CONTAINER_DOCKERFILE_REPO allows you to use the Dockerfile inside
rpc-gating (`RE`), or the project in test (`PROJECT`).
SLAVE_CONTAINER_DOCKERFILE_PATH allows you to specify the location and
name of the Dockerfile, relative to the root of rpc-gating or the clone
of the project in test.
SLAVE_CONTAINER_DOCKERFILE_BUILD_ARGS allows you to pass in custom
build …

RE-1169 Make use of Docker more customisable

---

rpc_jobs/standard_job_postmerge.yml

At present push-triggered jobs end up in multiple regions, which is
causing saved images to be spread across three regions.  We want to
force push-triggered jobs to go to DFW specifically so that we only
need to worry about saved images in DFW.
Issue: [RE-36](https://rpc-openstack.atlassian.net/browse/RE-36)

RE-36 Force push-triggered builds into DFW

---

rpc_jobs/rpc_openstack.yml

This commit adds 'system' as a scenario to
`rpc-openstack-master-mnaio-postmerge` project and a filter to ensure
that it only creates a single jobs for
`PM_rpc-openstack-master-xenial_mnaio_no_artifacts-system-deploy`.
This job is will be the proof of concept job for running system level
testing on rpc-openstack. Hooks for taking advantage of the `system`
scenario have not yet been implemented in the `rpc-openstack` repo.
Issue: [ASC-143](https://rpc-openstack.atlassian.net/browse/ASC-143)

(ASC-143) Add mnaio system test job

---

pipeline_steps/common.groovy
rpc_jobs/periodic_cleanup.yml

This commit ensures console logs are zipped when a job terminates.
This will affect all future jobs, current jobs are currentbly being
compressed by a bash loop. This relies on a plugin which has already
been installed.
Issue: [RE-1329](https://rpc-openstack.atlassian.net/browse/RE-1329)

RE-1329 Compress Logs

---

pipeline_steps/common.groovy

Jobs have been mysteriously loosing their parameter definitions, and
my suspicion is that this call is overwriting all the properties set
in JJB rather than appending the log compression property to the list.
This may also be causing jobs to loose their github project affiliation
which could be contributing to problems with triggering.

RE-1345 Remove properties call in global wraps

---

rpc_jobs/periodic_cleanup.yml

These variables are bash variables not groovy variables, so the dollar
signs should escaped.
Issue: [RE-1329](https://rpc-openstack.atlassian.net/browse/RE-1329)

RE-1329 Fix interpolation escape and move console log compression to periodic cleanup

---

rpc_jobs/release.yml

Two improvements to assist with future releases:
* Ensure that create tag happens before release notes are generated so that the new tag can be compared against the previous tag when generating release notes.
Issue: [RE-1310](https://rpc-openstack.atlassian.net/browse/RE-1310)

RE-1310 Release Improvements

---

playbooks/allocate_pubcloud.yml
rpc_jobs/rpc_designate.yml
rpc_jobs/standard_job_postmerge.yml
rpc_jobs/standard_job_premerge.yml

Booting from a saved image is significantly slower than from a base
image, and as such we need to make the timeout configurable.
The default remains 900 seconds, but we can now override this via
BOOT_TIMEOUT.
Additionally, we add some new rpc-designate periodic jobs which use
snapshot images. These jobs are purely for testing and we will look
at adding process and moving all rpc-designate's jobs over to these
images once they are running reliably.
Lastly, we update a comment in the rpc-designate-post-merge project
which was made mention of the pre-merge template and not the
post-merge template.
Issue: [RE-36](https://rpc-openstack.atlassian.net/browse/RE-36)

RE-36 Adjustable boot timeout & new snapshot jobs

---

rpc_jobs/rpc_openstack.yml

Apparently Ironic on Newton is not supported by RPC-O,
so the jobs are being removed.
Issue: [RE-1360](https://rpc-openstack.atlassian.net/browse/RE-1360)

RE-1360 Remove all Newton/Ironic jobs

---

rpc_jobs/rpc_openstack.yml

I'm not sure how we missed this, but the lack of the postmerge
newton-rc job means we're not getting snapshots when anything merges to
newton-rc branch.
Issue: [RE-1356](https://rpc-openstack.atlassian.net/browse/RE-1356)

RE-1356 Add newton-rc postmerge job

---

rpc_jobs/rpc_artifact_build.yml
rpc_jobs/rpc_openstack.yml

RPC-O master will now become Queens, and Pike will be branched.
This caters for the following changes:
1. Adjust the artifact build jobs to only run against Newton
and Pike branches. If any Queens artifact work is done then
the jobs can be adjusted later. Queens will start with no
artifact support.
2. Adjust the RPC-O jobs for master to only run without artifacts.
3. Adjust all current master/master-rc jobs that are Pike orientated
to run against the pike/pike-rc branches.
4. There will be no jobs for a master-rc branch until there is a
Queens RC, so we just rename all the master-rc branch to pike-rc.
Issue: [RE-1359](https://rpc-openstack.atlassian.net/browse/RE-1359)

RE-1359 Adjust gate jobs for Queens/Pike

---

rpc_jobs/dep_update.yml
rpc_jobs/hardening.yml

In https://github.com/rcbops/rpc-gating/pull/663 there were
some additional jobs missing to cater to the new pike/pike-rc
branches. This patch adds them too.
Issue: [RE-1359](https://rpc-openstack.atlassian.net/browse/RE-1359)

RE-1359 Add missing Pike dep_update/hardening jobs

---

rpc_jobs/standard_job_premerge_release.yml

The test to validate that a patch will not break the
release scripts is missing.
Issue: [RE-1359](https://rpc-openstack.atlassian.net/browse/RE-1359)

RE-1359 Add missing RPC-O Pike PR release test

---

pipeline_steps/common.groovy
pipeline_steps/pubcloud.groovy
playbooks/upload_to_swift.yml
rpc_jobs/standard_job_postmerge.yml
rpc_jobs/standard_job_premerge.yml
rpc_jobs/unit/artefact_publish.yml

Currently the job artifact upload assumes the directory
where the artifacts live, rather than making use of the
implemented hook to find out where it is.
This patch make the uploadToSwift function generic,
requiring only a path to find the stuff to upload. The
archive_artifacts function is then changed to make it
take parameters for the paths for the results/artifacts,
but to fall back to a set of default paths if they are
not provided.
The standard jobs are then changed to provide the correct
paths to the function so that the hooks are properly
implemented.
Issue: [RE-1294](https://rpc-openstack.atlassian.net/browse/RE-1294)
Issue: [RE-1328](https://rpc-openstack.atlassian.net/browse/RE-1328)

RE-1328 Fix job artifact upload to use the RE hook

---

nodepool/elements/jenkins-slave/element-deps
nodepool/elements/jenkins-slave/extra-data.d/20-jenkins-user
nodepool/elements/jenkins-slave/install.d/20-jenkins-slave
nodepool/elements/jenkins-slave/package-installs.yaml
nodepool/nodepool-config.yml
playbooks/setup_nodepool.yml
playbooks/setup_openstack_instances.yml
playbooks/vars/nodepool.yml

In order to ensure that every nodepool instance is prepared for
jenkins to use it, some preparation of the instance image is
required. This patch adds an diskimage-builder element to do
the preparation, and to configure nodepool to use it.
Also, to ensure that Trusty nodes are available, the configuration
is added to build Trusty images and prepare Trusty nodes.
Issue: [RE-1130](https://rpc-openstack.atlassian.net/browse/RE-1130)

RE-1130 Add jenkins-slave & Ubuntu Trusty configuration

---

rpc_jobs/pull_request_issue_link.yml

Currently, if a change is made to rpc-gating the issue link job uses
the default RPC_GATING_BRACH (master). This is generally fine except
it will not detect issues being introduced to the pipeline scripts
until after they have merged.
This commit simply updates pull_request_issue_link.yml to set
RPC_GATING_BRANCH to `origin/pr/${{env.ghprbPullId}}/merge` when
the repo in question is `rpc-gating`. Additionally, we remove the
REPO parameter since we can just reference `{repo}` instead.
Issue: [RE-1373](https://rpc-openstack.atlassian.net/browse/RE-1373)

RE-1373 Issue link job should execute from PR

---

nodepool/role_requirements.yml
playbooks/vars/nodepool.yml

This patch updates the nodepool implementation to the current
versions/SHA's available.
1. 'nodepool_git_dest' and 'diskimage_builder_git_dest' from
the respective ansible roles now use the value we had as
a default, so the overrides in our vars are no longer
necessary.
2. All role and service versions have been updated.
This implementation has been verified to work, including
upgrading it in a like test environment.
Issue: [RE-1362](https://rpc-openstack.atlassian.net/browse/RE-1362)

RE-1362 Update nodepool implementation

---

rpc_jobs/rpc_upgrades.yml

mitaka_to_newton will utilize major upgrade.
Issue: [RLM-1449](https://rpc-openstack.atlassian.net/browse/RLM-1449)

RLM-1449 Remove mitaka_to_newton_leap jobs

---

pipeline_steps/common.groovy
rpc_jobs/rpc_openstack.yml

This commit creates a new creds bundle called rpc_asc_creds, which
contains credential RPC_ASC_QTEST_API_TOKEN.  This is needed by
PR/PM master/pike/newton rpc-openstack jobs in order for test results
to get uploaded to qTest.
Issue: [RE-1376](https://rpc-openstack.atlassian.net/browse/RE-1376)

RE-1376 Add rpc_asc_creds to creds_bundles

---

rpc_jobs/periodic_cleanup.yml

The artifact builder is a long-lived node, so it should never
be cleaned up.
Issue: [RE-1397](https://rpc-openstack.atlassian.net/browse/RE-1397)

RE-1397 Add ArtifactBuilder to protected prefix to avoid clean up

---

rpc_jobs/unit/single_use_slave.yml

The current check does not understand the nodepool slave
type. This updates the check to cater for the new type.
Issue: [RE-1414](https://rpc-openstack.atlassian.net/browse/RE-1414)

RE-1414 Update check to cater for nodepool slave type

---

nodepool/elements/jenkins-slave/package-installs.yaml

Without this package, the rpc-gating venv tarball cannot
be extracted.
We also sort the packages installed alphabetically to make
them easier to find.
Issue: [RE-1412](https://rpc-openstack.atlassian.net/browse/RE-1412)

RE-1412 Add bzip package install to nodepool elements

---

playbooks/setup_nodepool.yml

To make sure that new elements that merge are used as soon as
possible, we trigger a new diskimage build whenever they change.
Issue: [RE-1413](https://rpc-openstack.atlassian.net/browse/RE-1413)

RE-1413 Trigger a new diskimage build when elements change

---

job_dsl/release.groovy
rpc_jobs/standard_job_premerge_release.yml

The current method of PR testing for releases uses
the remote fork for the test, instead of using the
target repo and the PR ref. This results in the test
failing in all kinds of exciting ways when the remote
fork does not contain the correct refs for the tooling
to be able do what it's supposed to do.
This patch ensures that the parameters passed to the
tooling are more appropriate and will ensure that all
the correct refs are there.
Issue: [RE-1190](https://rpc-openstack.atlassian.net/browse/RE-1190)

RE-1190 Use correct repo/ref for release PR tests

---

pipeline_steps/common.groovy
pipeline_steps/github.groovy

The issue link job currently does not work properly when
executing from a fork. While the current mechanism is ok
it can be simplified to use the other existing clone
function which includes refs, and the function to find
the JIRA issues can then use the pr merge ref.
This simplifies the system, negating the need to add more
remotes and ensuring that everything required is in place.
Issue: [RE-1418](https://rpc-openstack.atlassian.net/browse/RE-1418)

RE-1418 Fix issue link job when using remote forks

---

rpc_jobs/rpc_openstack.yml

1. Removes the ironic PM AIO jobs for master, pike, and pike-rc since
we have equivalent PM MNAIO jobs for these. At present we have no
immediate use for ironic snapshot images, so there's no point
leaving the ironic PM AIO jobs around for this.
2. Sets a @monthly CRON value for the PM swift AIO jobs on master, pike
and pike-rc so that these jobs are effectively only run when the
branches are pushed to (again, we have equivalent PM MNAIO jobs for
these).
3. Similar to #2, we do this for the PM xenial_loose_artifacts newton
and newton-rc AIO jobs since we have this combintation running as
PM MNAIO jobs.
Issue: [RI-254](https://rpc-openstack.atlassian.net/browse/RI-254)

RI-254 Remove unnecessary PM jobs and adjust timer

---

nodepool/elements/jenkins-slave/package-installs.yaml
nodepool/elements/jenkins-slave/pre-install.d/20-add-openjdk-ppa-to-trusty

Jenkins requires the JRE 1.8 in order to connect to
the slaves. In this patch we ensure that the PPA is
setup if the image being built is on Ubuntu Trusty
(it has no native/backport package) and we also
ensure that the package installed afterwards is
explicitly set the the right one instead of assuming
the default package gives us JRE 1.8 for xenial.
Issue: [RE-1415](https://rpc-openstack.atlassian.net/browse/RE-1415)

nodepool elements: Explicitly use jre 1.8

---

rpc_jobs/unit/re_unit_tests.yml

Currently the unit test only verifies that Ubuntu
Xenial nodes work. We should also verify that the
Trusty nodes are working.
Issue: [RE-1419](https://rpc-openstack.atlassian.net/browse/RE-1419)

RE-1419 Add nodepool-ubuntu-trusty node unit test

---

rpc_jobs/standard_job_postmerge.yml
rpc_jobs/standard_job_premerge.yml

To increase the usage of nodepool, we transition some low-impact
tests to it.
Given that the 'functional' pre-merge test is duplicated in the
unit tests, we remove that.
Issue: [RE-1420](https://rpc-openstack.atlassian.net/browse/RE-1420)

RE-1420 Transition rpc-gating tests to use nodepool

---

nodepool/elements/jenkins-slave/install.d/20-jenkins-slave

In order to ensure that java applications work properly
we set the environment variable as a default. To ensure
that we use whatever the current location is, we use a
find instead of a static path.
Issue: [RE-1415](https://rpc-openstack.atlassian.net/browse/RE-1415)

RE-1415 Add JAVA_HOME env var to default environment

---

.gitignore
rpc_jobs/build_gating_venv.yml

- Moved archive creation to inside the container to avoid any external "file changed" issues previously discovered
- Increased the number of venvs to keep from 10 to 100
Issue: [RE-1240](https://rpc-openstack.atlassian.net/browse/RE-1240)

RE-1240 Build Gating venv improvements

---

playbooks/setup_jenkins_slave.yml

Since #703 has since merged (and only installs openjdk-8-jre-headless
on both trusty and xenial), this commit has been created to update
setup_jenkins_slave.yml to do the same thing.  This should ensure
that we have consistent nodes irrespective of nodepool or legacy boot
method.
NOTE: We also add a task to set set the default JAVA_HOME to the
installed jdk, otherwise the groovy syntax check fails as groovy looks
for java under /usr/lib/jvm/default-java/bin/java. This doesn't
exist as we no longer install default-jre-headless or run
update-java-alternatives to point the default to
java-1.8.0-openjdk-amd64.
Issue: [RE-1415](https://rpc-openstack.atlassian.net/browse/RE-1415)

RE-1415 Only install openjdk-8-jre-headless

---

rpc_jobs/dummy_pipeline.yml
rpc_jobs/standard_job_dep_update.yml
scripts/dep_update.sh

This change adds support for testing component dependency updates. By
default this feature is not enabled but can be specified in the project
definition with `component_dependencies_update: "true"`. Currently this
feature is still being tested and should not be used outside of that
test work.
This change also allows for the use of update_dependencies/run updates
to be disabled with `third_party_dependencies_update: "false"`.
Issue: [RE-1384](https://rpc-openstack.atlassian.net/browse/RE-1384)

RE-1384 Add component dependency update support

---

gating/common/run_lint.sh
playbooks/setup_jenkins_slave.yml

It turns out that openstack-ansible copies the host's /etc/environment
to each container's /etc/environment, and having JAVA_HOME set in the
logstash container is interfering w/ the installation of logstash.
Rather than setting JAVA_HOME, we simply set export it in
gating/common/run_lint.sh instead so that groovy can find a suitable
java executable.
Issue: [RI-255](https://rpc-openstack.atlassian.net/browse/RI-255)

RI-255 Don't add JAVA_HOME to /etc/environment

---

rpc_jobs/params.yml
rpc_jobs/phobos_vpn_service.yml
rpc_jobs/unit/phobos_vpn.yml

This service adds a job to create a background vpn service that runs
on the Jenkis nodes within the Rackspace firewall.
This is for two purposes:
1. Give the master access to phobos outside the context of a job
so that phobos can be used as a region
2. Give the slave access to phobos, so jobs can use it without
starting their own vpn instance.

RE-1424 Phobos VPN Service

---

rpc_jobs/periodic_cleanup.yml

The script to compress logs in the periodic_cleanup only registers a
failure in the while loop if it happens on the last pass. This change
ensure that any failures are reported by the first build that detects
them and are consistent between builds.
Issue: [RE-1434](https://rpc-openstack.atlassian.net/browse/RE-1434)

RE-1434 Expose failures compressing logs

---

rpc_jobs/dummy_pipeline.yml
rpc_jobs/standard_job_release.yml

This commit adds the standard template for release testing.
Additionally, we add jobs for all dummy pipeline repos
(rpc-metadata, rpc-product-1, rpc-component-1, rpc-component-2) for PR,
PM, and RELEASE (where applicable).

Add RELEASE template and dummy repos

---

scripts/dep_update.sh

This change fixes the label string to reference the correct variable.
Without this change the label was taking the form `some-repo_` when it
should be `some-repo_a-branch`.
Issue: [RE-1355](https://rpc-openstack.atlassian.net/browse/RE-1355)

RE-1355 Fix dep_update JIRA label

---

constraints.txt

The latest version of os-client-config, 1.31.0 is incompatible with the
current version of shade being used. This change pins the package to fix
build failures.
Issue: [RE-1456](https://rpc-openstack.atlassian.net/browse/RE-1456)

RE-1456 Pin os-client-config

---

rpc_jobs/dummy_pipeline.yml
rpc_jobs/standard_job_gate.yml

This commit adds a new job template for triggering component gate
checks.  Similar to the release gate, this is triggered manually via
the addition of a comment (`trigger-component-gate`) to the PR in
question. This should be added after all the initial checks have run and
the PR has been reviewed.  Upon successful completion of the gate jobs,
the PR will automatically merge.
We also modify the GATE_ template to add necessary parameters for
passing through PR details. We also remove the jira_project_key
reference in the stdJob() call to reflect what is currently done in
the pre-merge jobs. Lastly, we set a default for `branch` in the
template incase one doesn't get passed through by the project.
Issue: [RE-1316](https://rpc-openstack.atlassian.net/browse/RE-1316)

RE-1316 RPC Gate Triggers

---

rpc_jobs/dummy_pipeline.yml

This commit:
- Changes any pre-merge job to a lint test
- Moves pre-merge jobs to containers
- Moves remaining jobs using single use slaves to nodepool instances
- Moves any gate lint jobs to functional jobs
- Adds gate jobs for rpc-component-1 and rpc-component-2

RE-1317 Cleanup dummy jobs

---

rpc_jobs/standard_job_release.yml

This commit alters the command supplied to RE-Release so that the
release job will perform the expected actions instead of simply printing
the command that would have been run.

RE-1317 Enable RE-Release in release pipeline

---

rpc_jobs/rpc_openstack.yml

This commit increases the number of branches that have
credentials to publish to qtest.  The desired state is that
all branches that run system tests should be able to publish
test results to qtest.
Issue: [ASC-384](https://rpc-openstack.atlassian.net/browse/ASC-384)

ASC-384 add qtest creds to more branches

---

rpc_jobs/periodic_cleanup.yml
scripts/workspace_cleanup.sh

Master now runs build summary in docker. As docker is being used,
its important that docker cleanup is run regularly. However a bug
in the periodic cleanup job means that cleanup is not running on
master.
This commit ensures that cleanup does indeed run on the master.
Issue: [RE-1452](https://rpc-openstack.atlassian.net/browse/RE-1452)

RE-1452 Ensure master is included in cleanup

---

grafana/grafyaml/dashboard-nodepool.yaml
grafana/setup_grafana.yml
rpc_jobs/setup_grafana.yml

This PR fixes the following:
- The URL in the dashboard is incorrect.
- The credentials are not available to the job to use.
- The grafyaml import job fails if the key is not present.
Issue: [RE-1408](https://rpc-openstack.atlassian.net/browse/RE-1408)

RE-1408 Fix grafyaml import and dashboard URL

---

pipeline_steps/common.groovy

The correct credential ID, variable and name is
RE_GRAFANA_GRAFYAML_API_KEY - the previous patch
missed the 'RE_' prefix.
Issue: [RE-1408](https://rpc-openstack.atlassian.net/browse/RE-1408)

RE-1408 Fix misspelled credential

---

Dockerfile
Dockerfile.standard_job
nodepool/files/elements/jenkins-slave/package-installs.yaml
pipeline_steps/common.groovy
playbooks/setup_jenkins_slave.yml

Currently, if bad XML ends up in the result dir and jenkins parses it
with the junit step, then jenkins will mark the build as UNSTABLE.
To avoid builds failing because of this situation, we first run xmllint
against the XML files and then only run the junit step if no errors
were found.
We also install libxml2-utils (which provides xmllint) in Docker
containers, pubcloud single use slaves, and nodepool instances.
Issue: [RE-1449](https://rpc-openstack.atlassian.net/browse/RE-1449)

RE-1449 Lint XML before running junit step

---

scripts/rax_instance_clean.sh

The temporary jenkins workspace dirs can contain sensitive files, but
don't appear to be cleaned up automatically.
This commit simply removes any tmp dirs from /var/lib/jenkins/workspace
prior to shutting down so that restoring a snapshot won't have any
sensitive files lingering in it.
Issue: [RE-1481](https://rpc-openstack.atlassian.net/browse/RE-1481)

RE-1481 Remove /var/lib/jenkins/workspace/*@tmp

---

nodepool/files/nodepool.yml

1. Switching the ubuntu-xenial and ubuntu-trusty nodes
to have 0 min-ready means that they can be phased
out, instead of being yanked out. This is in case
any existing jobs are still set to use them.
2. The providers/diskimages section refers to the disk
images used, not the node labels. This patch corrects
the configuration.

RE-1463 Correct nodepool config

---

nodepool/files/nodepool.yml
rpc_jobs/dummy_pipeline.yml
rpc_jobs/rpc_ceph.yml
rpc_jobs/rpc_eng_ops.yml
rpc_jobs/rpc_hummingbird.yml
rpc_jobs/rpc_maas.yml
rpc_jobs/rpc_openstack.yml
rpc_jobs/rpc_role_logstash.yml
rpc_jobs/standard_job_postmerge.yml
rpc_jobs/standard_job_premerge.yml
rpc_jobs/unit/re_unit_tests.yml
rpc_jobs/unit/wrappers.yml

Something is not quite right when trying to use the new labels
so we switch to using the old labels for the g1-8 flavor, and
revert the job configuration to use the old mechanism for the
p2-15 jobs until we can work out the issue.
We also adjust the min-ready settings to accommodate this new
strategy.

RE-1463 Revert g1-8 to working label and p2-15 to old config

---

rpc_jobs/rpc_openstack.yml

This commit adds the `system` action to newton and newton-rc green
field matrices. This action is performed in conjunction with the
`xenial_mnaio_no_artifacts` image. The `system` and `deploy` actions
are filtered in order to only create one new job per branch to match
the other branch jobs for the `system` action.
Therefore, only the following jobs are created:
https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-openstack-newton-xenial_mnaio_no_artifacts-swift-system
https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-openstack-newton-rc-xenial_mnaio_no_artifacts-swift-system
Issue: [ASC-475](https://rpc-openstack.atlassian.net/browse/ASC-475)

ASC-475 Add system action to green field newton

---

nodepool/files/nodepool.yml
rpc_jobs/dummy_pipeline.yml
rpc_jobs/rpc_ceph.yml
rpc_jobs/rpc_eng_ops.yml
rpc_jobs/rpc_hummingbird.yml
rpc_jobs/rpc_maas.yml
rpc_jobs/rpc_openstack.yml
rpc_jobs/rpc_role_logstash.yml
rpc_jobs/standard_job_postmerge.yml
rpc_jobs/standard_job_premerge.yml
rpc_jobs/unit/re_unit_tests.yml
rpc_jobs/unit/wrappers.yml

Now that the issue of nodepool rejecting jobs for labels which
end with a number [a] is resolved, we can revert 935af07.
This extends the use of nodepool to more jobs and a broader set
of flavors, allowing us to monitor these for stability before
moving on to the next stage of job migrations.
[a] rpc-openstack.atlassian.net/browse/RE-1502
In order to cater to nodepool now handling almost all PR jobs,
we adjust the quotas.
1. We set max-servers in the main pool for each region to 20,
providing a total maximum of 60 servers from the main pool
which will be handling non-container tests for PR's.
2. We set the min-ready for the ubuntu-xenial and ubuntu-trusty
nodes to 0 as they're being phased out and replaced with the
more explicitly named (according to flavor profile)
ubuntu-xenial-g1-8 and …

RE-1463 Extend nodepool usage to more PR jobs

---

rpc_jobs/rpc_maas.yml
rpc_jobs/rpc_role_logstash.yml

In order to make on-demand testing easier, and to highlight
bit-rot, we add PM jobs for rpc-maas and rpc-role-logstash.

RE-1463 Add PM jobs tor rpc-role-logstash and rpc-maas

---

nodepool/files/nodepool.yml

Using https for the mirror is pointless, and prevents
caching from having any useful effect. A recent RPC-O
test failed due to a TLS error communicating with the
mirror.
In order to reduce the chances of failure, and improve
caching performance in tests, we switch the image to
use http instead of https.

RE-1463 Use http for mirror.rackspace.com

---

rpc_jobs/jjb_setup.yml

With a lock around the actual execution of JJB. This means
JJB will still only be running in serial, but setup stuff such
as building venvs can happen in parallel.
Issue: [RE-1514](https://rpc-openstack.atlassian.net/browse/RE-1514)

RE-1514 Allow JJB to execute concurrently

---

rpc_jobs/pull_request_issue_link.yml

This commit updates the status-context for the issue link job to be
consistent with other status-contexts (underscore versus dash).
NOTE: Both rpc-openstack and rpc-gating have this job configured, but
neither have branches where this job is set to required. As such,
nothing should need to be done in GitHub once this merges.
Issue: [RE-1489](https://rpc-openstack.atlassian.net/browse/RE-1489)

RE-1489 Update issue link status-context

---

constraints_rpc_component.txt
rpc_jobs/standard_job_release.yml
scripts/dep_update.sh

rpc_component has been moved from mattt416/rpc-metadata to
rcbops/rpc_component. This change updates the use of rpc_component to
pin it to the latest available version.
In addition a few breaking changes have been addressed so that the new
version works where used. These changes centre around more consistent
use of the terms release and version.
Issue: [RE-1491](https://rpc-openstack.atlassian.net/browse/RE-1491)

RE-1491 Update use of rpc_component

---

nodepool/files/nodepool.yml
rpc_jobs/hardening.yml
rpc_jobs/rpc_openstack.yml
rpc_jobs/rpc_upgrades.yml

The nodepool provisioning is encountering some trouble with
onmetal provisioning due to quota calculations and also seems
to not work right with multiple pools. While we work out the
root cause and a solution for it, we revert to the previous
configuration - but add the ability to fall back from IAD to
DFW now that we're using the io2 flavor which is available in
both regions.
Issue: [RE-1516](https://rpc-openstack.atlassian.net/browse/RE-1516)

RE-1516 Revert MNAIO jobs to not use nodepool

---

playbooks/allocate_pubcloud.yml

OnMetal hosts take ~5 mins to be connectible via SSH. We
set the timeout to 10 mins to give it some breathing room.
Issue: [RE-1516](https://rpc-openstack.atlassian.net/browse/RE-1516)

RE-1516 Wait for up to 10 mins for SSH connectivity

---

rpc_jobs/rpc_upgrades.yml

This commit expands the mnaio upgrade jobs to include the execution of
`rpc-openstack-system-tests`. This execution is triggered by the
inclusion of an additional field (separated by `_`) in the action
parameter.
Issue: [ASC-476](https://rpc-openstack.atlassian.net/browse/ASC-476)

ASC-476 Add system testsing jobs to mnaio upgrades

---

pipeline_steps/common.groovy
pipeline_steps/pubcloud.groovy
playbooks/templates/artifact/index.html
playbooks/templates/artifact/styles.css
playbooks/upload_to_swift.yml
rpc_jobs/unit/artefact_publish.yml

Currently all artefacts are compressed into a single archive
and uploaded to cloud files. This is convenient if you want
to download all the artefacts. However it turns out that
most of the time it would be more useful to be able to
directly link to individual artefacts.
This commit changes upload artefacts so that each job has
a unique container and files are uploaded individually.
Cloud files has no index generation feature so a searchable
index page is also generated.
Issue: [RE-1498](https://rpc-openstack.atlassian.net/browse/RE-1498)

RE-1498 Browsable Artefacts

---

scripts/build_summary/build_summary_gh.py
scripts/build_summary/failure.py

Currently build summary is very laggy becuase data.json is very
large. Its large because some jobs have very long lines (an
entire RPCO run in one case). And that entire line is getting
embedded into the data.json file.
This commit puts an 1000 char limit on the detail field.
Issue: [RE-1505](https://rpc-openstack.atlassian.net/browse/RE-1505)

RE-1505 Remove large values from summary data

---

rpc_jobs/rpc_maas.yml

Currently we have pike, newton, and ceph all gating on a trusty image,
but pike only supports xenial and it appears that the ceph job is also
only run on xenial in the pre-merge tests.
This commit splits out the periodic tests into a separate trusty and
xenial project.

RE-1463 Adjust rpc-maas periodic jobs

---

nodepool/files/elements/rpco-artifacts-ubuntu-minimal/element-deps
nodepool/files/elements/rpco-artifacts-ubuntu-minimal/element-provides
nodepool/files/elements/rpco-artifacts-ubuntu-minimal/environment.d/10-ubuntu-environment
nodepool/files/elements/rpco-artifacts-ubuntu-minimal/package-installs.yaml
nodepool/files/elements/rpco-artifacts-ubuntu-minimal/root.d/75-ubuntu-minimal-baseinstall
nodepool/files/nodepool.yml

In order to implement the ability for nodepool to build a base
image which is usable for RPC-O newton strict artifact builds,
we add the appropriate diskimage-builder elements and config
to build an image using the apt artifact repository, and the
appropriate nodepool config to ensure that we are able to
request nodes using this image.
We deliberately do not want to convert any jobs over to using
this image yet as we need to confirm that the nodes provided
with this image are usable and do not break the tests.
Issue: [RE-1466](https://rpc-openstack.atlassian.net/browse/RE-1466)

RE-1466 Add nodepool config for RPC-O artifacted base images

---

nodepool/files/nodepool.yml

The node label was used instead of the diskimage name.
This patch corrects it.
Issue: [RE-1466](https://rpc-openstack.atlassian.net/browse/RE-1466)

RE-1466 Correct diskimage name

---

pipeline_steps/common.groovy
rpc_jobs/standard_job_release.yml
scripts/add_component_gate_trigger_job.sh

This change extends the standard release job to allow new components to
be added to the releases repo.
In addition, when a new component is registered this change creates a
pull request to rpc-gating to get the gate trigger job set up, the
trigger job is used to gate a component's pull requests.
Issue: [RE-1487](https://rpc-openstack.atlassian.net/browse/RE-1487)
Test pull request - https://github.com/rcbops/rpc-gating/pull/850
Test issue - https://rpc-openstack.atlassian.net/browse/RE-1528

RE-1487 Add component registration support

---

rpc_jobs/rpc_designate.yml

The snapshot periodic jobs are running reliably, so no need to run both
sets any longer.
Issue: [RE-1536](https://rpc-openstack.atlassian.net/browse/RE-1536)

RE-1536 Remove non-snapshot periodic jobs

---

pipeline_steps/common.groovy
pipeline_steps/pubcloud.groovy
playbooks/templates/artifact/index.html
playbooks/templates/artifact/styles.css
playbooks/upload_to_swift.yml
rpc_jobs/unit/artefact_publish.yml

The first attempt at this failed, as we were using a cloud files
api call which takes an archive and expands it out into a container.
That operation was too slow and unreliable to be useful.
As a recap, the aim is to have artifacts be browsable (and therefore
linkable) but also downloadable in bulk for local analysis.
This commit achieves both aims, by uploading a single archive but
also uploading each file individually. Both of these operations
have potential to take significant amounts of time. Archive creation
has taken 3 hours in the past due to compression. In order to speed
that up, this commit switches from bzip compression to gzip --fast
which can be an order of magnitude faster. Single file upload can
also be slow due to the number of api operations it requires. The
api rate …

RE-1526 Browsable Artifacts Attempt 2

---

playbooks/upload_to_swift.yml

The ARA report links to foo/ and expects foo/index.html to be returned.
That wasn't working, despite the rackspace docs saying:
The page you set for X-Container-Meta-Web-Index becomes the index page
for every subdirectory in your website.
Testing showed that this does work, but that upload_to_swift wasn't
enabling the static website correctly. The problem was that the
container name should have been appended to the object store url
used for enabling the static website.
This commit fixes this above problem and also enables file listing
so that a user can browse files/folders directly as well as using
the generated index.html.
Issue: [RE-1545](https://rpc-openstack.atlassian.net/browse/RE-1545)

RE-1545 Fix enable static website

---

playbooks/templates/artifact/index.html

Chrome fails to download the archive, instead it logs a content
type warning to the console. This commit fixes the issue by
adding the html5 download attribute to instruct the browser to
download rather than display the linked file.
Issue: [RE-1546](https://rpc-openstack.atlassian.net/browse/RE-1546)

RE-1546 Use html download attribute

---

rpc_jobs/rpc_artifact_build.yml
rpc_jobs/standard_job_dep_update.yml
rpc_jobs/standard_job_premerge.yml
rpc_jobs/standard_job_premerge_release.yml
rpc_jobs/unit/re_unit_tests.yml

I suspect we added this when we had multiple jenkins instances running
at the same time, but this is no longer necessary.
We will need to communicate this change to users and merge on a set
date to avoid any surprises.
Issue: [RE-1489](https://rpc-openstack.atlassian.net/browse/RE-1489)

RE-1489 Remove CIT reference from recheck triggers

---

rpc_jobs/rpc_upgrades.yml

Adds incremental AIO test for newton to queens using
incremental upgrades script from each branch in OSA.
Don't merge until https://github.com/rcbops/rpc-upgrades/pull/165 is merged.
Issue: [RLM-1471](https://rpc-openstack.atlassian.net/browse/RLM-1471)

RLM-1471 Adds incremental test of Newton to Queens

---

rpc_jobs/rpc_openstack.yml

This creates the following postmerge AIO job:
PM_rpc-openstack-master-rc-xenial_no_artifacts-swift-deploy
Issue: RO-4245
Issue: [RO-4245](https://rpc-openstack.atlassian.net/browse/RO-4245)

[RO-4245] Create master-rc postmerge AIO job

---

rpc_jobs/unit/re_unit_tests.yml

Currently the status context and trigger phrase doesn't match. Instead
of adding `re` to the trigger phrase, we just remove it from the status
context since we don't use this prefix anywhere else.
Once this merges, we'll need to update the repo settings to make this
test required (since it's going to appear as a new test).
Additionally, we remove an unnecessary `?` in the trigger phrase. This
was left over when we removed the `cit` reference from the trigger
phrase in 36f717f5.
Issue: [RE-1297](https://rpc-openstack.atlassian.net/browse/RE-1297)

RE-1297 Remove `re` ref from status context

---

nodepool/files/nodepool.yml

The flavor '7' isn't recognised by the shade library,
but using the actual name of the flavor works. This
patch corrects the name so that this base image is
usable, then sets the minimum number of available
nodes to verify that the image nodes start successfully
and are usable for testing.
Issue: [RE-1466](https://rpc-openstack.atlassian.net/browse/RE-1466)

RE-1466 Correct rpco-14.2-xenial-base flavor name

---

rpc_jobs/rpc_octavia.yml

The rpc-r14.15.0-xenial-swift image has some necessary fixes in it to
update endpoint IPs after a thaw. This commit bumps the image and also
sets the flavor to a flavor 8 as the 7 causes excessive swapping when
octavia starts spinning up instances.
Issue: [RE-1550](https://rpc-openstack.atlassian.net/browse/RE-1550)

RE-1550 Update rpc-octavia snapshot image

---

rpc_jobs/rpc_openstack.yml

Mitaka deploy test jobs are no longer needed, so removing
Issue: [RE-1575](https://rpc-openstack.atlassian.net/browse/RE-1575)

RE-1575 Removes Mitaka Gating Jobs

---

rpc_jobs/standard_job_release.yml

If the first version of a component is being released the previous
version argument, used for generating release notes, gets set to an
empty string. It is left the component to determine how to use that
information.
Issue: [RE-1535](https://rpc-openstack.atlassian.net/browse/RE-1535)

RE-1535 Fix release when no previous version

---

constraints_rpc_component.txt

This change updates rpc_component to the latest version to ensure
rpc-gating works with the new component file format, where release order
is reversed.
Issue: [RE-1513](https://rpc-openstack.atlassian.net/browse/RE-1513)

RE-1513 Update rpc_component SHA

---

nodepool/files/nodepool.yml

In order to replace the "Ubuntu 14.04.5 LTS prepared for RPC deployment"
images used widely across multiple tests, we add the configuration to
make nodepool build the images and prepare a set of nodes which can be
tested against.
Issue: [RE-1583](https://rpc-openstack.atlassian.net/browse/RE-1583)

RE-1583 Add image configuration for artifacted trusty nodes

---

rpc_jobs/rpc_openstack.yml

With the dependent PR merged, we can start using nodepool nodes
which use an image built by nodepool, instead of relying on the
static image created some time ago which cannot be re-created.
The pike and master branches already use nodepool for PR's.
Depends-On: https://github.com/rcbops/rpc-openstack/pull/3062
This has been tested in https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-openstack-newton-xenial-swift-deploy-testjp/7/
Issue: [RE-1584](https://rpc-openstack.atlassian.net/browse/RE-1584)

RE-1584 Move rpc-openstack newton xenial PR jobs to use nodepool

---

rpc_jobs/rpc_upgrades.yml

Drops 14.2.0 leap testing
Issue: [RLM-1498](https://rpc-openstack.atlassian.net/browse/RLM-1498)

RLM-1498 Drops 14.2.0 leap testing

---

rpc_jobs/rpc_openstack.yml

Unfortunately the 'nodepool-' prefix was left off the node name.
Issue: [RE-1584](https://rpc-openstack.atlassian.net/browse/RE-1584)

RE-1584 Correct nodepool node name for RPC-O newton xenial nodes

---

rpc_jobs/rpc_openstack.yml

We can now use nodepool nodes instead of relying on the
static image created some time ago which cannot be
re-created.
This has been tested here: https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-openstack-newton-trusty-swift-deploy-testjp/11
Issue: [RE-1585](https://rpc-openstack.atlassian.net/browse/RE-1585)

RE-1585 Move rpc-o newton trusty PR jobs to use nodepool

---

rpc_jobs/rpc_octavia.yml

We also flip the flavor size back to 7, since we've since had a
successful run on this flavor [1].
[1] https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-octavia-master-xenial_snapshot-functional-test/16/
Issue: [RE-1550](https://rpc-openstack.atlassian.net/browse/RE-1550)

RE-1550 Add rpc-octavia pike snapshot

---

rpc_jobs/rpc_openstack.yml

This commit creates a discrete postmerge MNAIO job labeled as
`experimental_asc`. The purpose of this is to enable experimental test
execution on CI MNAIO infrastructure without impacting the production CI
jobs.
Issue: [ASC-635](https://rpc-openstack.atlassian.net/browse/ASC-635)

ASC-635 Create ASC experimental job

---

rpc_jobs/rpc_eng_ops.yml

Don't automatically run a job that doesn't clean up after itself
because there's not enough resources (ie Ironic nodes in Phobos) for
that, but don't delete the job so that it can be ran manually to debug
the self-cleaning-and-automatic version.
https://rpc-openstack.atlassian.net/browse/REO-268
Issue: [REO-268](https://rpc-openstack.atlassian.net/browse/REO-268)

REO-268: Don't timer-trigger rpc-eng-ops noclean job

---

rpc_jobs/phobos.yml

Execute `git submodule sync` before executing `git submodule update
--init` to account for a possible change in a submodule's "url".
https://rpc-openstack.atlassian.net/browse/REO-265
Issue: [REO-265](https://rpc-openstack.atlassian.net/browse/REO-265)

REO-265 Sync Git submodules before updating

---

nodepool/files/elements/rpco-artifacts-ubuntu-minimal/root.d/75-ubuntu-minimal-baseinstall
rpc_jobs/rpc_upgrades.yml

We can now use nodepool nodes instead of relying on the
static image created some time ago which cannot be
re-created. This broadens the regions available to the
test execution and provides quicker access to the nodes.
Also, the tests which make use of the artifacted image expect
a backup of the default apt sources to be in place to allow
switching from artifacted to non-artifacted setups. Instead of
the tests having to assume or derive the correct default sources
we include a copy in the image instead.
Do NOT merge until https://github.com/rcbops/rpc-upgrades/pull/186 is merged.
Issue: [RE-1590](https://rpc-openstack.atlassian.net/browse/RE-1590)

RE-1590 Move rpc-upgrades AIO PR's to nodepool

---

rpc_jobs/rpc_designate.yml

The snapshot-based PM builds have been running successfully for
some time now, and are executed far faster.
This PR switches the PR builds to do the same thing, and switches
the error reporting from RE to RI considering it's now a stable
implementation.
Issue: [RE-1610](https://rpc-openstack.atlassian.net/browse/RE-1610)

RE-1610 Move rpc-designate PR jobs to use snapshot builds

---

job_dsl/rpc_artifact_build.groovy
pipeline_steps/artifact_build.groovy
rpc_jobs/build_gating_venv.yml
rpc_jobs/build_summary.yml
rpc_jobs/rpc_artifact_build.yml

We can now use nodepool nodes instead of relying on the
static image created some time ago which cannot be
re-created. This broadens the regions available to the
test execution and provides quicker access to the nodes.
Some technical debt management changes have been made
in this PR - please see the individual commits for more details.
Depends-On: https://github.com/rcbops/rpc-openstack/pull/3082
Test: https://rpc.jenkins.cit.rackspace.net/job/PM-rpc-openstack-newton-artifact-build/5/
Issue: [RE-1596](https://rpc-openstack.atlassian.net/browse/RE-1596)

RE-1596 Move RPC-O artifact builds to use nodepool

---

pipeline_steps/artifact_build.groovy
rpc_jobs/rpc_artifact_build.yml

This reverts commit b677b6d673261d0b96a755fa19e40869ba52583c.
This function is no longer needed. The commit was only included
in order to allow testing to pass prior to the PR merging.
Issue: [RE-1596](https://rpc-openstack.atlassian.net/browse/RE-1596)

Revert "RE-1596 Restore get_rpc_repo_creds function"

---

rpc_jobs/rpc_openstack.yml

This commit adds an 'sdqc' action to the
`rpc-openstack-master-mnaio-postmerge` project. The `ironic` scenario is
excluded when this action is used. So, the only job that should be
created by this change is:
PM_rpc-openstack-master-xenial_mnaio_no_artifacts-swift-sdqc
The purpose of this is to run the deployment and validation of
[openstack-ops](https://github.com/rsoprivatecloud/openstack-ops/) in
isolation from other system test suites. Currently, this is necessary
due to a conflict in the deployment ansible code.
Issue: [ASC-655](https://rpc-openstack.atlassian.net/browse/ASC-655)

ASC-655 Add sdqc action

---

rpc_jobs/rpc_octavia.yml

Snapshot builds can cut the build time down radically for jobs
which make use of RPC-O as a base. This PR implements exclusive
use of the snapshots for PR and PM jobs now that this has been
confirmed to work.
Issue: [RE-1611](https://rpc-openstack.atlassian.net/browse/RE-1611)

RE-1611 Move rpc-octavia to only use snapshot builds

---

rpc_jobs/rpc_upgrades.yml

Adds Mitaka as an AIO PR job to be tested.
Drops the major job as we're not using it for M->N.
Also slips a bump for the minor job to the latest release in.
Issue: [FLEEK-75](https://rpc-openstack.atlassian.net/browse/FLEEK-75)

FLEEK-75 Adds Mitaka Leap as a PR Job

---

rpc_jobs/rpc_maas.yml
rpc_jobs/rpc_openstack.yml

This commit adds a pike and newton MNAIO release job for rpc-openstack.
The MNAIO jobs are often referred to to determine the health of a
branch before release, so it makes most sense to run these prior to
releasing.
Additionally, we update a comment in rpc_maas.yml to better reflect our
intention of splitting out check and gate jobs after rpc-maas has been
successfully added to the pipeline. This comment was inadvertently
copied from rpc-ceph and since rpc-maas already has a lint and
functional jobs this should be a straight-forward exercise for us to
do.
Issue: [RE-1484](https://rpc-openstack.atlassian.net/browse/RE-1484)

RE-1484 Add rpc-openstack release jobs

---

rpc_jobs/rpc_openstack.yml

This commit adds the `sdqc` action to the
`rpc-openstack-master-rc-mnaio-postmerge` project.
Issue: [ASC-655](https://rpc-openstack.atlassian.net/browse/ASC-655)

ASC-655 Add sdqc action to MNAIO master-rc

---

pipeline_steps/common.groovy

The common. prefix can't be used to call functions from within
common. This commit removes the prefix and also adds an inner
try/catch to stop any other issues like this leaking out to the
build result.
Issue: [RE-1626](https://rpc-openstack.atlassian.net/browse/RE-1626)

RE-1626 Fix jira issue creation for upload fails

---

lint.sh
pipeline_steps/common.groovy
pipeline_steps/gate.groovy
pipeline_steps/github.groovy
rpc_jobs/standard_job_gate.yml
scripts/ghutils.py
scripts/lint_support_groovy/queue.groovy
scripts/lint_support_groovy/result.groovy
scripts/lint_support_groovy/workflowjob.groovy
src/com/rackspace/exceptions/REException.groovy

Without this change, any Component-Gate-Trigger_ job tests a pull
request against the target branch using the merge branch supplied by
GitHub but does not account for any changes that merge while those tests
are running.
This change ensures that a pull request is tested with any other pull
requests that are also going through the gate. To achieve this a build
looks for any builds that were started before it and includes their pull
requests in its own tests. If any of those builds fails, the tests on
dependent builds are terminated with a link to the upstream build and
new ones are started.
This change should provide a stronger guarantee as to the state of the
repository however if tests are unstable or pull requests are approved
that are broken, the time to merge a working pull request …

RE-1513 Improve gate test guarantees

---

pipeline_steps/gate.groovy
rpc_jobs/dummy_pipeline.yml
rpc_jobs/rpc_maas.yml

Currently, the gate jobs do not check if the commit is only changing
files in the skip_list. This means we may end up running lengthy gate
jobs which don't need to be run. This commit updates
pipeline/gate.groovy to only run gate jobs if isSkippable() is false.
Additionally, we update rpc-maas' skip_list replacing
gating/post_merge_test with gating/periodic, and add gating/release to
the existing skip_pattern. We also duplicate this skip_pattern to the
commented gate jobs in rpc_maas.yml.
Lastly, for testing, we update dummy_pipeline.yml to add a skip_pattern
to rpc-product-1's check and gate jobs.
Issue: [RE-1606](https://rpc-openstack.atlassian.net/browse/RE-1606)

RE-1606 Check skip_pattern in gate jobs

---

rpc_jobs/rpc_upgrades.yml

* Adds Mitaka to release, moves all version tests to release only
and leaves head leap to release tests.
* Moves minor upgrade to it's own section to avoid the excludes
Issue: [FLEEK-60](https://rpc-openstack.atlassian.net/browse/FLEEK-60)

FLEEK-60 Adds Mitaka version leap jobs to release

---

rpc_jobs/rpc_upgrades.yml

This commit removes all but the following leapfrog system jobs.
* PM_rpc-upgrades-master-trusty_mnaio-swift-liberty_to_r14.current_leap_system
* PM_rpc-upgrades-master-trusty_mnaio-swift-liberty_to_newton_leap_system
At the time of this commit, all of the leapfrog system jobs were
consistently failing. The jobs would either fail during deployment or
the system tests would fail. In order to reduce the noise and not waste
infrastructure resources all but the above jobs are being deleted.
The above jobs should be enough for us to be able to resolve the root
cause of the failures. Once they are passing the jobs deleted in this PR
will be added back in a more controlled manner.
JIRA: ASC-662
Issue: [ASC-662](https://rpc-openstack.atlassian.net/browse/ASC-662)

ASC-662 Remove most leapfrog system jobs

---

job_dsl/rpc_gating_merge_trigger.groovy
rpc_jobs/build_summary.yml
rpc_jobs/jjb_setup.yml
rpc_jobs/rpc_gating.yml
rpc_jobs/setup_grafana.yml
rpc_jobs/setup_graphite.yml
rpc_jobs/setup_nodepool.yml
rpc_jobs/setup_statsd.yml
rpc_jobs/standard_job_postmerge.yml
rpc_jobs/unit/re_unit_tests.yml

In order to properly co-ordinate the execution of merge
trigger jobs when commits are merged into rpc-gating,
we create a single merge trigger job which co-ordinates
the others appropriately.
Please see the individual commits for details of each change.
Tested successfully here:
https://rpc.jenkins.cit.rackspace.net/job/Merge-Trigger-rpc-gating/19
Issue: [RE-1503](https://rpc-openstack.atlassian.net/browse/RE-1503)

RE-1503 Add rpc-gating merge trigger job

---

rpc_jobs/standard_job_release.yml

Where we run the `git rev-parse --verify` in
`rpc_jobs/standard_job_release.yml`, no local branch exists tracking
the remote rc branch and therefore the verify fails with
`fatal: Needed a single revision`. This commit prefixes `${RC_BRANCH}`
with `remotes/origin` to correctly validate if the branch exists.
Additionally, we add some log statements to easily identify if we're
releasing from `${MAINLINE}` or `${RC_BRANCH}`.
Issue: [RE-1683](https://rpc-openstack.atlassian.net/browse/RE-1683)

RE-1683 Correctly reference remote rc branch

---

playbooks/upload_to_swift.yml

In order to improve the chances of the job artifact uploads
succeeding, all operations now have retries added, and more
specific conditions for success.
The rax_pub_cloud fact setting, related conditionals and tasks
for the 'not rax_pub_cloud' case are removed as that is an
unused and untested code path.
The 'Get Rackspace CloudFiles CDN URL' task is removed. The
previous task returns the data required, so this removes an
extra API call and point of failure.
The URI tasks have tightened response codes, with comments
for what each code means. This prevents failures leaking
through and makes it easier to understand what they are.
The URI tasks have 'no_log: True' removed, as they do not
expose any sensitive information unless the playbook is
run with '-vvv' which is not the case here.
As a …

Add retries and conditionals to cloudfiles upload

---

rpc_jobs/standard_job_release.yml

Currently, when we release through the pipeline we're tagging with the
branch (mainline or mainline-rc) instead of the specified SHA. This
commit updates rpc_jobs/standard_job_release.yml to tag the SHA incase
the specified SHA is not the latest commit in the branch.
Issue: [RE-1682](https://rpc-openstack.atlassian.net/browse/RE-1682)

RE-1682 Tag SHA not branch

---

playbooks/upload_to_swift.yml

When doing authentication, just validating that auth_token
is defined may not be enough. In this patch we make sure
that it is defined and that it is not empty.
JIRA: RE-1618
Issue: [RE-1618](https://rpc-openstack.atlassian.net/browse/RE-1618)

Add extra validation conditionals for auth_token

---

playbooks/upload_to_swift.yml

The URI module tasks are still intermittently failing with
a 401 error (unauthorized), but sometimes pass a little later
on a retry. Before we go ahead and implement changes to the
os_object module, or try another region, we implement an
increase in delays and retries in the hope that an intermittently
failing API would not be doing so over the period of 5 mins
(10 retries with a 30 second delay between each).
Issue: [RE-1618](https://rpc-openstack.atlassian.net/browse/RE-1618)

Increase Cloud Files action retries/delays

---

gating/common/run_lint.sh
influx-reports/influx.py
lint.sh
requirements.txt
scripts/build_summary/build.py
scripts/build_summary/build_summary_gh.py
scripts/build_summary/components.js
scripts/build_summary/constraints.txt
scripts/build_summary/failure.py
scripts/build_summary/index.html
scripts/build_summary/requirements.txt
scripts/build_summary/styles.css
scripts/build_summary/views.js
scripts/create_cloud_image.py
scripts/ghutils.py
scripts/jenkins_node.py
scripts/jirautils.py
scripts/lint_jjb.py
scripts/maasutils.py
scripts/notifications.py
scripts/periodic_cleanup.py
scripts/release.py
test-requirements.txt

This PR rewrites the build summary interface so that
* Failures can be viewed by category
* Individual repos/jobs/failures/failure categories can be inspected
* Items within the ui can be linked from outside
* Dynamic graphs/tables with tabs so that the
most relevant data can be shown without overwhelming the page.
This commit builds on the previous commit that shifted to vuejs
but kept the ui largely similar to the old jquery one.
This embraces vue, and its component structure.
Issue: [RO-4182](https://rpc-openstack.atlassian.net/browse/RO-4182)

RO-4182 Job Failure Analysis

---

pipeline_steps/common.groovy
scripts/jirautils.py

The post merge test standard job (Created in RE-507) creates
JIRA issues on failure. These issues use the default label from
jirautils.py which is "jenkins-build-failure".  This task should allow a
label to be set in common.groovy (as "post-merge-test-failure" in
stdJob) and passes the label to jirautil.py.
JIRA: RE-783
Issue: [RE-783](https://rpc-openstack.atlassian.net/browse/RE-783)

RE-783 Change the label for build failure issues

---

rpc_jobs/rpc_ceph.yml

This enables 3rd party dep updates for rpc-ceph.
Issue: [CEPHSTORA-236](https://rpc-openstack.atlassian.net/browse/CEPHSTORA-236)

CEPHSTORA-236 Enable 3rd party dep updates

---

playbooks/phobos_vpn.yml
rpc_jobs/setup_nodepool.yml

This reverts commit 54c71e1ac47deb617ab139f964dee6f1ffe4c970.
This commit is causing the setup_nodepool job to fail as it is not
passing the correct vars to it.
Issue: [RE-1735](https://rpc-openstack.atlassian.net/browse/RE-1735)

[RE-1735] Revert "RE-1555 Implement VPN Connectivity"

---

playbooks/templates/artifact/index.html

Instead of linking to the main page of the build summary, link
to the build summary page for the job that generated the artifacts.
Issue: [RE-1500](https://rpc-openstack.atlassian.net/browse/RE-1500)

RE-1500 Artifact index build summary job link

---

scripts/dep_update.sh

The original message posted in the JIRA ticket created by dep_update is
"This issue was generated automatically by the Jenkins job
${RE_JOB_NAME}. See update_dependencies in https://rpc-openstack.atlass-
ian.net/wiki/spaces/RE/pages/19005457/RE+for+Projects for more details."
This task should modify the message to include pull request information.
For the sake of keeping the message relatively short, only the PR link
will be included, but additional PR info can be added if desired.
According to jenkinsci/plugins/ghprb/GhprbTrigger.java, which sets pull
request related environment variables, the pull request link environment
variable that should be used for this modification is $ghprbPullLink
JIRA: RE-1725
Issue: [RE-1725](https://rpc-openstack.atlassian.net/browse/RE-1725)

RE-1725 Add PR info to dep_update issue message

---

job_dsl/release.groovy
job_dsl/rpc_artifact_build.groovy
job_dsl/rpc_gating_merge_trigger.groovy
job_dsl/standard_job_dep_update.groovy
rpc_jobs/standard_job_gate.yml
rpc_jobs/standard_job_postmerge.yml
rpc_jobs/standard_job_premerge.yml
rpc_jobs/standard_job_release.yml

There are now two global libraries defined in jenkins, rpc-gating
and rpc-gating-master. rpc-gating does a full clone and fetches
additional refs such as PRs. rpc-gating master does a shallow clone
and does not fetch additional refs. Consequently rpc-gating-master
is faster and uses fewer resources on the master. This commit moves
production standard jobs to use rpc-gating-master. The pre merge
standard job will use rpc-gating when running against the rpc-gating
repo.
Issue: [RE-1582](https://rpc-openstack.atlassian.net/browse/RE-1582)

RE-1582 Reduce library clone size

---

pipeline_steps/common.groovy
rpc_jobs/standard_job_release.yml

This commit updates the release process to check for the following:
- if the specified SHA is valid
- if the component has an RC branch
- if the tip of the RC branch matches the supplied SHA
Rather than checking this after the RELEASE_* jobs have run, we move
these checks into runReleasesPullRequestWorkflow(). This means an
issue with a SHA will surface before we've wasted time running
RELEASE_* jobs.
Additionally, we correctly reference `componentYaml` in
runReleasesPullRequestWorkflow() rather than `component_text` since
`component_text` is being made available from some outer scope.
Lastly, since we're now checking for the RC branch in
runReleasesPullRequestWorkflow(), we add a bool parameter called
`from_rc_branch` to the `Component-Release` job and correctly pass this
in in …

RE-1682 Check SHA before running RELEASE_*

---

playbooks/allocate_pubcloud.yml

Sometimes when an instance is created, it is not possible
to ssh to it. This is especially true of OnMetal nodes.
To try and prevent this from affecting tests before the
tests can be migrated to use nodepool, we implement a
try/rescue block so that if either the instance creation
or the ssh connection test fails, the instance is unusable
and a second attempt is done in the fallback region.
Also:
1. The variable 'primary_region_attempts' is removed, as it
is unused.
2. The variable 'regions_shuf' is renamed to 'regions_shuff'
so that it is more uniform with 'fallback_regions_shuff'.
3. The difference filter used in 'fallback_regions_shuff' is
documented, and fixed to use 'regions_shuff' as it should
be.
4. Extra debug output is added to help diagnose issues which
may arise with this …

Verify ssh connectivity for jenkins slaves

---

rpc_jobs/rpc_maas.yml

Now that we've added bandit to rpc-maas' tox.ini, we'd like to have it as a Jenkins job.
JIRA: TURTLES-1017
Issue: [TURTLES-1017](https://rpc-openstack.atlassian.net/browse/TURTLES-1017)

TURTLES-1017: Add bandit to rpc-maas premerge

---

rpc_jobs/repo_server.yml
rpc_jobs/setup_grafana.yml
rpc_jobs/setup_graphite.yml
rpc_jobs/setup_nodepool.yml
rpc_jobs/setup_statsd.yml
scripts/ansible_v2_3_2_0_1_contrib_inventory_openstack.py

When Ansible uses the dynamic inventory to create instances, the
inventory currently fails due to the new Phobos cloud configuration
which is unreachable for the Jenkins slaves.
This patch updates the dynamic inventory to the latest available
version in 'stable-2.4' branch which provides the ability to set
a specific OS_CLOUD environment variable to tell the script to only
look at that cloud.
We also update all the jobs to make use of this environment variable.
This has been verified to work:
https://rpc.jenkins.cit.rackspace.net/job/Setup-Grafana/243/
JIRA: RE-1751
Issue: [RE-1751](https://rpc-openstack.atlassian.net/browse/RE-1751)

Update RE jobs to set OS_CLOUD when creating instances

---

playbooks/allocate_pubcloud.yml

To ensure that we're able to effectively handle transient
failures, we split the apt cache update and installs, and
we add retries to both. We also shift to using 'apt-get'
instead of 'apt' as the output does not have color coding
and is therefore easier to read in Ansible's output.
JIRA: RE-1752
Issue: [RE-1752](https://rpc-openstack.atlassian.net/browse/RE-1752)

Separate the apt commands for OnMetal tests

---

rpc_jobs/periodic_cleanup.yml

- Added `cloud_creds` to periodic cleanup creds wrapper so that python script env PUBCLOUD_* creds were available.
JIRA: RE-1753
Issue: [RE-1753](https://rpc-openstack.atlassian.net/browse/RE-1753)

RE-1753 Periodic Cleanup Cloud Creds Fix

---

nodepool/files/nodepool.yml
pipeline_steps/common.groovy

In order to verify that image uploads are working correctly
before anything else, we set max-servers to 0. Once the image
uploads are confirmed to be working we can increase this
number so that Phobos takes on test workloads.
JIRA: RE-1559
Issue: [RE-1559](https://rpc-openstack.atlassian.net/browse/RE-1559)

Set max-servers for nodepool to 0

---

nodepool/files/nodepool.yml

- Added hypervisor_type meta tag for disk images to keeps them from getting assigned to ironic nodes.
JIRA: RE-1755
Issue: [RE-1755](https://rpc-openstack.atlassian.net/browse/RE-1755)

RE-1755 Ensure Nodepool Disk Images Have Correct Metadata

---

playbooks/allocate_pubcloud.yml

Some of the OnMetal hosts are failing to install the
python-minimal and python-yaml packages when they are
initially built, but the reason why they're failing
is not clear.
This patch adds some diagnostic configuration to the
host and some debug outputs to the tasks to help figure
out what's going on.
JIRA: RE-1758
Issue: [RE-1758](https://rpc-openstack.atlassian.net/browse/RE-1758)

Add debug outputs to help diagnose apt issues

---

playbooks/allocate_pubcloud.yml

The OnMetal hosts have their images prepared by Ubuntu
and therefore include the default use of Ubuntu mirror
for apt packages. These have turned out to be a bit
flaky so we have opted to reconfigure the hosts with
the Rackspace mirror instead, which we've found in
all our tests to be reliable.
This patch implements that change in configuration, but
also ensures that this is only done on a host which does
not already have python installed. This prevents any
unnecessary execution of the reconfiguration tasks.
Issue: [RE-1758](https://rpc-openstack.atlassian.net/browse/RE-1758)

Reconfigure apt sources for OnMetal hosts

---

pipeline_steps/pubcloud.groovy
playbooks/allocate_pubcloud.yml
scripts/reconfigure_apt_sources.sh

**Ensure retries cleanup**
The allocate_pubcloud playbook will try in a second region if creating an   
instance in the first region fails, or if the instance in the first region
can't be contacted via ssh.
This commit ensures that any instance created in the first region is
removed before attempting to create an instance in a second region.
This commit also ensures that writing the inventory file is the first task
after each instance creation task so that the cleanup stage has the highest
chance of success.
This commit also switches back from wait_for_connection to wait_for
as wait_for_connection ignores host and port parameters, only checking
connectivity to the host the task is targeted at.
**Ensure inventory stash happens**
If an error happens during the playbook that allocates …

RE-1767 Prevent Instance Leak

---

nodepool/templates/systemd-service-override.conf.j2
rpc_jobs/phobos_vpn_service.yml

- Added respawn limit unlimited line to restart VPN when process exists
JIRA: RE-1756
Issue: [RE-1756](https://rpc-openstack.atlassian.net/browse/RE-1756)

RE-1756 Jenkins Master VPN Dies

---

nodepool/files/nodepool.yml

Phobos builds are causing issues w/ rpc-maas tests (lack of created
entity), temporarily disabling phobos builds until rpc-maas is able to
address.
Issue: [RE-1782](https://rpc-openstack.atlassian.net/browse/RE-1782)

RE-1782 Temporarily disable phobos builds

---

playbooks/allocate_pubcloud.yml
playbooks/setup_jenkins_slave.yml

The current play combines the apt cache update and the
package install task in one, which is nice and concise
but makes it difficult to understand whether the install
failed due to an apt cache update failure or a package
install failure. Compounding the issue is the fact that
the apt module swallows the error in Ansible 2.3, so we
do not get to see it. Also, by default the apt_repository
module tries to update the apt cache after changing the
repository configuration, but if that fails then it will
retry and find on the second round that the file needs no
change and will not bother doing the cache update.
To improve our ability to diagnose errors when executing
these tasks, we move the setup of apt debug mode to be
done on all instances created (not just those without
python). We then …

Improve jenkins slave setup resilience

---

scripts/create_cloud_image.py

Snapshots are currently failing due to a recent change in
scripts/create_cloud_image.py:
```
>>> from six import xrange
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ImportError: cannot import name xrange
>>> from six.moves import xrange
>>>
```
This commit updates the six import.
Issue: [RE-1490](https://rpc-openstack.atlassian.net/browse/RE-1490)

RE-1490 Fix failing snapshot script

---

scripts/dep_update.sh

Reverts rcbops/rpc-gating#939
Harry pointed out that the pull request is already available in the side window and having the pull request in the message is not necessary or worth the trouble, so we decided to back-out the changes and consider RE-1725 and RE-1787 as done
Issue: [RE-1725](https://rpc-openstack.atlassian.net/browse/RE-1725)

Revert "RE-1725 Add PR info to dep_update issue message"

---

rpc_jobs/rpc_upgrades.yml

This commit adds some rpc-upgrades release jobs, and fine-tunes
skip_pattern for PR jobs.
Issue: [RE-1788](https://rpc-openstack.atlassian.net/browse/RE-1788)

RE-1788 Add rpc-upgrades release jobs

---

pipeline_steps/common.groovy

When RE_JOB_TRIGGER is PULL, we need to quote the RE_JOB_TRIGGER_DETAIL
env var as it contains spaces and is breaking the rpc-o's MNAIO tooling
when run on the MNAIO RELEASE job.
Issue: [RE-1548](https://rpc-openstack.atlassian.net/browse/RE-1548)

RE-1548 Quote env.RE_JOB_TRIGGER_DETAIL on PULL

---

nodepool/files/nodepool.yml
nodepool/setup_nodepool.yml

- Bumped NodePool Launcher SHA/version to include support for the new 'ignore-provider-quota' configuration option
- Added new 'ignore-provider-quota' configuration flag to each provider - this will allow to configuration to respect the max-servers value.
JIRA: RE-1729
Issue: [RE-1729](https://rpc-openstack.atlassian.net/browse/RE-1729)

RE-1729 Update NodePool to include RE-1521 and related configuration

---

rpc_jobs/rpc_appformix.yml
rpc_jobs/rpc_designate.yml
rpc_jobs/rpc_octavia.yml
rpc_jobs/rpc_openstack.yml

We're currently building newton/newton-rc snapshots for
trusty/trusty_loose_artifacts and xenial/xenial_loose_artifacts but
as only 'loose' artifact mode is being used in production we should
force all jobs to use the 'loose' image and skip building the 'strict'
images.
This commit adds a separate project for newton/newton-rc for snapshots
so we can be specific about which images get built.
Additionally, we bump all existing jobs using snapshots to use the
'loose' newton image, and bump all other snapshots to the latest
released version. Note that for queens, we actually fix the image to
rpc-r17 rather than rpc-r18.
Issue: [RE-1490](https://rpc-openstack.atlassian.net/browse/RE-1490)

RE-1490 Remove unneeded rpco snapshot jobs

---

rpc_jobs/rpc_openstack.yml
rpc_jobs/rpc_upgrades.yml

ORD has only a small subset of custom images, this commit removes this
region on jobs using these images.
Issue: [RE-1819](https://rpc-openstack.atlassian.net/browse/RE-1819)

RE-1819 Remove ORD when using custom RPC images

---

gating/common/run_snapshot.sh
rpc_jobs/bump_snapshots.yml
rpc_jobs/rpc_gating.yml

This commit adds a new job called Bump-Snapshot-Images that cycles
through rpc-openstack branches finding the latest tag and then bumps
versions of snapshot images in rpc_gating/.
Note that before we update any images, we test the image to ensure that
it is functional. Currently the latest snapshot image for each branch
will be tested regardless of whether a change has been detected, but
this serves as a bit rot test to help us identify problematic
rpc-openstack snapshots before users do.
Issue: [RE-1490](https://rpc-openstack.atlassian.net/browse/RE-1490)

RE-1490 Add job to bump snapshot versions

---

constraints.txt
job_dsl/release.groovy
requirements.txt
rpc_jobs/re_release_manual.yml
rpc_jobs/standard_job_release.yml
scripts/confluence_release_page.j2
scripts/confluenceutils.py
scripts/release.py

The purpose of this change is to automate the publishing of releases to
the Confluence wiki.
`release.py` is extended to include the new sub-command
`publish_release_to_wiki`. This updates the table on the page to include
an entry for the new release. If the release already exists on the page,
its details, such as comment, are updated.
If a release is done within 7 days of the first working day of the month
it is considered a scheduled release, if it is outside of that window it
is considered an asynchronous release. The wiki page "Product Releases"
details the differences between these two types of release.
JIRA: RE-1534
Issue: [RE-1534](https://rpc-openstack.atlassian.net/browse/RE-1534)

Extend release to publish details to Confluence

---

docs/debugging.md
pipeline_steps/common.groovy
pipeline_steps/pubcloud.groovy
playbooks/artifact_upload.yml
playbooks/tasks/artifact_upload/cloudfiles_authenticate.yml
playbooks/tasks/artifact_upload/cloudfiles_create_container.yml
playbooks/tasks/artifact_upload/upload_file.yml
playbooks/tasks/artifact_upload/upload_log.yml
rpc_jobs/unit/artefact_publish.yml

In this PR, we create a pluggable artifact upload hook which currently implements two types: 'log' and 'file'.
This new hook makes use of the in-repo ``component_metadata.yml`` file to discover its configuration.
The 'log' type works in exactly the same way as the current job artifact publishing, and has a shim for the ``RE_HOOK_ARTIFACT_DIR`` environment variable for backwards compatibility.
The 'file' type provides the capability to upload any file or recursively upload any folder to public cloud's cloudfiles, in a container name which matches the repository running the test.
We also switch the current log archiving mechanism to use the 'log' type.
There is follow up work in [RE-1813](https://rpc-openstack.atlassian.net/browse/RE-1813) to automatically publish the URL where these files …

RE-1325 Create pluggable artifact upload hook

---

scripts/build_summary/cachequery.py
scripts/build_summary/components.js
scripts/build_summary/failure.py
scripts/build_summary/index.html
scripts/build_summary/views.js

Addresses two grave bugs in the way build summary handles dates when
producing graphs:
1) The graphs are generated using a histogram, builds are divided into 60
24 hour buckets, and each bucket is labeled with a date. The problem is
that the start point is whenever the page is rendered so the 24 hour
histogram buckets do not line up with calendar days. The resolution is to
move the histogram start point to a day boundary so that histogram buckets
and days lineup.
2) The way that builds are allocated to buckets is by working out the
difference between the histogram end, and the build timestamp in
milliseconds, this in the divided by the number of milliseconds in a day
and rounded to produce an integer. That integer is subtracted from the
length of the histogram to get the bucket number. …

RE-1839 Build Summary Date Accounting Errors

---

pipeline_steps/common.groovy
rpc_jobs/bump_snapshots.yml
scripts/add_component_gate_trigger_job.sh

The original task asked to add a label for cards that were created
automatically.  At the time I began this task, the label "jenkins" had
been added to almost every automated PR/card, but after further
examination, some recent features do not include the "jenkins" label. So
this task now involves simply adding the "jenkins" label to any missing
automated card - for the sake of consistency.
JIRA: RE-730
Issue: [RE-730](https://rpc-openstack.atlassian.net/browse/RE-730)

RE-730 Make jenkins label consistent for JIRA cards

---

.gitignore

The rpc-gating venv contains openstack.logrotate, but it's not present
in .gitignore so anything attempting to do a `git add -A` in
rpc-gating will include this ansible role.
This commit updates .gitignore by adding playbookes/roles and removing
all individual roles specified in playbooks/roles/.
Issue: [RE-1800](https://rpc-openstack.atlassian.net/browse/RE-1800)

RE-1800 Add playbooks/roles/ to .gitignore

---

playbooks/ansible.cfg

The various tests which run may include implementing an ansible.cfg
file in the default search paths that ansible uses, resulting in
our playbooks trying to load/use things which are not meant to be.
To combat this, we override the paths for all plugin types and set
them to the location in the rpc-gating venv. We do the same for the
roles packaged into the rpc-gating tarball.
JIRA: [RE-1870](https://rpc-openstack.atlassian.net/browse/RE-1870)

Override default ansible plugin paths to prevent interference

---

job_dsl/release.groovy
rpc_jobs/re_release_manual.yml

This commit runs the release.py script inside a docker container,
removing the need for a project's generate_release_notes tooling to run
their scripts inside a docker container.
We will need to coordinate this change with changes to the following
projects to remove the docker references in their generate_release_notes
scripts:
rpc-openstack master/queens/pike/newton
rpc-maas master
rpc-upgrades master
rpc-ceph master
Issue: [RE-1616](https://rpc-openstack.atlassian.net/browse/RE-1616)

RE-1616 Run release tooling inside container

---

pipeline_steps/common.groovy

This reverts commit d8b9ef2010adb6e88a41eff1a370749ff1c3dfda.
This workaround is no longer required no the issues have been addressed
in rpc-openstack.
JIRA: 1798
This can be merged once all other pull requests against the issue have merged.
Issue: [RE-1548](https://rpc-openstack.atlassian.net/browse/RE-1548)

Revert "RE-1548 Quote env.RE_JOB_TRIGGER_DETAIL on PULL"

---

rpc_jobs/standard_job_premerge_release.yml

job_dsl/release.groovy now uses a `SLAVE_TYPE` of `container`, so we
need to ensure all jobs using job_dsl/release.groovy have the necessary
params set.
Issue: [RE-1612](https://rpc-openstack.atlassian.net/browse/RE-1612)

RE-1612 Add SLAVE params to premerge release test

---

CONTRIBUTING.md

Add a section to CONTRIBUTING.md regarding 'allowing edits' on personal fork/branches.
Issue: RE-154
Issue: [RE-154](https://rpc-openstack.atlassian.net/browse/RE-154)

add section about allowing edits on personal branch

---

pipeline_steps/common.groovy
rpc_jobs/params.yml
scripts/lint_support_groovy/ParametersAction.groovy
scripts/lint_support_groovy/StringParameterValue.groovy

`testRelease` is extended to enable it to discover any existing RELEASE_
or PM_ build that completed successfully for a particular SHA. RELEASE_
and PM_ jobs are treated as equivalent if they only differ by the prefix
(RELEASE_/PM_). If a build exists, the job does not need to be run
again.
To determine if a test was for a particular SHA the parameter
`_BUILD_SHA` is checked.
This change should, in general, reduce the time the release process
takes to complete, while allowing it to automatically resolve any
missing prerequisites.
JIRA: RE-1671
Issue: [RE-1671](https://rpc-openstack.atlassian.net/browse/RE-1671)

Skip release tests with existing successful builds

---

pipeline_steps/common.groovy
rpc_jobs/params.yml
scripts/lint_support_groovy/ParametersAction.groovy
scripts/lint_support_groovy/StringParameterValue.groovy

We're hitting some container build failures as a result of this change,
which may or may not be related to the `dir()` step used inside the
container.
Additional work needs to be done to validate that this is in fact the
issue and a further testing will need to be done on the proposed fix.
Reverts rcbops/rpc-gating#1005

Revert "Skip release tests with existing successful builds"

---

nodepool/files/nodepool.yml
rpc_jobs/rpc_openstack.yml

Now that nodepool can properly cater to providing OnMetal instances, we can switch these jobs over to use it. We also increase the minimum available nodes of this type to try to ensure that there's always one available, minimising test wait times.
Issue: [RE-1730](https://rpc-openstack.atlassian.net/browse/RE-1730)

Move rpc-openstack MNAIO jobs to use nodepool

---

rpc_jobs/rpc_upgrades.yml

Now that nodepool can properly cater to providing
OnMetal instances, we can switch these jobs over
to use it.
As per the issue, the team has agreed to go ahead
with this without pre-testing all the jobs.
Issue: [RE-1732](https://rpc-openstack.atlassian.net/browse/RE-1732)

Move upgrade MNAIO jobs to use nodepool

---

constraints_rpc_component.txt

Currently only alpha/beta pre-release tags are supported.
This patch updates the rpc_component SHA to include the
change of schema which allows rc pre-release tags so that
they can be used for releases.
The accepted form is the same as with alpha/beta tags, eg:
1.0.0-rc.1, 1.0.0-rc.2, etc.
Issue: [RE-1894](https://rpc-openstack.atlassian.net/browse/RE-1894)

Update rpc_component to allow RC tags

---

playbooks/tasks/artifact_upload/upload_file.yml

Cloud Files only supports file sizes up to 5GB [1]. Anything larger
must be segmented. When serving these files via the CDN address
they are still delivered as a single file, so segmentation provides
the advantage of a faster upload and downloads still work as one
would expect by delivering a single large file. This ensures that
we are able to upload large files (such as VM images) and consume
them.
[1] https://support.rackspace.com/how-to/cloud-files-uploading-large-files/
Issue: [RE-1561](https://rpc-openstack.atlassian.net/browse/RE-1561)

Segment large file artifacts when uploading them

---

playbooks/tasks/artifact_upload/upload_file.yml
rpc_jobs/unit/artefact_publish.yml

When no destination is provided, the set_fact fails to resolve
because the split function is still evaluated by Ansible at run
time. In this patch we do the following:
1. We switch to using a regex_replace filter instead, which
should only get evaluated if the dest is defined. The regex
will result in '/foo/bar' or 'foo/bar' returning 'foo'.
2. We add the configuration to the unit test to verify that
this works.
3. We resolve a bug where if the source was 'foo' and the dest
was 'bar/baz', the resulting upload would go into 'bar/baz/foo'
which is not what was intended. With the change in the task
which handles the move of content, it will now go into the
destination path 'bar/baz' as intended.
Issue: [RE-1901](https://rpc-openstack.atlassian.net/browse/RE-1901)

Resolve artifact upload error when no dest is specified

---

rpc_jobs/dummy_pipeline.yml

These components have been moved from mattt416 to rcbops.
Issue: [RE-1917](https://rpc-openstack.atlassian.net/browse/RE-1917)

RE-1917 Update test components' repo_url

---

pipeline_steps/github.groovy
rpc_jobs/standard_job_gate.yml
rpc_jobs/standard_job_release.yml
scripts/ghutils.py

This change seeks to make gate and release trigger builds fail early if
GitHub branch protection requirements are not met. This helps to protect
against builds with side effects failing on merge. Specifically,
Component-Gate-Trigger_ and Component-Release-Trigger will now fail if
either the required number of approvals have not been given or the
required checks have not passed.
The new function `github.is_pr_approved` allows for GitHub checks to be
excluded from the test so that, for example, a build triggered by a
required GitHub check can make use of the function even though it will
not yet be registered as succeeding by GitHub.
JIRA: RE-1630
Issue: [RE-1630](https://rpc-openstack.atlassian.net/browse/RE-1630)
Fails: https://rpc.jenkins.cit.rackspace.net/job/Component-Gate-Trigger_rpc-pr …

Ensure merge requirements met before gate/release

---

pipeline_steps/github.groovy
scripts/ghutils.py

This commit adds an argument to ghutils.py to allow posting to a GitHub
issue (or PR, both use issues under the hood). It also adds a groovy
function that uses this new ghutils.py functionality to add comments to
PRs specifically.
Issue: [RE-1624](https://rpc-openstack.atlassian.net/browse/RE-1624)

RE-1624 Add function to post to issue

---

rpc_jobs/rpc_ceph.yml

https://rpc-openstack.atlassian.net/browse/CEPHSTORA-373
Adding lint checks for rpc-ceph playbooks/*.y[a]ml files.
Will submit a separate PR for code changes in rpc-ceph repo.
Issue: [CEPHSTORA-373](https://rpc-openstack.atlassian.net/browse/CEPHSTORA-373)

enabling ansible lint checks for rpc-ceph

---

constraints.txt
lint.sh

This commit bumps cryptography as there are problems with the wheels
for the version we were using previously.
It also adds OS detection to the lint script and sets appropriate
vars so that c libs from homebrew can be located when building
wheels. This shouldn't affect builds in CI (due to the conditional) but
will enable developers to build venvs (and run lint) on local
macOS environments.
Issue: [RE-1923](https://rpc-openstack.atlassian.net/browse/RE-1923)

Cryptography version update

---

nodepool/files/nodepool.yml

Providing bionic nodepool instances will allow teams to migrate
to bionic when they are ready.
We can adjust the min-ready values as jobs migrate.
Adds Bionic:
* Cloud image for onmetal
* Disk image for vm instances
* Labels
* Pool entries
Issue: [RE-1925](https://rpc-openstack.atlassian.net/browse/RE-1925)

RE-1925 Add bionic instances to nodepool

---

rpc_jobs/rpc_gating.yml

rpc-gating does not currently make use of the component mechanisms,
disabling the comment prevents confusion given the suggested actions are
not available on the repository.
JIRA: RE-1624
Issue: [RE-1624](https://rpc-openstack.atlassian.net/browse/RE-1624)

Disable whisperer comment on rpc-gating

---

rpc_jobs/pull_request_whisperer.yml
rpc_jobs/releases.yml
rpc_jobs/standard_job_gate.yml
rpc_jobs/standard_job_release.yml

This change standardises the trigger phrase for the gate and release
process. :shipit: as a phrase is shorter and hopefully easier to
remember and also corresponds to an emoji that is commonly used on
GitHub to indicate approval of a change. By having one common phrase,
this should also reduce the impact of its use on developers.
JIRA: RE-1568
Issue: [RE-1568](https://rpc-openstack.atlassian.net/browse/RE-1568)

Update trigger phrase for gate and release

---

scripts/confluenceutils.py

When confluenceutils.py is creating or updating a release page, it
should create the month as a double digit, with a leading 0, if the
month is only a single figure. So we would get a release of 2018.09
instead of 2018.9
Issue: RE-1942
Issue: [RE-1942](https://rpc-openstack.atlassian.net/browse/RE-1942)

Ensure release page month is padded with a 0

---

rpc_jobs/pull_request_whisperer.yml

Adding the issue link is useful but not required, this change prevents
the build from failing because the user did not add an issue reference
to their commits.
JIRA: RE-1944
Issue: [RE-1944](https://rpc-openstack.atlassian.net/browse/RE-1944)

Skip failure to add issue link to pull request

---

rpc_jobs/hardening.yml
rpc_jobs/phobos.yml
rpc_jobs/rpc_openstack.yml

To prepare to remove the RC branches from RPC-O, we remove all jobs related to the branches. Some jobs remain, but are switched to using the mainline branch instead.
When the rocky jobs were created, the hardening job was mistakenly left out. We add it in this PR.
Issue: [RE-1739](https://rpc-openstack.atlassian.net/browse/RE-1739)

Remove all RPC-O RC branch jobs

---

pipeline_steps/common.groovy
rpc_jobs/releases.yml
rpc_jobs/standard_job_release.yml

Sometimes projects choose to release with failed tests. While this is
not ideal, to cater for this requirement, this pull request adds the
ability to skip code validation. Normally what happens is that if a
project has tests that have not been performed for the specified hash,
the release process will look to run those tests to ensure the code
works. With this change the status of any existing builds are ignored
and no new builds are started. All tests are skipped and the rest of the
release is completed as if the code was validated.
To skip validation a release should be triggered with the phrase
`:shipit: skip validation`.
JIRA: RE-1948
Issue: [RE-1948](https://rpc-openstack.atlassian.net/browse/RE-1948)
Tested with and without skipping:
https://github.com/rcbops/releases/pull/71 …

Enable releasing with failed tests

---

webhooktranslator/setup.py

The version of flask used in webhooktranslator is vulnerable
to a denial of service attack (CVE-2018-1000656).
This commit bumps flask to the oldest non-vulnerable version.
Issue: [RE-1906](https://rpc-openstack.atlassian.net/browse/RE-1906)

RE-1906 Bump flask version

---

constraints_rpc_component.txt
pipeline_steps/common.groovy

This change triggers any component that is dependent on a project to be
(dep) updated immediately after the project is released instead of
relying solely on a weekly dep update.  In this configuration, the third
party dependencies are not updated.  The dependent search is performed
via modifications also made in the component tool (rpc_component)
JIRA: RE-1599
Issue: [RE-1599](https://rpc-openstack.atlassian.net/browse/RE-1599)

RE-1599 Add dep update for dependents after release

---

Dockerfile.standard_job
job_dsl/release.groovy
rpc_jobs/standard_job_premerge_release.yml

component_metadata.yml can include information related to dependencies
and artefacts. To ensure this file is valid this change updates the
release pre-merge job, which is automatically added to new components,
to also test component metadata to ensure it is always in a valid
format.
The Docker file updated is used by the release job, python3 is installed
to support the component CLI tool.
[Success](https://rpc.jenkins.cit.rackspace.net/job/RE-Release-PR_rpc-product-1-master/2/console)
[Failure](https://rpc.jenkins.cit.rackspace.net/job/RE-Release-PR_rpc-product-1-master/6/console)
JIRA: RE-1811
Issue: [RE-1811](https://rpc-openstack.atlassian.net/browse/RE-1811)

Add component metadata file validation

---

rpc_jobs/releases.yml
rpc_jobs/standard_job_premerge.yml
rpc_jobs/standard_job_release.yml

To improve the clarity of the information provided by whisperer in
rcbops/releases this change:
- updates the status context prefix used by the check job to be prefixed
with `check` to make it easier to reference by whisperer
- removes the use of CIT from the status context for the release job
- modifies the whisperer comment body to better explain and reference
the check and release jobs.
JIRA RE-1945
Issue: [RE-1945](https://rpc-openstack.atlassian.net/browse/RE-1945)

Update releases jobs to give clearer information

---

pipeline_steps/common.groovy

The prefix common. should not be used to call common functions from within
common.
Issue: [RE-1494](https://rpc-openstack.atlassian.net/browse/RE-1494)

RE-1494 Fix recordAbortDueToMaintenance

---

nodepool/files/nodepool.yml
rpc_jobs/rpc_maas.yml

This commit enabled phobos as a nodepool region for labels
that aren't used by RPC-MaaS jobs. MaaS jobs are incompatible
with phobos as they expected MaaS entities to be pre-created
for the node that they run on.
This commit also adds bionic nodes to phobos and adds ubuntu-bionic
to the disk images config that was missing previously.
Issue: [RE-1954](https://rpc-openstack.atlassian.net/browse/RE-1954)

RE-1954 RE-Enable Phobos nodepool region

---

rpc_jobs/rpc_openstack.yml

In order to prepare for using the MNAIO images, we need to
switch to using bionic hosts. They're required to support
the use of the later virt-tools which perform the magic
in the images prior to booting the VM's to ensure that they
work when starting up without having to run any extra
playbooks.
JIRA: RE-1562
Issue: [RE-1562](https://rpc-openstack.atlassian.net/browse/RE-1562)

Switch to using bionic hosts for RPC-O MNAIO master jobs

---

rpc_jobs/build_summary.yml
rpc_jobs/periodic_cleanup.yml
scripts/extract_dsl.py
scripts/lint_jjb.py

Two timer triggers were added to some jobs in order to avoid
the maintenance window. However only one makes it into the
Jenkins configuration. This commit switches from two timer
triggers to a single timer trigger that contains two cron
expressions.
Issue: [RE-1976](https://rpc-openstack.atlassian.net/browse/RE-1976)

RE-1976 Fix dual schedules

---

rpc_jobs/rpc_appformix.yml

The repo is private, so to allow jenkins to authenticate via
its key we need to use the URL git@github.com:rcbops/rpc-appformix
instead.
Issue: [RE-1985](https://rpc-openstack.atlassian.net/browse/RE-1985)

Switch rpc-appformix repo URL to use git@

---

rpc_jobs/rpc_appformix.yml

The Appformix PM jobs are failing because the name of
the axis is incorrect. It is 'deploy' instead of
'functional', and there is no tox env for 'deploy'.
Issue: [RE-1985](https://rpc-openstack.atlassian.net/browse/RE-1985)

Correct Appformix action axis name

---

playbooks/allocate_pubcloud.yml

- Updated cloud region logic: if there is only one item in the region list, use it - even if it's in the first list, otherwise remove previously attempted region
JIRA: RE-1987
Issue: [RE-1987](https://rpc-openstack.atlassian.net/browse/RE-1987)

Allow Single Region to be in both Primary and Fallback

---

pipeline_steps/common.groovy

This process needs improvement and the abort line should
be removed so that jobs can continue. This will be reenabled
after making improvements such as allowing a maitnenance to
end early.
Issue: [RE-1965](https://rpc-openstack.atlassian.net/browse/RE-1965)

RE-1965 Disable Maintenance aborts

---

rpc_jobs/rpc_appformix.yml

Without the whisperer, no PR's can be rechecked and none
of the helper comments are added to PR's.
Issue: [RE-1985](https://rpc-openstack.atlassian.net/browse/RE-1985)

Add the whisperer job to rpc-appformix

---

Dockerfile.standard_job
pipeline_steps/common.groovy
rpc_jobs/unit/artefact_publish.yml
rpc_jobs/unit/re_unit_tests.yml
rpc_jobs/unit/single_use_slave.yml

After extracting the venv on a target host, the python version
on the host may be different enough to cause the scripts used
in the venv to fail. This patch ensures that the python version
in the venv is replaced with whatever is on the host at runtime.
Resetting python in the venv cannot be done by simply doing a
python binary copy - it results in a broken venv which is missing
some of the standard libraries. Due to that, we need to use the
'virtualenv' tool for the reset. Given the range of options
available over time, we have to do a fair amount of logic to
figure out the options available to use.
To help prove that this works, unit tests are added for the
following:
1. Get a nodepool bionic node.
2. Publish artifacts using a xenial container (instead of using
the long-lived slave), …

Reset python in rpc-gating venv at run time

---

Dockerfile.standard_job

It seems that tests using the container image commonly use pip
and sudo, so we need to include it in the base dockerfile.
JIRA: RE-1977
Issue: [RE-1977](https://rpc-openstack.atlassian.net/browse/RE-1977)

Include sudo/pip in container image

---

nodepool/files/nodepool.yml
pipeline_steps/common.groovy
playbooks/allocate_pubcloud.yml
rpc_jobs/bump_snapshots.yml

nodepool.yml is updated to support three new types of node. Replicating
how the snapshots are currently used, each node type is flavour 7. The
nodes are labelled based on the major series to which they belong and
not the specific version, this simplifies the management of the
configuration but does mean if a project requires use of a specific
version it will need to be done manually.
bump_snapshots.yml has been updated so that Nodepool is automatically
updated when new snapshots become available.
JIRA: RE-1465
Issue: [RE-1465](https://rpc-openstack.atlassian.net/browse/RE-1465)

Add RPCO snapshot support to Nodepool

---

pipeline_steps/common.groovy

When using the Groovy File class, the thaw file does not get found. This
can switches to using Bash.
JIRA: RE-1465
Issue: [RE-1465](https://rpc-openstack.atlassian.net/browse/RE-1465)

Fix thaw file detection

---

grafana/grafyaml/dashboard-nodepool.yaml

Some of the graphs in Grafana appear to have aggregation and/or sparse
data, making the plots very difficult to understand.  After examining
the Graphite data and also comparing with the Openstack nodepool data,
our data/graphs appears to be correct but the panel configurations need
to be adjusted.
JIRA: RE-1522
Issue: [RE-1522](https://rpc-openstack.atlassian.net/browse/RE-1522)

RE-1522 Modify Grafana graphs that may have aggregation

---

Dockerfile.standard_job

Some tests are using options that are only available in more
recent versions of pip than are available in the distro package.
Issue: [RE-1977](https://rpc-openstack.atlassian.net/browse/RE-1977)

Upgrade pip in the base container image

---

pipeline_steps/common.groovy

To ensure that standard jobs are able to recognise whether the run
stage passed/failed, we export a new environment variable before
running the post script. This makes it possible to adjust the post
script to skip the artifact configuration which causes broken images
to get uploaded after the job.
Issue: [RE-1989](https://rpc-openstack.atlassian.net/browse/RE-1989)

Expose the build result to the post stage

---

nodepool/files/nodepool.yml

Our current max-age for nodepool nodes for most labels
is 1 hour. This was initially implemented during the
testing phase for nodepool to ensure that changes in
the image were implemented quickly. However, the images
are now largely stable, so all it's doing now is causing
unnecessary churn.
This patch changes the max-age to 1 day to reduce churn.
The snapshot images are not yet being used by any jobs,
but consuming a large amount of quota. Even when they
do start getting used, the frequency of their usage is
quite low, so a min-ready setting of 1 should be fine.
To ensure that our VM usage for DFW does not exceed our
actual quota of 512GB RAM, we also change the max-servers
for the two pools to ensure that neither can ever use more
than half of it. We set ORD to max-server 30 to match …

Reduce max-age for nodepool nodes to reduce churn

---

grafana/grafyaml/dashboard-nodepool.yaml

Some of the Grafana graphs show inaccurate data points if the graph
is zoomed out, or the time range is larger than about 6-12 hours.
For more an example, see the notes file attached to the RE-1980 card.
This task attempts to resolve the time range issue and includes a
minor adjustment to fix the units (scale) in the "Time to Ready" panel.
Ref: https://github.com/rcbops/rpc-gating/blob/master/CONTRIBUTING.md
JIRA: RE-1980
Issue: [RE-1980](https://rpc-openstack.atlassian.net/browse/RE-1980)

RE-1980 Fix the Grafana time range issue

---

nodepool/files/nodepool.yml

The public cloud DFW region is exclusively used for snapshot
builds and snapshot consumption, both of which currently use
jenkins (not nodepool). In the 2018.10 release we'll be migrating
the snapshot consumption to use nodepool, so that will help us to
remain within a quota - but jenkins does not have quota awareness,
so we have the snapshot creation jobs failing unless we provide
some headroom for jenkins to use.
In this patch we do the following:
1. Reduce the DFW nodepool quota to ensure that there is headroom
for jenkins.
2. Reduce the min-ready for ubuntu-xenial-g1-8 and ubuntu-bionic-g1-8
because it seems that they are underutilised with the current
setting. With min-ready at 1, there will be one available in each
region which should be more than enough.
3. Reduce the min-ready for …

Adjust nodepool settings to give more headroom to DFW

---

pipeline_steps/common.groovy
rpc_jobs/re_maintenance_window.yml

The first RE maintenance window occurred on 2018-09-24, and there were some
teething problems:
* Builds aborted due to the maintenance window had result set to
SUCCESS instead of ABORTED.
* Schedule was incorrect for the maintenance start job
* Maintenance start job was aborted as it overlapped the maintenance
window
* Maintenance start job failed on missing common. prefix for lib func.
* Maintenance was completed quickly but there was no mechanism for
resuming jobs before the end of the predefined window.
All these issues are fixed by this commit.
e5adbe0 (Hugh Saunders, 23 hours ago)
Revert "RE-1965 Disable Maintenance aborts"
This reverts commit 0b3748ac576a5a89f3f9fc17d17457192ef33cde. Maintenance
aborts were disabled temporarily while bugs are fixed This pr fixes the
bugs and …

RE-1965 Maintenance Process Improvements

---

job_dsl/release.groovy

The metadata verification step was added by
bec68cab3f994280a2109a1f29df3d1397df0d1a for use by
'RE-Release-PR_{repo}-{BRANCH}' jobs however because this code is also
shared by 'RE-Release' it is causing failures when releasing components.
This change ensures the verification is only performed on a pull
request.
JIRA: RE-2033
Issue: [RE-2033](https://rpc-openstack.atlassian.net/browse/RE-2033)

Fix release job so it skips metadata verification

---

rpc_jobs/osp_mnaio.yml
rpc_jobs/rpc_upgrades.yml

Assuming we have enough Bionic nodes in the queue, I'd like to move from Xenial to Bionic for rpc-upgrades and osp-mnaio builds.
Issue: [RI-498](https://rpc-openstack.atlassian.net/browse/RI-498)

RI-498 Upgrade rpc-upgrades/osp-mnaio hypervisor to Bionic

---

rpc_jobs/rpc_openstack.yml

The PR jobs have been using nodepool for some time. We can
now switch the PM jobs too. The region and flavor settings
are removed as they're not used by nodepool.
Confirmed to be working as normal via:
https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-openstack-newton-xenial-swift-deploy/475/
https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-openstack-newton-trusty-swift-deploy/427/
Issue: [RE-1586](https://rpc-openstack.atlassian.net/browse/RE-1586)
Issue: [RE-1587](https://rpc-openstack.atlassian.net/browse/RE-1587)

Move RPC-O strict artifact builds to using nodepool

---

rpc_jobs/rpc_upgrades.yml

Use version snapshots to avoid inital deploy and
just focus on upgrading.
Issue: [RI-499](https://rpc-openstack.atlassian.net/browse/RI-499)

RI-499 Use snapshots on incremental upgrades

---

rpc_jobs/rpc_designate.yml

Nodepool now provides nodes based on the most recent
snapshot image of a working RPC-O deployment. With
this implemented, we can switch the designate jobs
over to using them.
Testing:
https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-designate-master-xenial_snapshot-newton-deploy/227/
https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-designate-master-xenial_snapshot-pike-deploy/229/
https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-designate-master-xenial_snapshot-queens-deploy/168/
Issue: [RE-1592](https://rpc-openstack.atlassian.net/browse/RE-1592)
Issue: [RE-1593](https://rpc-openstack.atlassian.net/browse/RE-1593)

Move rpc-designate snapshot jobs to use nodepool

---

rpc_jobs/rpc_octavia.yml

Nodepool now provides nodes based on the most recent
snapshot image of a working RPC-O deployment. With
this implemented, we can switch the octavia jobs
over to using them.
Testing:
https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-octavia-master-xenial_snapshot-functional-test/37/
https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-octavia-pike-xenial_snapshot-functional-test/23/
Issue: [RE-1594](https://rpc-openstack.atlassian.net/browse/RE-1594)
Issue: [RE-1595](https://rpc-openstack.atlassian.net/browse/RE-1595)

Move rpc-octavia snapshot jobs to use nodepool

---

rpc_jobs/rpc_upgrades.yml

The PR jobs have been using nodepool for some time. We can
now switch the PM jobs too. The region and flavor settings
are removed as they're not used by nodepool.
Issue: [RE-1589](https://rpc-openstack.atlassian.net/browse/RE-1589)
Issue: [RE-1591](https://rpc-openstack.atlassian.net/browse/RE-1591)

Move rpc-upgrades to using nodepool

---

Dockerfile.standard_job

virtualenv calls python3 at times, so some wheels need python3-dev

install python3 packages

---

rpc_jobs/rpc_appformix.yml

Nodepool now provides nodes based on the most recent
snapshot image of a working RPC-O deployment. With
this implemented, we can switch the appformix jobs
over to using them.
Issue: [RE-2050](https://rpc-openstack.atlassian.net/browse/RE-2050)

Move rpc-appformix snapshot jobs to use nodepool

---

rpc_jobs/rpc_upgrades.yml

Jobs have never been successful as deployment of the older
versions is broken so removing them as to not eat up
unnecessary resources.

Dropping rpc-upgrades Kilo version jobs

---

rpc_jobs/rpc_openstack.yml

In order to prepare for using the MNAIO images, we need to
switch to using bionic hosts. They're required to support
the use of the later virt-tools which perform the magic
in the images prior to booting the VM's to ensure that they
work when starting up without having to run any extra
playbooks.
Issue: [RE-1998](https://rpc-openstack.atlassian.net/browse/RE-1998)

Switch to using bionic hosts for RPC-O MNAIO pike jobs

---

rpc_jobs/rpc_openstack.yml

In recent PR's the MNAIO host was switched to using bionic, but
the same was not done for the release and the ASC experimental
job. This patch ensures those jobs are also switched over.
Issue: [RE-1562](https://rpc-openstack.atlassian.net/browse/RE-1562)
Issue: [RE-1996](https://rpc-openstack.atlassian.net/browse/RE-1996)
Issue: [RE-1997](https://rpc-openstack.atlassian.net/browse/RE-1997)
Issue: [RE-1998](https://rpc-openstack.atlassian.net/browse/RE-1998)

Switch release/experimental MNAIO jobs to use bionic hosts

---

rpc_jobs/rpc_maas.yml

- Changed the periodic MaaS Post Merge deploy scenarios for queens, pike, newton, and ceph running on xenial from weekly to daily.
JIRA: RE-2054
Issue: [RE-2054](https://rpc-openstack.atlassian.net/browse/RE-2054)

Change PM MaaS Queens Deploy Job to Run Daily

---

rpc_jobs/rpc_maas.yml

- Changed the periodic MaaS Post Merge deploy scenarios for newton running on trusty from weekly to daily.
JIRA: RE-2054
Issue: [RE-2054](https://rpc-openstack.atlassian.net/browse/RE-2054)

Change PM MaaS Newton Deploy Job to Run Daily

---

pipeline_steps/common.groovy

In standard_job_slave we call use_node for all node types apart from
containers. This means that install_ansible is not run on containers,
which means the rpc-gating venv is not adjusted for the current os.
This commit adds a call to install_ansible within each container before
its used.
Issue: [RE-2064](https://rpc-openstack.atlassian.net/browse/RE-2064)

RE-2064 Run install_ansible in containers

---

pipeline_steps/webhooks.groovy

Currently the webhookproxy only starts automatically in runlevel 2,
which means on a reboot into runlevel 3 it is not started.
This commit alters the upstart config that gets generated by our groovy
to start the webhookproxy in runlevels 2,3,4 and 5
Issue: RE-2062
Issue: [RE-2062](https://rpc-openstack.atlassian.net/browse/RE-2062)

ensure webhook starts in runlevels 2345

---

rpc_jobs/rpc_openstack.yml

This commit removes the specialized naming convention for the images
used for the asc staging job. The non-standard name prevents the images
cached in the CDN from being detected.
In order to allow the job to remain discrete from the production system
testing job, the action is renamed to 'system_staging'.
Issue: [ASC-1042](https://rpc-openstack.atlassian.net/browse/ASC-1042)

ASC-1042 Rename asc staging image

---

rpc_jobs/rpc_openstack.yml

The 'ironic' scenario in RPC-O does not do anything different
to the 'deploy' scenario. This means that CI resources are being
wasted on executing them. This PR removes the ironic jobs so that
this no longer happens.
Also, in order to prepare for using the MNAIO images, we need to
switch to using bionic hosts. They're required to support
the use of the later virt-tools which perform the magic
in the images prior to booting the VM's to ensure that they
work when starting up without having to run any extra
playbooks.
Issue: [RI-513](https://rpc-openstack.atlassian.net/browse/RI-513)
Issue: [RE-2030](https://rpc-openstack.atlassian.net/browse/RE-2030)

Remove 'ironic' RPC-O jobs and switch newton MNAIO to bionic hosts

---

nodepool/files/elements/jenkins-slave/install.d/20-jenkins-slave

Bionic images are failing to resolve DNS because glean
is not implementing any systemd-resolved configuration
to make it work. This results in the system initially
working OK, but failing if any changes are made to the
networking configuration which causes systemd-resolved
to restart (replacing the content of /etc/resolve.conf
which glean put there).
While this is currently only showing up in RPC-O tests,
the issue would happen on any nodepool nodes which make
adjustments to the network config. Given that we use
glean as part of the nodepool node setup, we need to do
this here to prevent test failures rather than expect
test implementations to do it.
We disable this on any image which is not trusty/xenial
so that this will happen for any images bionic onwards.
Issue: …

Disable systemd-resolved in bionic+ images

---

nodepool/files/elements/jenkins-slave/install.d/20-jenkins-slave

systemd-resolved adds a symlink which glean does not
seem to replace on boot. To ensure that the boot can
complete, and the image build is unaffected by this
change, we replace /etc/resolv.conf with a normal
file and a public resolver.
Glean fails with the symlink in place with:
```
Oct 12 15:55:59 nodepool-ubuntu-bionic-g1-8-pubcloud-dfw-0000116762 glean.sh[417]: Traceback (most recent call last):
Oct 12 15:55:59 nodepool-ubuntu-bionic-g1-8-pubcloud-dfw-0000116762 glean.sh[417]:   File "/usr/local/bin/glean", line 11, in <module>
Oct 12 15:55:59 nodepool-ubuntu-bionic-g1-8-pubcloud-dfw-0000116762 glean.sh[417]:     sys.exit(main())
Oct 12 15:55:59 nodepool-ubuntu-bionic-g1-8-pubcloud-dfw-0000116762 glean.sh[417]:   File "/usr/local/lib/python2.7/dist-packages/glean/cmd.
py", line 1481, …
```

Replace the systemd-resolved symlink

---

nodepool/files/elements/jenkins-slave/install.d/20-jenkins-slave

In Ubuntu Bionic onwards, systemd-resolved is enabled by
default.
We have glean to setup the interfaces and the resolvers
from config-drive. Ideally we'd like glean to configure
systemd-resolved properly, but it can't do that right
now.
We've tried the following:
1. Disabling systemd-resolved. This causes other services
which are set to depend on it not to start, so the VM
never boots.
2. Using resolvconf. This has the same problem as glean -
systemd-resolved keeps changing the config to something
broken.
So, as a workaround, we implement a static config here with
public DNS servers.
Issue: [RI-514](https://rpc-openstack.atlassian.net/browse/RI-514)

Configure systemd-resolved on bionic+ images

---

nodepool/files/elements/jenkins-slave/install.d/20-jenkins-slave

In https://github.com/rcbops/rpc-gating/pull/1135 we configured
systemd-resolved in nodepool bionic images to ensure that they
are able to resolve DNS until glean is fixed to configured the
systemd-networkd interfaces with DNS as well.
To ensure that the glean configuration will take preference when
a fix is included in the release, we switch the DNS configuration
here to be a fallback only. Any systemd-networkd will then take
preference, but fall back to this configuration if that does not
work.
Issue: [RI-514](https://rpc-openstack.atlassian.net/browse/RI-514)

Only configure fallback DNS for systemd-resolved

---

rpc_jobs/rpc_openstack.yml

In order to test the ELK add-on for RPC-O, we add an
extra 'action' which executes that option using the
MNAIO images. This also ensures that the 'deploy'
action remains focused on the base RPC-O deployment
without any extras.
The 'action' axis components are all re-ordered into
alphabetical order for easier maintenance.
Issue: [RI-263](https://rpc-openstack.atlassian.net/browse/RI-263)

Add 'elk' action to RPC-O MNAIO tests

---

rpc_jobs/hardening.yml

In order to ensure that the hardening tests make use of
MNAIO images rather than do the deployment from scratch,
we rename the 'action' to 'hardening' rather than 'deploy'.
We also update the nodepool node to use bionic.
Finally we change the 'image' axis to be 'xenial_mnaio'
for pike, queens rocky and master rather than make mention
of 'loose_artifacts' given that these RPC-O branches do not
have any notion of artifacts. We restrict that naming to
only newton. We also add bionic VM tests for rocky and
master.
Issue: [RE-2053](https://rpc-openstack.atlassian.net/browse/RE-2053)

Update hardening tests to use MNAIO images

---

rpc_jobs/hardening.yml

To allow the hardening jobs to simply use the RPc-O MNAIO
images, the 'image' axis names need to match. This patch
ensures that is the case.
Issue: [RE-2053](https://rpc-openstack.atlassian.net/browse/RE-2053)

Ensure hardening job image names match RPC-O jobs

---

pipeline_steps/common.groovy
rpc_jobs/standard_job_postmerge.yml

This change fixes some issues with the implementation of the
functionality to hold Nodepool nodes:
- ensures a node is not held if `env.HOLD_ON_ERROR` is unset.
- ensures a post-merge project can override the default value.
JIRA: RE-2016
Issue: [RE-2016](https://rpc-openstack.atlassian.net/browse/RE-2016)
[Failure when HOLD_ON_ERROR unset](https://rpc.jenkins.cit.rackspace.net/job/scratchpipeline/1206/console)
[Failure when HOLD_ON_ERROR set](https://rpc.jenkins.cit.rackspace.net/job/scratchpipeline/1207/console)

Fix Nodepool holding

---

rpc_jobs/rpc_ceph.yml

There are several PM tests missing for rpc-ceph. These are
important to ensure that it is continuously tested in case
there is bitrot. It is also useful when diagnosing PR
failures to determine if the issue is PR-specific or not.
Issue: [RE-2087](https://rpc-openstack.atlassian.net/browse/RE-2087)

Add missing PM tests for rpc-ceph

---

scripts/CIT_JM_Docker/Dockerfile
scripts/CIT_JM_Docker/README.md

This dockerfile is for producing an environment that is very
similar to the running Jenkins master.
Useful for testing upgrades, reproducing errors etc.
Issue: [RE-1971](https://rpc-openstack.atlassian.net/browse/RE-1971)

RE-1971 Add CIT Jenkins docker env

---

scripts/commit_and_pull_request.sh

If the branch already exists, the `git push` command fails. This change
forces the push to ensure that the script can always update an existing
pull request.
JIRA: RE-2100
Issue: [RE-2100](https://rpc-openstack.atlassian.net/browse/RE-2100)

Allow commit_and_pull_request.sh to update branch

---

pipeline_steps/common.groovy

When we release a node, we clean the workspace by calling
deleteDir from common.use_node. If the node has gone offline
for any reason, that deleteDir will fail. If the node wen't offline
during the post phase, we don't want its disapperance to fail the
build so we enclose deleteDir in try/catch.
Issue: [RE-2087](https://rpc-openstack.atlassian.net/browse/RE-2087)

RE-2087 Catch workspace cleanup failures

---

grafana/grafyaml/dashboard-nodepool.yaml
nodepool/templates/nodepool.yml.j2

In order to verify the capability to use Ironic nodes
in Phobos, we add a new set of labels for them. Once
it's verified that they work we can add them to the
general pool of ubuntu-*-om-io2 nodes.
To provide visibility into what's happening in Phobos
we add the appropriate dashboard configuration.
To accommodate the new graph on the bottom row we
reduce the span size to ensure it still fits in.
Issue: [RE-2051](https://rpc-openstack.atlassian.net/browse/RE-2051)

Add test node set for phobos ironic nodes and add Phobos into Grafana

---

nodepool/templates/nodepool.yml.j2
rpc_jobs/rpc_openstack.yml

This reverts commit 3ec27fb.
Releases are now been processed and the resource crisis
is over, so we can revert this change.
A duplicated cloud image was put into the configuration
for Phobos, but it was supposed to be two different
images. This corrects the mistake.
Issue: [RE-2051](https://rpc-openstack.atlassian.net/browse/RE-2051)

Revert job frequency and correct nodepool config error

---

nodepool/templates/nodepool.yml.j2

The previously used name was for VM's, not ironic
nodes. This corrects it to the right name.
Issue: [RE-2152](https://rpc-openstack.atlassian.net/browse/RE-2152)

Correct Phobos ironic network name

---

pipeline_steps/common.groovy

Previously, there was no check for the status of the maintenance ticket,
so builds were still aborted even when the ticket was progressed
past doing. This commit adds a check so that once a maintenance
ticket is moved past doing it won't count towards future mainteanances.
Issue: [RE-2085](https://rpc-openstack.atlassian.net/browse/RE-2085)

RE-2085 Fix PR aborts post maintenance

---

pipeline_steps/common.groovy

A prefix match is used to determine which jobs can run during
a maintenance window. One of the existing prefixes is
RE-unit-test, which was designed to cover all the unit tests,
however the constraints leak job name starts RE-unit-venv.
This commit reduces the prefix match to RE-unit to ensure that the
constraints leak job is allowed.
Issue: [RE-2083](https://rpc-openstack.atlassian.net/browse/RE-2083)

RE-2083 Allow constraints leak test during maint

---

rpc_jobs/re_maintenance_window.yml

Quiet down is moved to the end of the pipeline as nothing
can execute once quiet down is enabled.
Issue: [RE-2082](https://rpc-openstack.atlassian.net/browse/RE-2082)

RE-2082 Reorder maint start job

---

rpc_jobs/rpc_upgrades.yml

Captures MNAIO environment after the initial deployment of a
version has ran.  Leverages the workarounds to install an older
version so that we can create a library of older versions and
focus on just testing upgrades rather than deployment of an older
verision.
Uses snapcap as the action which skips the upgrade part of
the job and captures the image on success. Testing out with one
image to see how it works.  
The upgrade_to is ignored but the format is left as is to avoid making a lot of changes to the existing process.
Relies on https://github.com/rcbops/rpc-upgrades/pull/276

Adds temporary job to capture older versions

---

nodepool/templates/nodepool.yml.j2

Now that we've verified that the Phobos ironic nodes are
usable in the same way as the public cloud OnMetal nodes,
we can add them to the same label.
Issue: [RE-2152](https://rpc-openstack.atlassian.net/browse/RE-2152)

Use Phobos ironic nodes for MNAIO tests

---

pipeline_steps/common.groovy

At the end of a maintenance the mainteance-end job attempts to recheck
all PR builds that were aborted due to the maintenance. This process
fails if any non-pr builds are reported, as the PR related fields are
null.
This PR ensures that non-pr failures are safely skipped when rechecking
PRs after a maintenance.
Issue: [RE-2061](https://rpc-openstack.atlassian.net/browse/RE-2061)

RE-2061 Ignore non pr failures on maint tickets

---

nodepool/templates/nodepool.yml.j2

As agreed with our public cloud friends, we reduce the
OnMetal max-servers for the LON region down to 5 now that
we have Phobos ironic nodes online.
Issue: [RE-2152](https://rpc-openstack.atlassian.net/browse/RE-2152)

Reduce LON region OnMetal max-servers to 5

---

rpc_jobs/rpc_upgrades.yml

Adds older versions of jobs we need to capture for
testing, set at a monthly cadence but really can
be removed once the image has been captured.
Also adds an initial testing job for the image we've
captured already.

Adds jobs to capture older versions of RPC-O

---

pipeline_steps/common.groovy
scripts/jirautils.py

Jira processes string search terms including translating underscores
to spaces. To prevent this, much quoting is required.
Issue: [RE-2000](https://rpc-openstack.atlassian.net/browse/RE-2000)

RE-2000 Quote JQL terms that may contain - or _

---

job_dsl/standard_job_checkmarx.groovy
rpc_jobs/mk8s.yml

This allows keys to be used to access private repos.
Also set thresholds to 0 not 1, so that any vulnerability causes a scan to fail. 
Issue: [RE-2184](https://rpc-openstack.atlassian.net/browse/RE-2184)

RE-2184 Switch MK8s Checkmarx jobs to ssh clones

---

gating/check/run
gating/common/run_standard_job_pre_merge.py
rpc_jobs/standard_job_premerge.yml

RE_JOB_NAME currently binds to the name of the JJB project and not the
name of the job. To enable this to be correct, this change adds the new
variable RE_JOB_PROJECT_NAME to allow existing uses of RE_JOB_NAME to be
switched to using RE_JOB_PROJECT_NAME before updating RE_JOB_NAME to the
correct value.
This change adds a new pre-merge test job for rpc-gating to test that
the `RE_JOB_.*` environment variables are defined as expected.
Issue: [RE-2031](https://rpc-openstack.atlassian.net/browse/RE-2031)

Add RE_JOB_PROJECT_NAME environment variable

---

job_dsl/standard_job_checkmarx.groovy
pipeline_steps/checkmarx.groovy
rpc_jobs/standard_job_checkmarx.yml

This commit moves the defaults and scan call out of the standard
Checkmarx job into a library function that can be used in any job.
This will allow teams such as MK8s to intergrate Checkmarx scans
with their existing pipelines.
Issue: [RE-2184](https://rpc-openstack.atlassian.net/browse/RE-2184)

RE-2184 Make Checkmarx consumable from pipelines

---

nodepool/templates/nodepool.yml.j2
rpc_jobs/rpc_maas.yml

rpc-maas is now able to test the API on Phobos and so it is no longer
necessary to provide separate nodes to cater for its needs. This change
removes the node definitions and updates the projects using them to
instead use the original versions.
JIRA: RE-1782
Issue: [RE-1782](https://rpc-openstack.atlassian.net/browse/RE-1782)

Remove MaaS Nodepool node types

---

rpc_jobs/jjb_setup.yml

Jenkins-Job-Builder was changed to Jenkins-Job-Builder-master, because
the job was changed to a template however the name to not need to be
parameterised for it to work. Changing this back because the name change
broke the merge trigger job and is unnecessary.
JIRA: RE-2069
Issue: [RE-2069](https://rpc-openstack.atlassian.net/browse/RE-2069)

Fix Jenkins-Job-Builder name

---

rpc_jobs/rpc_openstack.yml

Marked out known false alarm and changed the rule based on
master check. Adding rocky check.
Issue: [RI-547](https://rpc-openstack.atlassian.net/browse/RI-547)

RI-547 RPC-Openstack rocky checkmarx

---

rpc_jobs/osp_mnaio.yml

This commit adds the `osp_13_deploy-system` action to the OSP daily jobs
in order to create a job that runs the tests in
https://github.com/rcbops/rpc-openstack-system-tests/tree/osp13
Issue: [ASC-801](https://rpc-openstack.atlassian.net/browse/ASC-801)

ASC-801 Add OSP system-tests job

---

rpc_jobs/periodic_cleanup.yml

Periodic cleanup is temporarily disabled to ensure that logs aren't
compressed while we are running a version of workflow-job that
prevents the jenkins ui from rendering compressed logs.
See Jira for details.
Issue: [RE-2215](https://rpc-openstack.atlassian.net/browse/RE-2215)

RE-2215 Disable periodic cleanup

---

pipeline_steps/common.groovy
rpc_jobs/periodic_cleanup.yml

The workflow-job plugin has now been downgraded to 2.25 and the UI is rendering compressed logs. Its now safe to re-enable periodic cleanup. 
Reverts rcbops/rpc-gating#1203
Jira: RE-2215
Issue: [RE-2215](https://rpc-openstack.atlassian.net/browse/RE-2215)

Revert "RE-2215 Disable periodic cleanup"

---

gating/common/run_standard_job_pre_merge.py
rpc_jobs/standard_job_checkmarx.yml
rpc_jobs/standard_job_dep_update.yml
rpc_jobs/standard_job_gate.yml
rpc_jobs/standard_job_lint_jenkins.yml
rpc_jobs/standard_job_postmerge.yml
rpc_jobs/standard_job_premerge.yml
rpc_jobs/standard_job_release.yml

This change fixes RE_JOB_NAME to ensure it is bound to the name of the
job and not the name of the project. The job name does not appear to be
available when using jenkins-jobs and so this change makes use of the
environment variable JOB_NAME to set RE_JOB_NAME to the correct value.
JIRA: RE-2031
Issue: [RE-2031](https://rpc-openstack.atlassian.net/browse/RE-2031)

Fix RE_JOB_NAME value

---

rpc_jobs/rpc_uam.yml

rpc-uam is added to RE jobs to run checkmarx
against the repository code

Adding RE job for RPC-UAM

---

rpc_jobs/rpc_upgrades.yml

Adds limits to avoid running job when not required on changes
to leapfrog scripts (/scripts/) and limits leapfrog PR jobs
from running on incrementals (/incremental).

Add PR job for testing mnaio incremental builds

---

job_dsl/rpc_artifact_build.groovy
pipeline_steps/common.groovy

Commenting on the status of pull request builds was not deemed to be
useful by teams, it simply created noise. This change removes the rest
of the code related to safe_jira_comment.
JIRA: RE-1124
Issue: [RE-1124](https://rpc-openstack.atlassian.net/browse/RE-1124)

Remove safe_jira_comment

---

rpc_jobs/rpc_octavia.yml

Per the comments in issue RI-520 we are removing the Pike PM job for 
Octavia as we do not deploy Octavia on Pike.
Issue: [RI-520](https://rpc-openstack.atlassian.net/browse/RI-520)

[RI-520] Remove Pike Octavia PM Job

---

pipeline_steps/common.groovy

We've had some jobs fail on git configuration because git can't
lock its own config files to modify them. This commit adds a lock
to ensure jenkins is only trying to configure git in one build at
a time. It also adds sleep+retry incase its a non-jenkins process
thats got the git config locked.
Issue: [RE-2231](https://rpc-openstack.atlassian.net/browse/RE-2231)

RE-2231 Mitigate git config races

---

scripts/confluence_release_page.j2

Previously only the release notes column was run through the
urlize filter, this meant that a stray ampersand could make it into
the comments filter, and cause confluence to return 400.
Issue: [RE-2238](https://rpc-openstack.atlassian.net/browse/RE-2238)

RE-2238 Fix confluence wiki page update

---

rpc_jobs/rpc_upgrades.yml

* Shortens the incremental action to give a bit more breathing room
on the job character limit.
* Adds 16.0.0-beta.1 for customer upgrade test
* Adds Newton to Rocky, Pike to R, Queens to R for initial testing
* Removes hold_on_error until things are more stable
Depends on https://github.com/rcbops/rpc-upgrades/pull/291

Shortens incremental action to fit char limit

---

scripts/add_component_skeleton.py

This commit ensures that new projects that are added to the RE
platform have a placeholder generate_release_notes implementation.
Otherwise their releases will fail until generate_release_notes
is implemented.
Issue: [RE-2255](https://rpc-openstack.atlassian.net/browse/RE-2255)

RE-2255 Generate release notes placeholder

---

gating/common/run_lint.sh
pipeline_steps/common.groovy
rpc_jobs/standard_job_premerge.yml

JJB definitions can be stored in project repos, some of which are private. An
ssh-agent is provided to the lint script so it can clone all the necessary
repos for testing JJB definitions.
Issue: [RE-2062](https://rpc-openstack.atlassian.net/browse/RE-2062)

RE-2062 Provide ssh key for lint

---

pipeline_steps/common.groovy

If github changes their public key, the current implementation
will not replace the key for any existing host. Also, if github
implements multiple keys, the current implementation will not
add any new ones for existing hosts.
This patch ensures that both of these situations are catered for.
Issue: [RE-2231](https://rpc-openstack.atlassian.net/browse/RE-2231)

Improve github known_hosts key addition

---

.gitignore
pipeline_steps/common.groovy
rpc_jobs/mk8s.yml
rpc_jobs/rpc_appformix.yml
rpc_jobs/rpc_asc.yml
rpc_jobs/rpc_ceph.yml
rpc_jobs/rpc_eng_ops.yml
rpc_jobs/rpc_jenkins_etl.yml
rpc_jobs/rpc_uam.yml
scripts/lint_jjb.py

* Updated PM jobs to use https protocol
* Updated clone/fetch repo to convert from https to ssh protocol
* Added unit test for repo_url protocol
JIRA: RE-2233
Issue: [RE-2233](https://rpc-openstack.atlassian.net/browse/RE-2233)

Gihub Pull Request Builder Cannot Use SSH Repo URL

---

lint.sh

The lint process clones all repos that contain JJB definitions.
This commit ensures those repos are removed before non-jenkins
lint steps happen (eg python) so that rpc-gating lint checks
don't fail because of a style fail in another project's repo.
Issue: [RE-2263](https://rpc-openstack.atlassian.net/browse/RE-2263)

RE-2263 Don't lint other repos

---

gating/common/run_lint.sh
pipeline_steps/common.groovy
rpc_jobs/defaults.yml
scripts/jjb-path-setup.py

The relevant metadata has now been merged into the mk8s repo.
This commit updates defaults so that the Jenkins-Job-Builder job
will build jobs from the mk8s repo.
Issue: [RE-2070](https://rpc-openstack.atlassian.net/browse/RE-2070)

RE-2070 Build jobs from MK8s repo

---

rpc_jobs/rpc_openstack.yml

PM_rpc-openstack-queens-xenial_mnaio_no_artifacts-swift-system
specifcally is what needs to be held (as mentioned in the issue).
Issue: [RI-591](https://rpc-openstack.atlassian.net/browse/RI-591)

hold the node on error for RI-591

---

rpc_jobs/standard_job_lint_jenkins.yml

The jjb_params parameter macro requires an argument to set the default
value, however no argument was passed. Consequently the rendered
job contained the text "{JOB_SOURCES}" as the default value of that
paramater, rather than the expected value from defaults.
This commit fixes that by passing the appropriate argument.
Issue: [RE-2267](https://rpc-openstack.atlassian.net/browse/RE-2267)

RE-2267 Fix sources param default in std lint job

---

pipeline_steps/common.groovy

* Ensure conversion is applied to the correct parameter
* Move conversion code into a reusable function
Issue: [RE-2268](https://rpc-openstack.atlassian.net/browse/RE-2268)

RE-2268 Fix https to git url conversion

---

job_dsl/standard_job_lint_jenkins.groovy
lint.sh
rpc_jobs/defaults.yml
rpc_jobs/standard_job_release.yml
rpc_jobs/sync_credential_store.yml
scripts/jjb-path-setup.py

* Remove unnecessary call to configure_git
* Prevent jjb-path-setup from cloning job source repos that
are cloned by other mechanisms. This includes rpc-gating
which is provided by common.use_node and the repo currently
being tested, as we want to use the version under test.
* Source venv before calling jjb-path-setup as it requires library
from the venv
* Call the lint script from within the rpc-gating directory, as
it expects paths relative to rpc-gating.
* Add the --python command to lint.sh when creating venvs to ensure
the correct interpreter is installed in each venv
* Remove .git from the end of any ssh urls found in config. The suffix
is not necessary and consistency is required.
* Add error message for when a componenet metdata file can't be found
in a job source repo.

JJB Lint fixes

---

rpc_jobs/rpc_upgrades.yml

The system tests have not run successfully against upgrades and other priorities are higher than resolving issues here. System tests for upgrade will be revisited later and remove the jobs for now to reduce CI noise.
Issue: [ASC-1364](https://rpc-openstack.atlassian.net/browse/ASC-1364)

ASC-1364 remove system tests from rpc-upgrades

---

rpc_jobs/rpc_openstack.yml

This reverts commit 46b5a70ac5624183531e36925c1519e97daffda5.
Signed-off-by: Matthew Thode <mthode@mthode.org>
Issue: [RI-591](https://rpc-openstack.atlassian.net/browse/RI-591)

Revert "hold the node on error for RI-591"

---

rpc_jobs/rpc_upgrades.yml

This gate is intended to provide some testing that approximates the Genentech upgrade scenario.  Initially, the understanding was that they would be upgrading from r16.0.0-beta, but it turns out they are actually running r14.6.0.

Upgrade from Newton release for Genentech gating job

---

rpc_jobs/rpc_openstack_ops.yml

openstack-ops is added to RE jobs to run checkmarx
against the repository code

Adding RE job for openstack-ops

---

pipeline_steps/checkmarx.groovy

The checkmarx scan step stometimes fails with a null pointer exception
during a soap call or a failure to connect to the remote server.
This commit attempts to mitigate both failures by adding retries
with sleep inbetween.
Issue: [RE-2272](https://rpc-openstack.atlassian.net/browse/RE-2272)

RE-2272 Retry checkmarx scans

---

scripts/build_summary/failure.py

Additional timeout messages have been encountered since the original
regex was written. This is useful now as I want to track the occurence
of timeouts in order to know where to focus attention on RE-2194.
Issue: [RE-2194](https://rpc-openstack.atlassian.net/browse/RE-2194)

RE-2194 exapnd build summary timeout regex

---

rpc_jobs/defaults.yml
rpc_jobs/standard_job_checkmarx.yml

Previously a param was added to allow checkmarx jobs to exclude folders.
However that param didn't have a default value that used a jjb macro
so couldn't be overidden from a jjb project. This commit adds the
required macro and a default value.
Issue: [RE-2265](https://rpc-openstack.atlassian.net/browse/RE-2265)

RE-2265 Overrideable default for folder excludes

---

rpc_jobs/re_release_manual.yml
scripts/confluenceutils.py

Previously the monthly release pages were directly under Product Releases
Now they are under annual pages. This commit updates the code to match
the new structure of the wiki.
Issue: [RE-2298](https://rpc-openstack.atlassian.net/browse/RE-2298)

RE-2298 Accomodate restructured wiki

---

rpc_jobs/rpc_asc.yml

This commit adds the `tests` directory to the list of folders to exclude
from the checkmarx scan for the zigzag repository.
Issue: [ASC-1414](https://rpc-openstack.atlassian.net/browse/ASC-1414)

ASC-1414 Exclude zigzag/tests from checkmarx scan

---

scripts/confluence_annual_page.j2

This should have been included with
a23112a6e68035d9620d9a47c947ed13095ee4ef but was omitted.
Issue: [RE-2298](https://rpc-openstack.atlassian.net/browse/RE-2298)

RE-2298 Add annual page template

---

playbooks/allocate_pubcloud.yml
rpc_jobs/rpc_openstack.yml

Rather than use public cloud images, which have proven to be unreliable
due to the nova-agent not starting properly, we enable the jenkins node
build to use the images built by nodepool instead.
The playbook fetches the list of available images, then uses the latest
available one for the build.
This brings the image build process closer to what is used for all tests
and should be more reliable given that nodepool does not use nova-agent.

Use nodepool images for AIO snapshot builds

---

constraints.txt

In [1] we changed the github3.py constraint, resulting
in downstream jobs breaking. To get the jobs back into
a working state, we revert that change along with its
dependencies.
[1] https://github.com/rcbops/rpc-gating/pull/1283
JIRA: RE-1721
Issue: [RE-1721](https://rpc-openstack.atlassian.net/browse/RE-1721)

Revert github3.py constraint change

---

grafana/role_requirements.yml

* Bump ansible-grafana role version to 0.13.0 to pick up the upstream
repo/gpg key fix.
JIRA: RE-2296
Issue: [RE-2296](https://rpc-openstack.atlassian.net/browse/RE-2296)

Jenkins Setup Grafana Repo Fix

---

playbooks/setup_openstack_instances.yml

When using the setup_openstack_instances playbook, the target
hosts may not have /usr/bin/python present on them. This is
the case for Ubuntu Xenial in the new Public Cloud images.
Without /usr/bin/python present, Ansible cannot gather facts
from the target host, so we need to use the raw/script module
to get it there before any subsequent plays which use facts.
Issue: [RE-2323](https://rpc-openstack.atlassian.net/browse/RE-2323)

Ensure /usr/bin/python is present on target hosts

---

pipeline_steps/common.groovy

In [1] the job timeout was set to 10 hours globally, but mistakenly
set to 3 hrs in the global wrap. This is causing job timeouts for
some of the longer running jobs (like MNAIO builds).
This patch just sets the global wrap timeout to the same value.
[1] https://github.com/rcbops/rpc-gating/pull/1275
JIRA: RE-2307
Issue: [RE-2307](https://rpc-openstack.atlassian.net/browse/RE-2307)

Correct global wrap timeout

---

nodepool/setup_nodepool.yml
nodepool/templates/nodepool.yml.j2
playbooks/allocate_pubcloud.yml
playbooks/setup_openstack_instances.yml
scripts/user_data_pubcloud.sh

Currently there are multiple methods for preparing a host for
tests:
1. In the jenkins nodepool plugin configuration, there is a script
which executes on all target nodes to prepare the node for use.
This script is used to add the jenkins user, add the ssh keys,
add the JDK, etc. This is used for preparing OnMetal/Ironic
hosts where we do not control the image.
2. In the setup_openstack_instances playbook, we use the raw Ansible
module to add python to the target host so that Ansible is able
to execute other tasks and modules on that host.
This is used for preparing VM's where we do not control the image.
3. In the allocate_pubcloud playbook we use the raw and script
modules to ensure that the apt sources are configured, apt debug
logging is enabled, and that python and python-yaml are …

Implement a common method for rpc-gating runtime requirements

---

rpc_jobs/rpc_openstack.yml

Master is unstable, so we want to reduce the frequency of the jobs.
Issue: [RI-648](https://rpc-openstack.atlassian.net/browse/RI-648)

RI-648 Change Master PM jobs to weekly

---

pipeline_steps/common.groovy

The release job is a 3 level hierachy:
1. Component-Release-Trigger
2. Component-Release
3. RE-Release
1. Checks the comment to determine if "re-release" was specified
then passes that as a boolean parameter to 2.
The bug is that 1. passed the re release value as an unnamed param.
This commit corrects the param name.
Issue: [RE-2310](https://rpc-openstack.atlassian.net/browse/RE-2310)

RE-2310 Add missing parameter name

---

constraints.txt
pipeline_steps/common.groovy
pipeline_steps/pubcloud.groovy
playbooks/save_pubcloud.yml
requirements.txt

The snapshot images, when booting up, often fail and are inaccessible
via SSH. In order to enable troubleshooting this situation, we set the
password for the jenkins user before snapshotting the instance.

Set jenkins password before saving the image

---

constraints.txt
requirements.txt
scripts/confluenceutils.py

Confluence protects against unknowingly updating a page that has been
modified by using a page version ID. The ID supplied when an update is
requested must be exactly one larger than the current page version ID.
However this means that if there is a conflict, publishing the update
will fail causing the release build to fail. This change adds retry
logic so that any failures when attempting to update the wiki, with a
new version of the release page, will result in the process being rerun.
This means any new updates will be incorporated in the subsequent
attempt.
JIRA: RE-2327
Issue: [RE-2327](https://rpc-openstack.atlassian.net/browse/RE-2327)

Add retry logic to wiki release page updates

---

rpc_jobs/rpc_openstack.yml

This removes the ELK component job from the master MNAIO gates.
JIRA: RI-656
Issue: [RI-656](https://rpc-openstack.atlassian.net/browse/RI-656)

[RI-656] Remove ELK Component from master gate

---

pipeline_steps/common.groovy

matcher.matches() will only return true if the pattern matches the whole
input string. The patterns in use do not cover the whole input string
only the trigger part and surrounding whitespace. That means that
using the current code .matches() won't trigger.
In a previous commit I removed .matches() and it caused release
jobs to fail because Jenkins CPS groovy does not cooerce matcher
objects to Boolean when matching method signatures, but vanilla
groovy does.
Consider the following snippet:
```
def func(Boolean f){
print f
}
Boolean match(){
return ("foo" =~ /oo/)
}
func(match())
```
This snippet returns true in groovy and:
java.lang.NoSuchMethodError: No such DSL method 'func'
in Pipeline/CPS groovy, because theres no method func(Matcher f).
This commit removes the .matches() call, but …

RE-2310 Fix release modifier regex matches

---

rpc_jobs/build_summary.yml

Previously the whole image URL was supplied as the tag name,
which lead to an invalid image name. This commit changes the
tag to "latest".
Issue: [RE-404](https://rpc-openstack.atlassian.net/browse/RE-404)

RE-404 fix build summary image name

---

job_dsl/standard_job_lint_jenkins.groovy

This template is used to created lint jobs for team repos that contain
jjb definitions. Currently it doesn't ensure groovy is installed
so groovy checks are omitted. This commit fixes that by installing
groovy so that groovy scripts can be syntax checked.
Issue: [RE-2354](https://rpc-openstack.atlassian.net/browse/RE-2354)

RE-2354 Install groovy in Jenkins Lint jobs

---

pipeline_steps/common.groovy
rpc_jobs/rpc_jenkins_etl.yml

Required so ASC can run their ETL job that collects data from
the Jenkins API.
Issue: [RE-2355](https://rpc-openstack.atlassian.net/browse/RE-2355)

RE-2355 Allow standard jobs to use internal slave

---

nodepool/templates/nodepool.yml.j2
playbooks/allocate_pubcloud.yml
rpc_jobs/bump_snapshots.yml

```
761cd52 (Hugh Saunders, 8 minutes ago)
RE-2358 Min-ready to 0
Set min-ready to 0 for all labels that are available in multiple regions.
Min-ready is ineffective in this scenario as requests are randomly assigned
to regions rather than being inteligently routed to regions that have ready
nodes.
bdd0ec6 (Hugh Saunders, 11 minutes ago)
RE-2358 Add newton trusty snapshot
These images exist but aren't exposed in nodepool config.
725e162 (Hugh Saunders, 15 minutes ago)
RE-2358 Undefined variable in allocate_pubcloud
The primary and secondary provision tasks had different values for the
userdata param, one of which was an undefined var, this commit sets them
both to the same lookup.
b37c70d (Hugh Saunders, 16 minutes ago)
RE-2358 Bump Snapshots: skip single release series
Theres no need to …
```

RE-2358 Fix bump snapshots for single release series

---

pipeline_steps/common.groovy
rpc_jobs/rpc_jenkins_etl.yml

This job requires access to the Jenkins API as it pulls data from there
to send to google big query.
The only nodes we have with access to the Jenkins api are the master
and one TES node. This node runs centos6, which is a pain as it
uses python2.6
This job uses a docker image to insulate it from the host, allow
modern python and package installs etc. In order to push/pull the image
from the repo, creds are required.
Issue: [RE-2355](https://rpc-openstack.atlassian.net/browse/RE-2355)

RE-2355 Add internal registry creds to ETL job

---

job_dsl/release.groovy

This change ensures that release notes pull requests test against the
most recent release, where most recent is dependent on the release
series. This ensures that the testing better matches the operation
performed by a release.
JIRA: RE-2360
Issue: [RE-2360](https://rpc-openstack.atlassian.net/browse/RE-2360)

Fix pull request release note testing

---

pipeline_steps/common.groovy

addArtifactTypeToComponent requires a number of C libraries to be
installed which causes errors if the slave does not have them. This
change moves addArtifactTypeToComponent to use a shared slave so that
project slaves do not have additional requirements placed on them given
the potential for conflict or absence.
JIRA: RE-2306
Issue: [RE-2306](https://rpc-openstack.atlassian.net/browse/RE-2306)

RE-2306: Use shared slave for addArtifactTypeToComponent

---

scripts/rax_instance_clean.sh

When booting up a snapshot, there are no network interfaces present.
The 'glean' service should set them up automagically once the devices
are present, but it is not working. To work around this, we enable
the service ourselves before we shut the instance down. It will then
start on boot and the new instance should have network connectivity.

Ensure that glean sets up eth0 on boot of snapshots

---

nodepool/templates/nodepool.yml.j2
scripts/rax_instance_clean.sh

When booting up a snapshot, if there are previously implemented
interfaces present which were setup by glean, glean will skip
setting up new interfaces from config_drive. To ensure that the
new instance gets new interfaces setup, we force the removal of
the old interfaces.
For systemd environments, the clean-up happens automatically -
but for upstart environments that doesn't happen, so we need to
ensure it is forced.
Also, the snapshot bump job has been failing for some time due to
issues with the snapshots, and the job only caters for a single version
bump. RPC-O newton released several tags in quick succession, so
we need to manually bump this to the most recent release because
the job won't do it automatically.

Ensure that interfaces setup by glean are removed

---

job_dsl/release.groovy
job_dsl/rpc_artifact_build.groovy
job_dsl/rpc_gating_merge_trigger.groovy
job_dsl/rpc_repo_verify.groovy
job_dsl/standard_job_dep_update.groovy
job_dsl/standard_job_lint_jenkins.groovy
rpc_jobs/bump_snapshots.yml
rpc_jobs/standard_job_gate.yml
rpc_jobs/standard_job_postmerge.yml
rpc_jobs/standard_job_premerge.yml

Some jobs cannot currently have the rpc-gating branch changed.
This fixes that and ensures that they are all consistently
implemented.

Allow rpc-gating branch overrides for all jobs

---

pipeline_steps/pubcloud.groovy
scripts/jenkins_node.py

The legacy method of provisioning slaves using playbooks as part of the
build (not Nodepool) is still used in some cases. Part of the clean up
during the build is to delete the node from Jenkins. Removing the slave
from Jenkins when it does not exist causes a build failure. This change
updates the code to prevent false-positives from these failures causing
builds to fail or mask the true failure.
There are two changes made by this patch:
- The delete call in the Python script is wrapped with exception
handling so that failures when deleting unknown nodes do not
propagate.
- `ssh_slave.destroy` is used to delete the node from Jenkins and is now
performed before the instance is destroyed so that it doesn't
disappear from Jenkins while still registered and result in misleading
logs.
Clean up …

RE-2348: Prevent failure when removing non-existent slave

---

nodepool/templates/nodepool.yml.j2
rpc_jobs/rpc_appformix.yml
rpc_jobs/rpc_barbican.yml
rpc_jobs/rpc_designate.yml
rpc_jobs/rpc_maas.yml
rpc_jobs/rpc_octavia.yml

The current nodepool nodes have a host name which includes a lot
of unnecessary information. For example, the provider does not
need to be included in the host name. Also, some of the label
names are based on very long image names, and the label name is
also included in the host name.
This, in some circumstances, results in a host name which exceeds
the maximum of 63 characters. For example, the following is 67
characters:
nodepool-rpc-r18-xenial_no_artifacts-swift-pubcloud-dfw-0000152558
When trying to set this host name, glean fails because the operating
system rejects it. This causes glean to fail and not continue to
implement the network interfaces, resulting in connectivity for the
node never coming up.
To resolve this, we remove the unnecessary inclusion of the provider
in the host …

Reduce nodepool host name length

---

rpc_jobs/rpc_asc.yml

This commit adds the asc
[healthcheck repo](https://github.com/rcbops/rpc-openstack-healthcheck)
to the job list for checkmarx scanning.
Issue: [ASC-1564](https://rpc-openstack.atlassian.net/browse/ASC-1564)

ASC-1564 Create healthcheck checkmarx job

---

rpc_jobs/rpc_openstack.yml

Add the "ceph" scenario to the system staging job so that we can start
creating Molecule tests for Ceph backends. Also, I dropped a redundant
image specification.
Issue: [ASC-1655](https://rpc-openstack.atlassian.net/browse/ASC-1655)

ASC-1655 Add Ceph Scenario to Staging Job

---

pipeline_steps/checkmarx.groovy

* Added logic to check the build result and if unsuccessful throws a
REException which is caught in the calling function. From there the
common code will create a JIRA ticket if the JIRA_PROJECT_KEY is set.
JIRA: RE-2388
Issue: [RE-2388](https://rpc-openstack.atlassian.net/browse/RE-2388)

Checkmarx Scan Failure Should Create a JIRA Ticket

---

job_dsl/rpc_repo_verify.groovy
job_dsl/standard_job_checkmarx.groovy
job_dsl/standard_job_dep_update.groovy
job_dsl/standard_job_lint_jenkins.groovy
pipeline_steps/common.groovy
rpc_jobs/defaults.yml
rpc_jobs/hardening.yml
rpc_jobs/jjb_setup.yml
rpc_jobs/periodic_cleanup.yml
rpc_jobs/phobos.yml
rpc_jobs/standard_job_checkmarx.yml
rpc_jobs/standard_job_dep_update.yml
rpc_jobs/standard_job_gate.yml
rpc_jobs/standard_job_lint_jenkins.yml
rpc_jobs/standard_job_postmerge.yml
rpc_jobs/standard_job_premerge.yml
rpc_jobs/standard_job_release.yml
rpc_jobs/unit/jira.yml

This change reworks `build_failure_issue` to be used more generally so
that it can also send messages on Slack if required. It is renamed to
`build_failure_notify` to account for this adjustment.
The hardening jobs have been updated to make use of Slack notifications.
Unit test failure expected due to change in function name requiring the job to be rebuilt. Tested manually with: https://rpc.jenkins.cit.rackspace.net/job/RE-unit-test-jira/2030/replay/diff
JIRA: RE-2338
Issue: [RE-2338](https://rpc-openstack.atlassian.net/browse/RE-2338)

RE-2338 Add slack support for notifying of build failures

---

rpc_jobs/osp_mnaio.yml

@odyssey4me Can you tell me if I am specifying two sets of credentials correctly?  I tried to follow the instructions https://rpc-openstack.atlassian.net/wiki/spaces/RE/pages/19005457/RE+for+Projects#REforProjects-Credentials
Issue: [ASC-1623](https://rpc-openstack.atlassian.net/browse/ASC-1623)

ASC-1623 add ASC creds to RPC-R system test job

---

scripts/confluence_annual_page.j2
scripts/confluence_release_page.j2
scripts/confluenceutils.py

Publishing releases by meta-release will no longer be done, releases are
now separated by project. This change updates the publishing code to
remove unnecessary logic and update the appropriate project page.
JIRA: RE-2370
Issue: [RE-2370](https://rpc-openstack.atlassian.net/browse/RE-2370)

Update presentation of releases in Confluence

---

pipeline_steps/docker_utils.groovy

Docker is failing client side when pushing a large amount
of images in parallel. This is a change to limit the amount it
pushes to see if the image jobs become more stable.

Nerf docker upload limit for image jobs

---

rpc_jobs/build_summary.yml

When the Build-Docker-Images-For-Master is ran, it uploads using a suffix
'build-summary'. The Build-Summary's job's default name is 'buildsummary'.
This results in a naming mismatch with Build-Summary causing it to fail. When
manually specifying build-summary, it completes without issue.  This change
updates the default value to match what is actually being uploaded to the docker
registry.

Fix build summary naming issue
