.gitignore, lint.sh, pipeline-steps/allocate_pubcloud.groovy, pipeline-steps/cleanup_pubcloud.groovy, pipeline-steps/common.groovy, pipeline-steps/connect_slave.groovy, pipeline-steps/pub_cloud_slave_highlevel.groovy, pipeline-steps/remove_slave.groovy, playbooks/allocate_pubcloud.yml, playbooks/drop_ssh_auth_keys.yml, playbooks/remove-jenkins-slave.yml, playbooks/setup-jenkins-slave.yml, rpc-jobs/RPC-AIO.yml, rpc-jobs/params.yml, rpc-jobs/single_use_slave_template.yml
Add reusable step for setting up an existing node as a jenkins slave.
Depends on #4
Connects rcbops/u-suk-dev#1066
=> RPC-AIO Pipeline Connect Slave

rpc-jobs/multi-node-aio.yml
Successful Run:
https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO/25/
Connects https://github.com/rcbops/u-suk-dev/issues/1091
=> Multi-Node AIO: Slave allocation and setup

playbooks/install_jenkins_plugins.yml, rpc-jobs/install-jenkins-plugins.yml, rpc-jobs/params.yml
Please let me know if I'm missing any plugins.  I'm also not sure if this is a good approach to take so input appreciated.  :)
Connects https://github.com/rcbops/u-suk-dev/issues/1082
=> Add job to install Jenkins plugins

pipeline-steps/deploy.groovy, rpc-jobs/multi-node-aio.yml
I used deploy.sh script instead of playbooks since that will test a more end to end workflow. A future task can be to make a separate job that deploys using playbooks. Also, I named the stage "Deploy RPC w/ Script" because a "Deploy" stage would get triggered by listing "Deploy VMs" in the stage parameter.
Successful Run: https://rpc.jenkins.cit.rackspace.net/job/OnMetal_Multi_Node_AIO/52/
Connects https://github.com/rcbops/u-suk-dev/issues/1123
=> Multi-Node AIO: Deploy RPC stage

pipeline-steps/multi_node_aio_prepare.groovy, rpc-jobs/multi-node-aio.yml
Because upstream changes tend to only work when using build.sh, I switched to that instead of separate stages for each part of the prepare.
Connects https://github.com/rcbops/u-suk-dev/issues/1209
=> Use build.sh instead of individual scripts

pipeline-steps/holland.groovy, playbooks/test_holland.yml, rpc-jobs/RPC-AIO.yml
Includes playbook from jenkins-rpc, this playbook should be added to rpc
also.
Connects rcbops/u-suk-dev#1176
Depends on #17
=> CIT Stages: Add Holland Testing Stage

pipeline-steps/kibana.groovy, rpc-jobs/multi-node-aio.yml
Newton mult-node AIO: https://rpc.jenkins.cit.rackspace.net/job/kibana-OnMetal_Multi_Node_AIO/5/
Newton AIO: https://rpc.jenkins.cit.rackspace.net/job/kibana-OnMetal_Multi_Node_AIO/6/parameters/
Mitaka multi-node AIO: https://rpc.jenkins.cit.rackspace.net/job/kibana-OnMetal_Multi_Node_AIO/8/
Connects https://github.com/rcbops/u-suk-dev/issues/1126
=> Add Kibana Selenium tests

lint.sh, pipeline-steps/common.groovy, pipeline-steps/pubcloud.groovy, pipeline-steps/webhooks.groovy, playbooks/webhooks.yml, role_requirements.yml, rpc-jobs/webhook.yml
This commit adds a job for configurting a webhook proxy.
* Boots an instance and attaches it as a slave
* Configures sshd and firewall on the instance via ansible
* Drops upstart config and ssh key on master
* Prompts user to install upstart service as the jenkins user doesn't
have sudo.
Connects rcbops/u-suk-dev#1080
=> Add Webhook Proxy

Dockerfile, Jenkinsfile
Required a change to the CIT jenkins slave:
echo 'other_args="-G jenkins"' >> /etc/sysconfig/docker
Connects rcbops/u-suk-dev#1080
=> Add Jenkinsfile for rpc-gating lint job

rpc-jobs/multi-node-aio.yml
https://rpc.jenkins.cit.rackspace.net/job/mkam-OnMetal_Multi_Node_AIO/104/execution/node/114/log/
=> Test Holland in multi-node AIO

pipeline-steps/common.groovy, pipeline-steps/maas.groovy, pipeline-steps/multi_node_aio_prepare.groovy, playbooks/aio_config.yml, playbooks/vars/all.yml, playbooks/vars/onmetal.yml
Connects https://github.com/rcbops/u-suk-dev/issues/1299
Multi-node AIO: https://rpc.jenkins.cit.rackspace.net/view/Multi-Node%20AIO/job/mkam-OnMetal_Multi_Node_AIO/147/testReport/tempest.api.object_storage.test_container_sync_middleware/
AIO: https://rpc.jenkins.cit.rackspace.net/job/mkam-AIO/3/testReport/tempest.api.object_storage.test_container_sync_middleware/
The other tests failing in these runs are unrelated. The quota tests fail because we need a sha bump in the os_tempest roles.
=> Skip container sync test

pipeline-steps/tempest.groovy, rpc-jobs/params.yml
Multi-node AIO: https://rpc.jenkins.cit.rackspace.net/view/Multi-Node%20AIO/job/mkam-OnMetal_Multi_Node_AIO/117/consoleFull
AIO: https://rpc.jenkins.cit.rackspace.net/view/Multi-Node%20AIO/job/mkam-OnMetal_Multi_Node_AIO/118/consoleFull
Connects https://github.com/rcbops/u-suk-dev/issues/1268
=> Run tempest with 3 workers

.gitignore, Jenkinsfile, lint.sh, pipeline-steps/aio_prepare.groovy, pipeline-steps/common.groovy, rpc-jobs/RPC-AIO.yml, scripts/ghstatus.py
Alternative to #57
Corresponding RPCO branch: https://github.com/rcbops/rpc-openstack/pull/1991/files
=> 1313 jenkinsfile jjb matrix

pipeline-steps/pubcloud.groovy, rpc-jobs/RPC-AIO.yml, rpc-jobs/single_use_slave_template.yml
High level function for running a stage on public cloud.
Also fixes a bug where instance_name was not passed to delpubcloudslave
correctly.
Connects rcbops/u-suk-dev#1313
=> Add runonpubcloud function

rpc-jobs/RPC-AIO.yml, rpc-jobs/multi-node-aio.yml, rpc-jobs/params.yml, rpc-jobs/single_use_slave_template.yml
This is only adding the periodic jobs for mitaka, newton, and master. I haven't deployed liberty on multi-node AIO yet since it'll take some different prepare steps so I didn't include that at all here.
Connects https://github.com/rcbops/u-suk-dev/issues/936
=> Create periodic jobs for multi-node AIO

pipeline-steps/common.groovy, pipeline-steps/deploy.groovy
The quotes result in:
fatal: I don't handle protocol '"https'
Connects rcbops/u-suk-dev#1406
=> Fix quoting in ANSIBLE_GIT_REPO

pipeline-steps/artifact-build.groovy, rpc-jobs/RPC-Artifact-Build.yml
=> Add python/container artifact build jobs

rpc-jobs/RPC-Artifact-Build.yml
=> Ensure that environment_vars are passed to build

pipeline-steps/artifact_build.groovy, rpc-jobs/RPC-Artifact-Build.yml
In order to ensure that the correct checkout is
on the remote node we need to use the AIO prep
groovy script.
=> Add AIO prep to Artifact builds

rpc-jobs/RPC-AIO.yml, rpc-jobs/properties.yml
Adding things that were missed in the first commit.
connects rcbops/u-suk-dev#1379
=> GHPRB trigger for AIO jobs part 2

rpc-jobs/RPC-Artifact-Build.yml
Connects https://github.com/rcbops/u-suk-dev/issues/1413
=> Ensure container stage builds containers

rpc-jobs/jjb-setup.yml
I had a successful run of this in Jenkins, but the job unfortunately got deleted when JJB ran and cleaned up old jobs.
=> Convert JJB trigger to pipeline job

pipeline-steps/multi_node_aio_prepare.groovy
Prevents jobs from hanging forever waiting for the VMs to come up.
Connects https://github.com/rcbops/u-suk-dev/issues/1467
=> Timeout multi-node AIO prep

pipeline-steps/artifact_build.groovy
Connects https://github.com/rcbops/u-suk-dev/issues/1450
=> Add RPC_REPO creds to Artifact jobs

pipeline-steps/ssh_slave.groovy
In this case, pip is invoked from the scripts directory, so much look
up a level to find the constraints file.
=> Fix constraints file location

Dockerfile, constraints.txt, lint.sh, scripts/pull_passwords.py, test-requirements.txt
Connected https://github.com/rcbops/u-suk-dev/issues/1537
=> Run flake8 as part of lint script

pipeline_steps/pubcloud.groovy, pipeline_steps/ssh_slave.groovy, rpc_jobs/multi_node_aio.yml, rpc_jobs/rpc_aio.yml, rpc_jobs/rpc_artifact_build.yml, rpc_jobs/single_use_slave_template.yml, rpc_jobs/webhook.yml
This commit moves the step / stage for connecting and destroying a
jenkins slave from pubcloud.groovy to ssh_slave.groovy so that these
steps can be properly included in a non pubcloud context.
Connects https://github.com/rcbops/u-suk-dev/issues/1368
=> Create separate slave step/stage

playbooks/vars/all.yml, rpc_jobs/multi_node_aio.yml
Successful run of all tests against newton-14.0: https://rpc.jenkins.cit.rackspace.net/job/OnMetal-Multi-Node-AIO/22/
[In progress] Master: https://rpc.jenkins.cit.rackspace.net/job/OnMetal-Multi-Node-AIO/23/
[In progress] Mitaka: https://rpc.jenkins.cit.rackspace.net/job/OnMetal-Multi-Node-AIO/25/
Connects https://github.com/rcbops/u-suk-dev/issues/1490
=> Run all tempest tests for multi-node AIO

rpc_jobs/rpc_aio.yml
This commit re-adds 'Destroy Slave' to the default STAGES, and also adds
'Clear Workspace' to STAGES in the upgrade context.
=> Add missing stages to STAGES

pipeline_steps/irr_role_tests.groovy, rpc_jobs/irr_role_test.yml
=> added jobs for generic irr testing

pipeline_steps/irr_role_tests.groovy
=> added return this call

pipeline_steps/common.groovy, pipeline_steps/deploy.groovy, pipeline_steps/holland.groovy, pipeline_steps/kibana.groovy, pipeline_steps/maas.groovy, pipeline_steps/multi_node_aio_prepare.groovy, pipeline_steps/tempest.groovy, playbooks/vars/onmetal.yml, rpc_jobs/lem_multi_node_aio.yml, rpc_jobs/multi_node_aio.yml
Adds the VM parameter to multiple method so that we can run tasks on the newly added deploy node of the multi-node AIO environment.
I used named parameters instead of `Map args` with this card in mind: https://github.com/rcbops/u-suk-dev/issues/1531
Connects https://github.com/rcbops/u-suk-dev/issues/1578
=> Add support to deploy and test from deploy VM node

rpc_jobs/periodic_cleanup.yml, scripts/jenkins_node.py, scripts/periodic_cleanup.py
Deleting offline nodes: https://rpc.jenkins.cit.rackspace.net/job/mkam-Periodic-Cleanup/4/console
I tested that a node coming online didn't get deleted by manually running the script since I couldn't force the exact timing of that situation using my Jenkins job.
Connects https://github.com/rcbops/u-suk-dev/issues/1605
=> Add Jenkins node deletion to periodic cleanup

pipeline_steps/kibana.groovy, rpc_jobs/lem_multi_node_aio.yml, rpc_jobs/rpc_aio.yml
This commit does the following to rpc_aio.yml:
1. Adds `Prepare Kibana Selenium`, `Kibana Tests`, and `Holland` to
STAGES and breaks up the excessively long string
2. Executes kibana.kibana() in the job template DSL
It also does the following to lem_multi_node_aio.yml:
1. Updates concurrent so we can multiple jobs simultaneously
Lastly, we update kibana.groovy:
1. Install phantomjs from binary, rather than Ubuntu package (this
package is problematic on Ubuntu 16.04)
2. Adjusts some shell indentation for easier reading
Connects https://github.com/rcbops/u-suk-dev/issues/1491
Connects https://github.com/rcbops/u-suk-dev/issues/1614
=> Job parity and phantomjs update

pipeline_steps/ssh_slave.groovy, playbooks/setup_jenkins_slave.yml
Retry because of Jenkins exception: https://rpc.jenkins.cit.rackspace.net/job/mkam-OnMetal-Multi-Node-AIO/11/console
Normal slave Connection: https://rpc.jenkins.cit.rackspace.net/job/mkam-OnMetal-Multi-Node-AIO/8/console
Connects https://github.com/rcbops/u-suk-dev/issues/1649
=> Retry Jenkins node connection

pipeline_steps/artifact_build.groovy, rpc_jobs/rpc_artifact_build.yml
The doc skip check was misplaced and therefore not
skipping all jobs properly.
=> Fix doc skip for artifact jobs

rpc_jobs/rpc_artifact_build.yml
Connects https://github.com/rcbops/u-suk-dev/issues/1609
=> Add xenial axis to artifact build jobs

pipeline_steps/common.groovy
Updated to check for artifacts in locations for both Trusty and Xenial and added some logging for the archive steps.
Xenial: https://rpc.jenkins.cit.rackspace.net/job/mkam-RPC-AIO/21/
Trusty: https://rpc.jenkins.cit.rackspace.net/job/mkam-RPC-AIO/25/
Connects https://github.com/rcbops/u-suk-dev/issues/1591
=> UG-575 Add Xenial archive location

pipeline_steps/kibana.groovy, rpc_jobs/defaults.yml, rpc_jobs/lem_multi_node_aio.yml, rpc_jobs/multi_node_aio.yml, rpc_jobs/rpc_aio.yml
Takes into account the different location of the credentials and uses branches of the kibana-selenium repo that correspond to the version of RPC.
AIO upgrade build: https://rpc.jenkins.cit.rackspace.net/job/mkam-RPC-AIO_mitaka-upgrade/5/
AIO, non-upgrade mitaka build: https://rpc.jenkins.cit.rackspace.net/job/mkam-RPC-AIO/10/
Multi-node AIO build: https://rpc.jenkins.cit.rackspace.net/job/mkam-OnMetal-Multi-Node-AIO/4/
Connects https://github.com/rcbops/u-suk-dev/issues/1663
=> Support liberty Kibana testing

rpc_jobs/rpc_gating_lint.yml
=> Add Jira Comments to RPC Gating lint jobs

rpc_jobs/rpc_artifact_build.yml
This builds uses Jira notification functions that must be merged first.
Depends on #183 
=> UG-586 Add Jira Notification for artefact builds

rpc_jobs/rpc_aio.yml
=> UG-586 Add Jira comments to AIO Jobs

pipeline_steps/irr_role_tests.groovy
=> Add Jira comments to IRR jobs

rpc_jobs/periodic_cleanup.yml, scripts/docker_cleanup.sh, scripts/workspace_cleanup.sh
Additions to periodic cleanup:
* Jenkins workspaces not modified in the last 7 days
* Docker objects (images, containers)
=> UG-605 Cleanup docker images and workspaces

rpc_jobs/rpc_aio.yml
Tidy up the artifacts branch exclusions
and update the newton exclusions.
=> Exclude upgrades for newton jobs

pipeline_steps/common.groovy
It is important to check that a git repo has been supplied before
checking if all changes are doc related. Otherwise a misconfigured
job may supply a non repo dir, and the build will get skipped and
marked as successful rather than failing as expected.
This commit raises an exception if the directory supplied to
common.is_doc_update_pr is not a valid git repo.
=> UG-637 Check for git repo in docs check

docs/job_structure.md, rpc_jobs/hw_multi_node_aio.yml
The LEM job has been renamed to "HW" to denote "Hardware".
=> Rename LEM job 

pipeline_steps/common.groovy, pipeline_steps/maas.groovy, pipeline_steps/webhooks.groovy, playbooks/allocate_pubcloud.yml, playbooks/deploy_docker.yml, playbooks/setup_jenkins_slave.yml, playbooks/slave_security.yml, playbooks/webhooks.yml, role_requirements.yml, rpc_jobs/defaults.yml, rpc_jobs/irr_role_test.yml, rpc_jobs/jjb_setup.yml, rpc_jobs/long_running_slave.yml, rpc_jobs/multi_node_aio.yml, rpc_jobs/params.yml, rpc_jobs/rpc_aio.yml, rpc_jobs/rpc_artifact_build.yml, rpc_jobs/single_use_slave_template.yml, rpc_jobs/webhook.yml, scripts/jenkins_node.py, scripts/maasutils.py
=> UG-619 Add job to deploy long running cloud slave

lint.sh, requirements.txt, scripts/lint_naming_conventions.py
Adds lint tests for name formatting enforcement of file and job
names
=> UG-573 Add tests for name formatting

pipeline_steps/influx.groovy, playbooks/slave_open_ports.yml, playbooks/slave_security.yml, rpc_jobs/influx.yml
Job to create an influxdb long running instance.
Uses rpc-maas master branch to deploy using a playbook.
This job is not generic, as the checkouts are quite non-standard.
Issue: [LA-313](https://rpc-openstack.atlassian.net/browse/LA-313)
=> LA-313 Create influx job

pipeline_steps/deploy.groovy, rpc_jobs/rpc_aio.yml
This will ensure that the leapfrog process can't be broken by changes
to the starting point.
Issue: [LA-345](https://rpc-openstack.atlassian.net/browse/LA-345)
=> LA-345 Run leapfrog upgrade on PRs to kilo

pipeline_steps/multi_node_aio_prepare.groovy, pipeline_steps/pubcloud.groovy, pipeline_steps/ssh_slave.groovy, playbooks/setup_jenkins_slave.yml, rpc_jobs/hw_multi_node_aio.yml, rpc_jobs/multi_node_aio.yml, scripts/jenkins_node.py
This allows commands to be run directly
on the deploy node instead of having
an extra ssh step.
Issue: [UG-665](https://rpc-openstack.atlassian.net/browse/UG-665)
=> [UG-665] Connect deploy node vm as a Jenkins slave

.gitignore
I keep almost adding this to my commits, so updating the .gitignore.
=> Update .gitignore with docker playbook

pipeline_steps/common.groovy, pipeline_steps/ssh_slave.groovy
Using the old venv may create problems when versions have changed.
Issue: [RE-49](https://rpc-openstack.atlassian.net/browse/RE-49)
=> RE-49 Always recreate venv

rpc_jobs/hardening.yml
jenkins-job-builder version 2.0.0.0b2 has a `credentials` parameter
type, which would work well for HARDENING_REPO, however as we're still
on 2.0.0.0b1 we cannot make HARDENING_REPO a parameter with a default
from a credential.
Issue: [UG-596](https://rpc-openstack.atlassian.net/browse/UG-596)
=> UG-596 First pass at hardening job

pipeline_steps/common.groovy
If https://github.com/rcbops/rpc-gating/pull/331 merges first, than this PR is not necessary.
=> Load maas script to get token and URL

rpc_jobs/rpc_aio.yml
To deploy maas by default DEPLOY_MAAS should be set to "yes"
not "YES".
=> LA-373 Set DEPLOY_MAAS to yes by default

rpc_jobs/rpc_gating_project_builds.yml, rpc_jobs/single_use_slave_template.yml
This is a basic check to ensure that gating chagnes don't break a
sample build from each project. Currently only RPCO is included.
Issue: [RE-45](https://rpc-openstack.atlassian.net/browse/RE-45)
=> RE-45 Test mechanisms on rpc-gating changes

role_requirements.yml
We were discussing unpinned things in slack, which reminded me that this needed doing.
=> Add pins for unpinned roles

pipeline_steps/artifact_build.groovy
Set the IMAGE env var instead.
=> RE-133 runonpubcloud doesn't take an image param

rpc_jobs/multi_node_aio.yml, rpc_jobs/rpc_aio.yml
Issue: [RE-151](https://rpc-openstack.atlassian.net/browse/RE-151)
=> RE-151 Add gating for newton branch

rpc_jobs/hw_multi_node_aio.yml, rpc_jobs/multi_node_aio.yml, rpc_jobs/rpc_aio.yml
liberty-12.2 > liberty
mitaka-13.1 > mitaka
=> RE-146 Rename liberty and mitaka branches

rpc_jobs/defaults.yml
This reverts commit 3646005b7ff2966c65196c9da01986936514cb24.
=> Revert "Flip builds to IAD"

pipeline_steps/irr_role_tests.groovy
Issue: [RE-198](https://rpc-openstack.atlassian.net/browse/RE-198)
=> RE-198 Remove type in run_irr_tests()

pipeline_steps/tempest.groovy
Tempest has sometimes transient issues, and this can be fixed
by running tempest twice.
We already ran tempest twice on some condition, this formalizes
it for other conditions.
=> Do tempest twice

rpc_jobs/rpc_aio.yml
Issue: [RE-28](https://rpc-openstack.atlassian.net/browse/RE-28)
=> RE-28 Create jira issues for periodic failures

pipeline_steps/influx.groovy, pipeline_steps/webhooks.groovy
This is required after RE-105.
Issue: [RE-194](https://rpc-openstack.atlassian.net/browse/RE-194)
=> RE-194 Supply instance_name to delPubCloudSlave

rpc_jobs/irr_role_test.yml
=> add pike job to rpc-maas

influx-reports/influx-report.sh, influx-reports/influx.py, pipeline_steps/deploy.groovy, pipeline_steps/influx.groovy, requirements.txt
Issue: [LA-412](https://rpc-openstack.atlassian.net/browse/LA-412)
=> LA-412 Update influxdb reporting script

rpc_jobs/irr_role_test.yml
Test rpc-ceph via the irr role test mechanism.
Issue: [HUM-204](https://rpc-openstack.atlassian.net/browse/HUM-204)
=> HUM-304 Add RPC-Ceph job

docs/rpc_aio_leapfrog.md
Put together some docs on manipulating the AIO Leapfrog items.  
Issue: [RLM-204](https://rpc-openstack.atlassian.net/browse/RLM-204)
=> RLM-204 Add some documentation on configuring Leapfrog AIO jobs

pipeline_steps/artifact_build.groovy, pipeline_steps/pubcloud.groovy, playbooks/save_pubcloud.yml, rpc_jobs/cloud_image_build.yml, scripts/rax_create_image.py, scripts/rax_instance_clean.sh
In order to allow the capability to save an image
from a prepped instance in public cloud, a job
added which does so.
The nova CLI is used as rpc-gating uses pyrax
and therefore has access to the nova CLI. The
openstack client would be more ideal to use, but
switching from pyrax to it is out of scope for
this task.
Issue: [RE-279](https://rpc-openstack.atlassian.net/browse/RE-279)
=> RE-279 Build/save image in public cloud

rpc_jobs/hardening.yml, rpc_jobs/multi_node_aio_leapfrog.yml
Issue: [RE-221](https://rpc-openstack.atlassian.net/browse/RE-221)
=> RE-221 Update default image for other MNAIOs

job_dsl/dep_update.groovy, pipeline_steps/common.groovy, rpc_jobs/dep_update.yml, scripts/dep_update.sh, scripts/ghutils.py, scripts/jirautils.py
#386  Need to go in first, but lets get the review process started on this one, but make sure you're only looking at the dep update commit, not the commits that are also in #386 (RE-196)
Issue: [RE-197](https://rpc-openstack.atlassian.net/browse/RE-197)
=> RE-197 Dependency Update Mechanism

rpc_jobs/irr_role_test.yml
Issue: [RLM-224](https://rpc-openstack.atlassian.net/browse/RLM-224)
=> Add rpc-upgrades to the irr jobs

rpc_jobs/multi_node_aio.yml, rpc_jobs/rpc_aio.yml, rpc_jobs/rpc_aio_leapfrog.yml
Issue: [RE-677](https://rpc-openstack.atlassian.net/browse/RE-677)
=> RE-677 Fix KIBANA_SELENIUM_BRANCH override

rpc_jobs/irr_role_test.yml
This introduces a few specific jobs which will ensure we have a good
baseline for AIO testing.
Issue: https://rpc-openstack.atlassian.net/browse/RLM-225
Issue: [RLM-225](https://rpc-openstack.atlassian.net/browse/RLM-225)
=> RLM-225 Updated rpc-upgrades jobs

rpc_jobs/rpc_octavia.yml
Adds the pre-merge job for rpc-octavia
Issue: [K8S-434](https://rpc-openstack.atlassian.net/browse/K8S-434)
=> K8S-434 Add rpc-octavia to CI

job_dsl/dep_update.groovy, job_dsl/release.groovy, rpc_jobs/dep_update.yml, rpc_jobs/standard_job_premerge_release.yml, scripts/dep_update.sh
In order to ensure that changes introduced in a PR
are not breaking the hooks in some way, a PR test
is being introduced.
Working dep_update PR test:
https://rpc.jenkins.cit.rackspace.net/job/Dep-Update_rpc-openstack-master-PR/15/
Working dep_update PM test:
https://rpc.jenkins.cit.rackspace.net/job/Dep-Update_rpc-openstack-master-PM/1/
Working release note PR test:
https://rpc.jenkins.cit.rackspace.net/job/RE-Release-PR_rpc-openstack-master/7/
Issue: [RE-617](https://rpc-openstack.atlassian.net/browse/RE-617)
=> RE-617 Add PR tests for dep_update and release hooks

pipeline_steps/pubcloud.groovy
The clean up process requires an inventory file, in order
to determine the ID of the instance to remove and the region that
contains it.
If the inventory file doesn't exist, there is no point attempting
cleanup. If the job failed or was aborted before instance allocation
then there is nothing to cleanup. If an instance was allocated then
it will be cleaned up by the periodic cleanup job.
Issue: [RE-1073](https://rpc-openstack.atlassian.net/browse/RE-1073)
=> RE-1073 Check for inventory file before clean up

scripts/notifications.py
Fixes a few problems I noticed while testing mail notifications:
* No longer relies on the context object if all the options
are supplied
* Throw exception if the request to the mailgun api fails
* Debug log request and response information for the mailgun api
interaction.
Issue: [RE-646](https://rpc-openstack.atlassian.net/browse/RE-646)
=> RE-646 Mailgun notification fixes

rpc_jobs/rpc_octavia.yml
This job aims to builds and test and amphora image. If that
was succcessful it will store it in the artefact storage
Issue: [K8S-454](https://rpc-openstack.atlassian.net/browse/K8S-454)
=> K8S-454 Adds an Octavia post-merge job

rpc_jobs/phobos.yml
Depends on:
Related To:
Issue: [RE-1082](https://rpc-openstack.atlassian.net/browse/RE-1082)
=> RE-1082 Fix failures resulting from phobos deployment

rpc_jobs/rpc_upgrades.yml
Enables remaining AIO jobs for rpc-upgrade testing.
Issue: [RLM-290](https://rpc-openstack.atlassian.net/browse/RLM-290)
=> RLM-290 Enable all AIO rpc-upgrade jobs

rpc_jobs/rpc_upgrades.yml
This change adds a minor upgrade job for newton using the latest minor
release.
Issue: [RE-913](https://rpc-openstack.atlassian.net/browse/RE-913)
=> RE-913 Add minor upgrade job to rpc-upgrades jobs

playbooks/allocate_pubcloud.yml
This should help with debugging instance creation failures.
Issue: [RE-1146](https://rpc-openstack.atlassian.net/browse/RE-1146)
=> RE-1146 Add debug task to allocate pubcloud

pipeline_steps/common.groovy, pipeline_steps/pubcloud.groovy, rpc_jobs/defaults.yml, rpc_jobs/rpc_octavia.yml, rpc_jobs/standard_job_postmerge.yml, rpc_jobs/standard_job_premerge.yml, rpc_jobs/unit/artefact_publish.yml, rpc_jobs/unit/re_unit_tests.yml, rpc_jobs/unit/single_use_slave.yml, rpc_jobs/unit/with_requested_credentials.yml, scripts/lint_naming_conventions.py
This collection of commits allows a project to specify the credentials that their jobs require via JJB. RPC-Repo creds are added to octavia as they need them and also as an example. 
Issue: [RE-774](https://rpc-openstack.atlassian.net/browse/RE-774)
=> RE-774 Project specific creds for standard jobs

rpc_jobs/standard_job_postmerge.yml, rpc_jobs/standard_job_premerge.yml, rpc_jobs/unit/re_unit_tests.yml, rpc_jobs/unit/single_use_slave.yml
* Unit test job:
* didn't handle PRs correctly
* job name mismatch for single use slave test.
* Standard Job Post Merge
* withCredentials was not replaced with withRequestedCredentials.
Issue: [RE-1157](https://rpc-openstack.atlassian.net/browse/RE-1157)
=> RE-1157 Fix issues introduced by RE-774

rpc_jobs/rpc_upgrades.yml
Issue: [RLM-383](https://rpc-openstack.atlassian.net/browse/RLM-383)
=> RLM-383 Adds Kilo to Newton 14.2.0 test

job_dsl/dep_update.groovy, pipeline_steps/common.groovy, pipeline_steps/pubcloud.groovy, rpc_jobs/defaults.yml, rpc_jobs/params.yml, rpc_jobs/standard_job_postmerge.yml, rpc_jobs/standard_job_premerge.yml
Test job with Docker:
- https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-gating-master-xenial-functional-test-gh/4
Test jobs with compute:
- https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-gating-master-xenial-functional-test-gh/5
- https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-openstack-master-xenial-swift-deploy-gh/1
Issue: [RE-1075](https://rpc-openstack.atlassian.net/browse/RE-1075)
=> Modify standard jobs to support use of Docker containers

pipeline_steps/common.groovy, rpc_jobs/rpc_openstack.yml
Issue: [RE-1163](https://rpc-openstack.atlassian.net/browse/RE-1163)
=>  RE-1163 Add rpc-openstack master tox jobs

rpc_jobs/rpc_openstack.yml
Issue: [RE-1163](https://rpc-openstack.atlassian.net/browse/RE-1163)
=>  RE-1163 Add rpc-openstack mitaka/liberty/kilo tox jobs

rpc_jobs/rpc_upgrades.yml
Bumps release jobs to 14.5.0.
Issue: [RLM-636](https://rpc-openstack.atlassian.net/browse/RLM-636)
=> RLM-636 Bump rpc-upgrades release jobs to 14.5.0

docs/branch_strategy.html
These diagrams form part of the [RE Branch Strategy](https://rpc-openstack.atlassian.net/wiki/spaces/RE/pages/95387649/RE+Branch+Strategy) wiki page, please review that in it's entirety. 
Non VPN rendered version: https://rawgit.com/rcbops/rpc-gating/RE-1101/docs/branch_strategy.html
Issue: [RE-1101](https://rpc-openstack.atlassian.net/browse/RE-1101)
=> RE-1101 Branch Strategy Documentation

rpc_jobs/rpc_upgrades.yml
Now that test to Newton is stable, this will test the release versions.
Issue: [RLM-289](https://rpc-openstack.atlassian.net/browse/RLM-289)
=> RLM-289 Enables newton release mnaio leap tests

rpc_jobs/rpc_upgrades.yml
Bump rpc-upgrades release tests to r14.6.0
Issue: [RLM-1031](https://rpc-openstack.atlassian.net/browse/RLM-1031)
=> RLM-1031 Bump rpc-upgrades release tests to r14.6.0

rpc_jobs/rpc_openstack.yml
Multi Node - Tests both artifacts enabled and disabled
Issue: [RLM-1078](https://rpc-openstack.atlassian.net/browse/RLM-1078)
=> RLM-1078 Adds PostMerge Jobs for MNAIO

rpc_jobs/rpc_openstack.yml
Also removes some cruft from newton job
Issue: [RLM-1078](https://rpc-openstack.atlassian.net/browse/RLM-1078)
=> RLM-1078 Adds MNAIO jobs for master

rpc_jobs/rpc_openstack.yml
Adds the loose artifact jobs.
Issue: [RLM-1078](https://rpc-openstack.atlassian.net/browse/RLM-1078)
=> RLM-1078 Adds the loose mnaio jobs as well

rpc_jobs/rpc_openstack.yml
Newton doesn't support no_artifacts so drop
the jobs for them
Issue: [RLM-1078](https://rpc-openstack.atlassian.net/browse/RLM-1078)
=> RLM-1078 Drops no_artifacts job from newton

README.md, job_dsl/dep_update.groovy, job_dsl/release.groovy, lint.sh, pipeline_steps/common.groovy, rpc_jobs/build_gating_venv.yml, rpc_jobs/cloud_image_build.yml, rpc_jobs/influx.yml, rpc_jobs/install_jenkins_plugins.yml, rpc_jobs/irr_role_test.yml, rpc_jobs/jjb_setup.yml, rpc_jobs/long_running_slave.yml, rpc_jobs/ops_fabric_analytics.yml, rpc_jobs/ops_fabric_chatbot.yml, rpc_jobs/periodic_cleanup.yml, rpc_jobs/phobos.yml, rpc_jobs/pull_request_issue_link.yml, rpc_jobs/rpc_artifact_build.yml, rpc_jobs/setup_nodepool.yml, rpc_jobs/standard_job_postmerge.yml, rpc_jobs/standard_job_premerge.yml, rpc_jobs/sync_credential_store.yml, rpc_jobs/unit/re_unit_tests.yml, rpc_jobs/webhook.yml, scripts/lint_jjb.py
This PR adds two controls for log storage:
1. Ensure that no console log may exceed 200MB - the job will be killed if that limit is exceeded
1. Ensure that all jobs have a retention policy so logs are not stored indefinitely. A lint rule is added to enforce this. 
Issue: [RE-1191](https://rpc-openstack.atlassian.net/browse/RE-1191)
=> RE-1191 Control Log Storage

README.md, job_dsl/dep_update.groovy, job_dsl/release.groovy, lint.sh, pipeline_steps/common.groovy, rpc_jobs/build_gating_venv.yml, rpc_jobs/cloud_image_build.yml, rpc_jobs/influx.yml, rpc_jobs/install_jenkins_plugins.yml, rpc_jobs/irr_role_test.yml, rpc_jobs/jjb_setup.yml, rpc_jobs/long_running_slave.yml, rpc_jobs/ops_fabric_analytics.yml, rpc_jobs/ops_fabric_chatbot.yml, rpc_jobs/periodic_cleanup.yml, rpc_jobs/phobos.yml, rpc_jobs/pull_request_issue_link.yml, rpc_jobs/rpc_artifact_build.yml, rpc_jobs/setup_nodepool.yml, rpc_jobs/standard_job_postmerge.yml, rpc_jobs/standard_job_premerge.yml, rpc_jobs/sync_credential_store.yml, rpc_jobs/unit/re_unit_tests.yml, rpc_jobs/webhook.yml, scripts/lint_naming_conventions.py
Reverts rcbops/rpc-gating#577
One of the global wrappers requires a node, needs more testing.
=> Revert "RE-1191 Control Log Storage"

pipeline_steps/common.groovy, rpc_jobs/hardening.yml
Issue: [RE-1238](https://rpc-openstack.atlassian.net/browse/RE-1238)
=> RE-1238 Add hardening job support

rpc_jobs/rpc_designate.yml
Initial submission for gating the rpc-designate repo.
Issue: [RI-131](https://rpc-openstack.atlassian.net/browse/RI-131)
=> RI-131: Gating job for rpc-designate

rpc_jobs/rpc_ceph.yml
Issue: [CEPHSTORA-53](https://rpc-openstack.atlassian.net/browse/CEPHSTORA-53)
=> [CEPHSTORA-53] Add keystone/rgw integration test

rpc_jobs/irr_role_test.yml
Issue: [RE-1277](https://rpc-openstack.atlassian.net/browse/RE-1277)
=> RE-1277 Remove legacy rpc-role-logstash job

rpc_jobs/rpc_hummingbird.yml
Issue: [HUM-529](https://rpc-openstack.atlassian.net/browse/HUM-529)
=> HUM-529 Gating job for rpc-hummingbird

rpc_jobs/release.yml, scripts/ghutils.py, scripts/release.py
This patch also makes the default command more explicit so that
its easier to predict the effect changing each variable will have.
Issue: [RE-1306](https://rpc-openstack.atlassian.net/browse/RE-1306)
=> RE-1306 Detect mainline=rc and fail out

rpc_jobs/rpc_ceph.yml
Issue: [CEPHSTORA-98](https://rpc-openstack.atlassian.net/browse/CEPHSTORA-98)
=> CEPHSTORA-98 Skip jobs for doc file changes (.md/.rst)

constraints.txt, requirements.txt, rpc_jobs/standard_job_postmerge.yml, scripts/lint_jjb.py
In order to allow Post Merge (PM) job frequencies to
be configured, a parameter is added to allow any a
project to specify it.
The default is left as "@daily" to maintain the
current state for all jobs.
Issue: [RE-1313](https://rpc-openstack.atlassian.net/browse/RE-1313)
=> RE-1313 Add PM job frequency parameter

pipeline_steps/common.groovy
In #645, we had set some defaults or handle situations where
parameters being introduced were not yet available on live jobs.
1. In common.groovy, we can now explicitly throw an exception if
env.SLAVE_CONTAINER_DOCKERFILE_REPO is not set to either "PROJECT"
or "RE".  The previous structure would allow "RE" to be assumed
(the default) if env.SLAVE_CONTAINER_DOCKERFILE_REPO hadn't been
set.
2. In container.groovy, we can remove the default of "./Dockerfile" on
env.SLAVE_CONTAINER_DOCKERFILE_PATH since a default of
"./Dockerfile" will be set at the parameter level. We also change
from using `environ.get` so we can throw a KeyError if one of the
env variables do not exist.
NOTE: Please allow #645 to merge before this merges.
Issue: [RE-1169](https://rpc-openstack.atlassian.net/browse/RE-1169)
=> RE-1169 Docker follow-up changes

rpc_jobs/rpc_upgrades.yml
Reduces rpc-upgrades jobs to weekly runs instead of
daily runs.
Issue: [RLM-1443](https://rpc-openstack.atlassian.net/browse/RLM-1443)
=> RLM-1443 Reduce rpc-upgrades jobs to weekly runs

rpc_jobs/rpc_designate.yml
Issue: [RI-190](https://rpc-openstack.atlassian.net/browse/RI-190)
=> RI-190: Update Designate Test to include Pike

rpc_jobs/rpc_ceph.yml
Issue: [CEPHSTORA-131](https://rpc-openstack.atlassian.net/browse/CEPHSTORA-131)
=> CEPHSTORA-131 Add periodic for rpc-ceph/newton-rc integration

rpc_jobs/rpc_designate.yml
This PR adds in the master-rc branch for only PM testing.
Issue: [RI-208](https://rpc-openstack.atlassian.net/browse/RI-208)
=> RI-208: Add Designate master-rc branch for testing

rpc_jobs/rpc_artifact_build.yml, rpc_jobs/rpc_openstack.yml
@chundu and @mendi have requested the removal of these jobs since pike
is not shipping with any artifacts.
Issue: [RE-1332](https://rpc-openstack.atlassian.net/browse/RE-1332)
=> RE-1332 Remove artifact jobs from pike.*

rpc_jobs/rpc_openstack.yml
This commit adds the system action to pike-rc-mnaio-postmerge to bring
it into parity with the pike branch.
Issue: [ASC-232](https://rpc-openstack.atlassian.net/browse/ASC-232)
=> (ASC-232) Add system action to pike-rc

rpc_jobs/rpc_octavia.yml
Issue: [RE-1328](https://rpc-openstack.atlassian.net/browse/RE-1328)
=> RI-226 Adds the Pike rpc-octavia branch to the CI

rpc_jobs/rpc_octavia.yml
Issue: [RI-226](https://rpc-openstack.atlassian.net/browse/RI-226)
=> RI-226 Add new project for octavia's pike jobs

rpc_jobs/rpc_ceph.yml
Issue: [CEPHSTORA-174](https://rpc-openstack.atlassian.net/browse/CEPHSTORA-174)
=> CEPHSTORA-174 Create rpc-ceph gating job for bluestore

nodepool/elements/jenkins-slave/package-installs.yaml, nodepool/nodepool-config.yml, pipeline_steps/common.groovy, playbooks/setup_nodepool.yml, playbooks/vars/nodepool.yml, rpc_jobs/setup_nodepool.yml, rpc_jobs/unit/re_unit_tests.yml
This pr includes changes required to ensure the RPC nodepool cluster works with the jenkins nodepool plugin.
Issue: [RE-1393](https://rpc-openstack.atlassian.net/browse/RE-1393)
Issue: [RE-1387](https://rpc-openstack.atlassian.net/browse/RE-1387)
=> RE-1393 RPC NodePool Config Changes

.gitignore, rpc_jobs/phobos.yml
- On deploy failure, create JIRA ticket in REO JIRA project instead of RE project.
- Change Channel Notification List.
Issue: [RE-1410](https://rpc-openstack.atlassian.net/browse/RE-1410)
=> RE-1410 Updated Slack Channel List and Build Failure JIRA Project

rpc_jobs/rpc_appformix.yml
This PR is for the initial commit for the RPC-AppFormix repo. This testing is only doing syntax checking at this time and will, at a later time, include functional testing.
Issue: [RI-256](https://rpc-openstack.atlassian.net/browse/RI-256)
=> RI-256: RPC-Appformix gating job initial commit

rpc_jobs/rpc_designate.yml
This would need to merge after https://github.com/rcbops/rpc-designate/pull/27 as this is reliant on the code changes in https://github.com/rcbops/rpc-designate/pull/27 to merge. Please don't merge this until after that PR merges.
Issue: [RI-259](https://rpc-openstack.atlassian.net/browse/RI-259)
=> RI-259: Include Queens Scenario to testing

rpc_jobs/standard_job_gate.yml, rpc_jobs/standard_job_l2_gate.yml
- Created l2 job template.
Issue: [RE-1425](https://rpc-openstack.atlassian.net/browse/RE-1425)
=> RE-1316 Implement Sandbox Integration Gating Job

pipeline_steps/github.groovy, rpc_jobs/merge_pull_request.yml, rpc_jobs/standard_job_release.yml, scripts/ghutils.py
=> RE-1317 Add support for automated releases

pipeline_steps/common.groovy, rpc_jobs/rpc_appformix.yml
Issue: [RE-1457](https://rpc-openstack.atlassian.net/browse/RE-1457)
=> RE-1457 Add cred for AppFormix jobs

pipeline_steps/github.groovy, rpc_jobs/merge_pull_request.yml, rpc_jobs/standard_job_gate.yml, rpc_jobs/standard_job_release.yml, scripts/ghutils.py
Also included:
RE-1317 Fix interpreter directives in release job
When mismatch detected - https://rpc.jenkins.cit.rackspace.net/job/Merge-Pull-Request/3/console
Successful merge - https://rpc.jenkins.cit.rackspace.net/job/Merge-Pull-Request/4/console
=>  RE-1317 Ensure the correct SHA when merging

grafana/grafyaml/dashboard-nodepool.yaml, grafana/grafyaml/datasource-nodepool.yaml, grafana/setup_grafana.yml, nodepool/role_requirements.yml, nodepool/setup_nodepool.yml, pipeline_steps/common.groovy, role_requirements.yml, rpc_jobs/periodic_cleanup.yml
A few odds and ends fell out when doing testing with the
merged PR. These were due to some last-minute changes
implemented which didn't get tested, couldn't get tested
or were forgotten.
This PR's finalises the implementation with the last set
of tweaks which have been tested,
Issue: [RE-1408](https://rpc-openstack.atlassian.net/browse/RE-1408)
=> RE-1408 Updates to nodepool metrics stack

rpc_jobs/build_gating_venv.yml
- Moved tar and ssh to inside the container
- Added ssh agent support
- Added logic to skip building virtual env if archive exists.
- Changed concurrent to true
- Removed lock
Issue: [RE-1425](https://rpc-openstack.atlassian.net/browse/RE-1425)
=> RE-1425 RPC Gating VirtualEnv Container Optimizations

pipeline_steps/common.groovy, pipeline_steps/ssh_slave.groovy, rpc_jobs/defaults.yml, rpc_jobs/rpc_eng_ops.yml, rpc_jobs/standard_job_postmerge.yml, rpc_jobs/standard_job_premerge.yml, rpc_jobs/unit/re_unit_tests.yml, rpc_jobs/unit/wrappers.yml
Job to create a phobos-ironic embeded environment and deploy into it.
Issue: [RE-1243](https://rpc-openstack.atlassian.net/browse/RE-1243)
=> RE-1243 Embeded Environment Deploy Job

nodepool/files/nodepool.yml, rpc_jobs/dummy_pipeline.yml, rpc_jobs/rpc_ceph.yml, rpc_jobs/rpc_eng_ops.yml, rpc_jobs/rpc_hummingbird.yml, rpc_jobs/rpc_maas.yml, rpc_jobs/rpc_openstack.yml, rpc_jobs/rpc_role_logstash.yml, rpc_jobs/standard_job_postmerge.yml, rpc_jobs/standard_job_premerge.yml, rpc_jobs/unit/re_unit_tests.yml, rpc_jobs/unit/wrappers.yml
* Rename g1-8 nodepool nodes and add p2-15 nodes
* Move RPC-O PR jobs to use nodepool
* Move RPC-MAAS PR jobs to use nodepool
* Move RPC-CEPH PR/PM jobs to use nodepool 
* Move RPC-HUMMINGBIRD PR/PM jobs to use nodepool
* Move RPC-ROLE-LOGSTASH PR jobs to use nodepool
* Move RPC-ENG-OPS jobs to use nodepool
=> RE-1463 Use nodepool nodes for functional tests

scripts/docker_cleanup.sh
- Added sudo for docker commands to allow Jenkins Master cleanup to work.
Issue: [RE-1477](https://rpc-openstack.atlassian.net/browse/RE-1477)
=> RE-1477 Docker Cleanup Fixes

scripts/build_summary/build.py, scripts/build_summary/build_summary_gh.py, scripts/build_summary/failure.py
These slipped in with a change that couldn't be tested by the
lint job.
No new functionality is added by this commit, just fixes to get flake8
to pass.
Issue: [RE-1509](https://rpc-openstack.atlassian.net/browse/RE-1509)
=> RE-1509 Fix lint failures in build summary

rpc_jobs/rpc_upgrades.yml
Add mitaka to newton leap gate
Issue: [RLM-1474](https://rpc-openstack.atlassian.net/browse/RLM-1474)
=> RLM-1474 Add mitaka to newton leap gate

rpc_jobs/rpc_upgrades.yml
Don't run gates on various file types
Issue: [RLM-1475](https://rpc-openstack.atlassian.net/browse/RLM-1475)
=> RLM-1475 Don't run gates on various file types

rpc_jobs/rpc_appformix.yml
Issue: [ri-290](https://rpc-openstack.atlassian.net/browse/ri-290)
=> ri-290: Update Appformix Testing for queens and version bump

rpc_jobs/standard_job_gate.yml, rpc_jobs/standard_job_release.yml
This commit updates the gate trigger to indicate that it's a standard
check (recheck), and also updates the release trigger to indicate that
the release process will be run.
Issue: [RE-1489](https://rpc-openstack.atlassian.net/browse/RE-1489)
=> RE-1489 Update gate / release triggers

nodepool/files/nodepool.yml
Issue: [RE-1464](https://rpc-openstack.atlassian.net/browse/RE-1464)
=> RE-1464 Add missing 'pools' section for pubcloud-{dfw,ord}

rpc_jobs/rpc_ceph.yml
Add job for rpc-o Pike integration with rpc-ceph.
Issue: [CEPHSTORA-271](https://rpc-openstack.atlassian.net/browse/CEPHSTORA-271)
=> CEPHSTORA-271 Add rpco_pike periodic job

rpc_jobs/rpc_component.yml
Issue: [RE-1491](https://rpc-openstack.atlassian.net/browse/RE-1491)
=> RE-1491 Add pull requests tests for rpc_component

rpc_jobs/rpc_octavia.yml
Issue: [RE-1536](https://rpc-openstack.atlassian.net/browse/RE-1536)
=> RE-1536 Add octavia periodic job from snapshot

rpc_jobs/rpc_ceph.yml
Issue: [RE-1482](https://rpc-openstack.atlassian.net/browse/RE-1482)
=> RE-1482 Add rpc-ceph gate/release jobs

rpc_jobs/rpc_openstack.yml
Issue: [RO-4246](https://rpc-openstack.atlassian.net/browse/RO-4246)
=> RO-4246 add job for mnaio master-rc

scripts/ghutils.py
This change updates the merge_pr function to attempt to delete the pull
request branch. If rpc-jenkins-svc has the correct permissions and the
branch isn't protected, it will delete the branch. This functionality is
used by the Merge-Pull-Request job.
The repo context object is modified to add the github session object to
allow interaction with the pull request repo because it may not be the
same as the base branch repo.
Issue: [RE-1486](https://rpc-openstack.atlassian.net/browse/RE-1486)
=> RE-1486 Clean-up pull request branch on merge

rpc_jobs/rpc_maas.yml
Issue: [RE-1483](https://rpc-openstack.atlassian.net/browse/RE-1483)
=> RE-1483 Add release jobs for rpc-maas

rpc_jobs/rpc_hummingbird.yml
Issue: [RE-1544](https://rpc-openstack.atlassian.net/browse/RE-1544)
=> RE-1544 Add rpc-hummingbird release job

pipeline_steps/common.groovy
Artifact archival is not part of the test being executed, its a
convenience provided by RE. As such failures in that process
should not cause a build to fail.
This commit adds try/catch around artifact archival, and creates
a Jira issue on failure, instead of letting the exception propagate
up and fail the build.
Issue: [RE-1619](https://rpc-openstack.atlassian.net/browse/RE-1619)
=> RE-1619 Catch Artifact Archival Failures

rpc_jobs/rpc_ceph.yml
Issue: [RE-1617](https://rpc-openstack.atlassian.net/browse/RE-1617)
=> RE-1617 Add rpc-ceph dep-update job

rpc_jobs/rpc_hummingbird.yml
Issue: [RE-1617](https://rpc-openstack.atlassian.net/browse/RE-1617)
=> RE-1617 Add rpc-hummingbird dep-update job

rpc_jobs/rpc_hummingbird.yml
Issue: [RE-1606](https://rpc-openstack.atlassian.net/browse/RE-1606)
=> RE-1606 Add a skip_pattern to rpc-hummingbird

rpc_jobs/rpc_ceph.yml
Issue: [RE-1606](https://rpc-openstack.atlassian.net/browse/RE-1606)
=> RE-1606 Update rpc-ceph's skip_pattern

pipeline_steps/common.groovy
If a release fails, this change ensures any RELEASE_ jobs, that need to
be run for the release, do not need to be re-run when the release is
retried if they succeeded and the SHA has not changed. An example of
where this helps is if the release process fails when cloning rpc-gating
from GitHub.
JIRA: RE-1684
Issue: [RE-1684](https://rpc-openstack.atlassian.net/browse/RE-1684)
When there is no successful build:
```
[Pipeline] readYaml
[Pipeline] parallel
[Pipeline] [RELEASE_rpc-product-1-master-xenial-functional-test] { (Branch: RELEASE_rpc-product-1-master-xenial-functional-test)
[Pipeline] [RELEASE_rpc-product-1-master-xenial-functional-test] build (Building RELEASE_rpc-product-1-master-xenial-functional-test)
19:27:53 [RELEASE_rpc-product-1-master-xenial-functional-test] Scheduling …
```
=> Skip release tests that have already succeeded

rpc_jobs/rpc_upgrades.yml
* Adds Mitaka MNAIO version test jobs
* Removes Mitaka major job
* Removes versions from head testing, only tests versions to releases.
Issue: [FLEEK-134](https://rpc-openstack.atlassian.net/browse/FLEEK-134)
=> FLEEK-134 Adds Mitaka MNAIO test jobs

playbooks/phobos_vpn.yml, rpc_jobs/setup_nodepool.yml
- Updated host value to use target_hosts when available instead of localhost
- Added phobos_vpn to Prepare Instances Stage
JIRA: RE-1555
Issue: [RE-1555](https://rpc-openstack.atlassian.net/browse/RE-1555)
=> RE-1555 Implement VPN Connectivity

rpc_jobs/build_summary.yml
Ensure all required css and js files are deployed along with with
the main build summary page and its data file.
Issue: [RE-1733](https://rpc-openstack.atlassian.net/browse/RE-1733)
=> RE-1733 Ensure build summary is fully deployed

playbooks/phobos_vpn.yml, rpc_jobs/setup_nodepool.yml
- Wrapped phobos_vpn.yml with appropriate VPN variables
JIRA: RE-1735
Issue: [RE-1735](https://rpc-openstack.atlassian.net/browse/RE-1735)
=> RE-1735 VPN Playbook Fails with Undefined Vars

rpc_jobs/rpc_openstack.yml
Adds gate jobs for the new branches
Issue: [RI-376](https://rpc-openstack.atlassian.net/browse/RI-376)
=> RI-376 Add Queens branch gating

pipeline_steps/common.groovy, pipeline_steps/influx.groovy, pipeline_steps/pubcloud.groovy, pipeline_steps/ssh_slave.groovy, rpc_jobs/periodic_cleanup.yml, rpc_jobs/repo_server.yml, rpc_jobs/setup_grafana.yml, rpc_jobs/setup_graphite.yml, rpc_jobs/setup_nodepool.yml, rpc_jobs/setup_statsd.yml
- Added phobos-nodepool profile to clouds.yaml
- Added additional credentials/env vars to cloud_creds to support phobos nodepool
- Refactored writeCloudCfg() routine and calls - moved outer cloud credentials wrapper to inside the writeCloudCfg() method where it is directly used.
- set fail_on_errors: False to ensure Ansible script doesn't just fail even if one VPN connection fails
JIRA: RE-1558
Issue: [RE-1558](https://rpc-openstack.atlassian.net/browse/RE-1558)
=> RE-1558 Add Phobos Region to clouds.yaml

rpc_jobs/rpc_openstack.yml
Issue: [RE-1554](https://rpc-openstack.atlassian.net/browse/RE-1554)
=> RE-1554 Update rpc-openstack's skip_pattern

rpc_jobs/hardening.yml
- changes the frequency from daily to weekly
- adds queens/queens-rc jobs
Issue: [RE-1554](https://rpc-openstack.atlassian.net/browse/RE-1554)
=> RE-1554 Update hardening jobs

rpc_jobs/rpc_upgrades.yml
Adds minor upgrade jobs for pike and queens
Issue: [FLEEK-140](https://rpc-openstack.atlassian.net/browse/FLEEK-140)
=> FLEEK-140 Adds periodic jobs for testing minor upgrades

rpc_jobs/periodic_cleanup.yml
The call to withRequestedCredentials needs to be changed to
common.withRequestedCredentials instead.
Issue: [RE-1558](https://rpc-openstack.atlassian.net/browse/RE-1558)
=> RE-1558 Fix Periodic-Cleanup failure

nodepool/files/nodepool.yml
- Added phobos-cloud profile/config entry to nodepool.yaml
JIRA: RE-1559
Issue: [RE-1559](https://rpc-openstack.atlassian.net/browse/RE-1559)
=> RE-1559 Nodepool Configuration for Phobos

rpc_jobs/standard_job_premerge_release.yml
Issue: [RI-379](https://rpc-openstack.atlassian.net/browse/RI-379)
=> RI-379 Add RE-Release-PR_rpc-openstack-queens job

rpc_jobs/rpc_openstack.yml
This removes all of the master-rc gating jobs.
Issue: [RI-380](https://rpc-openstack.atlassian.net/browse/RI-380)
=> RI-380 Remove master-rc jobs

rpc_jobs/periodic_cleanup.yml
- Added additional debug and error reporting to Master Log Compression stage
JIRA: RE-1766
Issue: [RE-1766](https://rpc-openstack.atlassian.net/browse/RE-1766)
=> RE-1766 Add Additional Debug to Job Cleanup

rpc_jobs/periodic_cleanup.yml
- Added defensive code to the master log compression logic
JIRA: RE-1766
JIRA: RE-1767
Issue: [RE-1766](https://rpc-openstack.atlassian.net/browse/RE-1766)
=> Add Defensive Code to the Job Cleanup

rpc_jobs/rpc_upgrades.yml
Adds the following weekly periodic jobs for rpc-upgrades:
P2Q AIO
N2Q MNAIO
P2Q MNAIO
Issue: [RI-417](https://rpc-openstack.atlassian.net/browse/RI-417)
=> RI-417 Add P2Q AIO, N2Q/P2Q MNAIO upgrade jobs

rpc_jobs/rpc_openstack.yml
Adding gating for the new rocky branch, to be created.
Issue: [RI-434](https://rpc-openstack.atlassian.net/browse/RI-434)
=> RI-434 Add rocky branch jobs

rpc_jobs/rpc_openstack.yml
Issue: [RI-441](https://rpc-openstack.atlassian.net/browse/RI-441)
=> RI-441 Add release job for rocky

pipeline_steps/common.groovy, rpc_jobs/params.yml, scripts/lint_support_groovy/ParametersAction.groovy, scripts/lint_support_groovy/StringParameterValue.groovy
Re-submits https://github.com/rcbops/rpc-gating/pull/1005 and addresses failure due to `dir` in Docker causing code to be reverted https://github.com/rcbops/rpc-gating/pull/1014
JIRA: RE-1671
[Container test](https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-gating-master-xenial-functional-git-harry/19)
[Instance test](https://rpc.jenkins.cit.rackspace.net/job/PM_rpc-gating-master-xenial-functional-git-harry/20)
Issue: [SHA-1](https://rpc-openstack.atlassian.net/browse/SHA-1)
=>  Skip release tests with existing successful builds

rpc_jobs/standard_job_postmerge.yml, rpc_jobs/standard_job_premerge.yml
Issue: [RE-1905](https://rpc-openstack.atlassian.net/browse/RE-1905)
=> RE-1905 Remove deprecated hook dirs

pipeline_steps/common.groovy
We've removed the deprecated hook dirs, so this code is no longer
necessary.
PR #1025 will need to merge for this PR to gate successfully.
Issue: [RE-1905](https://rpc-openstack.atlassian.net/browse/RE-1905)
=> RE-1905 Revert multi hook dir code

rpc_jobs/osp_mnaio.yml
Adds initial PR job for osp-mnaio
Issue: [RE-1915](https://rpc-openstack.atlassian.net/browse/RE-1915)
=> RE-1915 Adds initial PR job for osp-mnaio

.gitignore, pipeline_steps/common.groovy, pipeline_steps/github.groovy, pipeline_steps/jenkins_api.groovy, rpc_jobs/build_summary.yml, rpc_jobs/bump_snapshots.yml, rpc_jobs/defaults.yml, rpc_jobs/hardening.yml, rpc_jobs/periodic_cleanup.yml, rpc_jobs/re_maintenance_window.yml, rpc_jobs/repo_server.yml, rpc_jobs/rpc_artifact_build.yml, rpc_jobs/rpc_gating.yml, rpc_jobs/rpc_maas.yml, rpc_jobs/rpc_octavia.yml, rpc_jobs/rpc_openstack.yml, rpc_jobs/rpc_role_logstash.yml, rpc_jobs/rpc_upgrades.yml, rpc_jobs/setup_grafana.yml, rpc_jobs/setup_graphite.yml, rpc_jobs/setup_nodepool.yml, rpc_jobs/setup_statsd.yml, rpc_jobs/standard_job_dep_update.yml, rpc_jobs/standard_job_postmerge.yml, scripts/jirautils.py, scripts/lint_jjb.py, scripts/lint_support_groovy/Job.groovy, scripts/lint_support_groovy/build.groovy, scripts/lint_support_groovy/run.groovy
* Add groovy functions for checking maintenance window overlap
* Add notifications for cancelled jobs
* jira - for RE to collect all cancelled jobs that relate
to a specific maintenance window
* PR - to explain why the job was cancelled.
* Add call to abortIfMaintenanceWindowPending in common.globalWraps
* Add lint test to check that no scheduled jobs conflict with
the maintenance window or its preceeding drain period.
Issue: [RE-1494](https://rpc-openstack.atlassian.net/browse/RE-1494)
=> RE-1494 Platform Maintenance Window

rpc_jobs/rpc_maas.yml
- Updated job templates to include queens
JIRA: RE-1969
Issue: [RE-1969](https://rpc-openstack.atlassian.net/browse/RE-1969)
=> Add Queens Check to rpc-maas

constraints_rpc_component.txt
Updates rpc_component to fix issue updating requirements.
JIRA: RE-1964
Issue: [RE-1964](https://rpc-openstack.atlassian.net/browse/RE-1964)
=> Update rpc_component version

rpc_jobs/rpc_appformix.yml, rpc_jobs/rpc_designate.yml, rpc_jobs/rpc_gating.yml, rpc_jobs/rpc_octavia.yml, rpc_jobs/snapshot.yml
- Added DFW as the fallback region to allow snapshot jobs to retry within same region
JIRA: RE-1973
Issue: [RE-1973](https://rpc-openstack.atlassian.net/browse/RE-1973)
=> Add Fallback Region for Snapshot Jobs

rpc_jobs/rpc_ceph.yml
Issue: [CEPHSTORA-368](https://rpc-openstack.atlassian.net/browse/CEPHSTORA-368)
=> CEPHSTORA-368 post merge gate job for queens

nodepool/files/nodepool.yml
JIRA: RE-1465
Issue: [RE-1465](https://rpc-openstack.atlassian.net/browse/RE-1465)
=> Fix typographical error in nodepool configuration

rpc_jobs/osp_mnaio.yml
Adds Periodic Testing of osp-mnaio
Issue: [RI-489](https://rpc-openstack.atlassian.net/browse/RI-489)
=> RI-489 Adds Periodic Testing of osp-mnaio

playbooks/phobos_vpn.yml, playbooks/templates/vpnc.conf.j2
Phobos VPN
* Add debug output to playbook
* VPN into Phobos only if outside Phobos
* Successfully test Phobos connectivity as exit criteria
Issue: [RE-2003](https://rpc-openstack.atlassian.net/browse/RE-2003)
=> Phobos VPN: Add debugging and conditional connecting

rpc_jobs/rpc_upgrades.yml
Include nodepool in label name.
=> Correct rpc snapshot name to include nodepool

pipeline_steps/common.groovy, rpc_jobs/unit/artefact_publish.yml
Issue: [RE-1654](https://rpc-openstack.atlassian.net/browse/RE-1654)
=> Fix issues with RE-unit-test-artefact-publication

constraints_rpc_component.txt, pipeline_steps/common.groovy, playbooks/tasks/artifact_upload/upload_file.yml, playbooks/tasks/artifact_upload/upload_log.yml
JIRA: RE-1813
Issue: [RE-1813](https://rpc-openstack.atlassian.net/browse/RE-1813)
Depends on https://github.com/rcbops/rpc_component/pull/10
=> Publishing file artefacts

pipeline_steps/common.groovy, rpc_jobs/rpc_ceph.yml
* Add exception handler to post stage to prevent it from causing failures
* Add hold_on_error to ceph jobs for diagnosis
Issue: [RE-2087](https://rpc-openstack.atlassian.net/browse/RE-2087)
=> RE-2087 Post stage failures

pipeline_steps/common.groovy, playbooks/tasks/artifact_upload/upload_file.yml
This change ensures that the CDN URL for the component's container is
used instead of one for a subdirectory in the container.
JIRA: RE-2100
Issue: [RE-2100](https://rpc-openstack.atlassian.net/browse/RE-2100)
=> Fix artefact store pull request proposal mechanism

nodepool/files/nodepool.yml
- Added Rocky images: rpc-r18.0.0-xenial_no_artifacts-swift, rpc-r18.0.0-bionic_no_artifacts-swift
JIRA: RE-2148
Issue: [RE-2148](https://rpc-openstack.atlassian.net/browse/RE-2148)
=> AIO OpenStack Rocky Images for NodePool

.gitignore, nodepool/setup_nodepool.yml
* Added task to create a Zookeeper cleanup cron job that runs daily at
midnight
* Ignore VSC project files
JIRA: RE-2158
Issue: [RE-2158](https://rpc-openstack.atlassian.net/browse/RE-2158)
=> Zookeeper TX Log Cleanup

rpc_jobs/rpc_jenkins_etl.yml
Issue: [ASC-1010](https://rpc-openstack.atlassian.net/browse/ASC-1010)
=> ASC-1010 CI for rpc-jenkins-etl

nodepool/templates/nodepool.yml.j2, rpc_jobs/rpc_maas.yml
Issue: [TURTLES-1582](https://rpc-openstack.atlassian.net/browse/TURTLES-1582)
=> TURTLES-1582: Enable rocky for rpc-maas on xenial and bionic

rpc_jobs/rpc_maas.yml
Issue: [TURTELS-1125](https://rpc-openstack.atlassian.net/browse/TURTELS-1125)
=> TURTELS-1125: Enable rpcr-osp13 gate for rpc-maas

pipeline_steps/common.groovy, scripts/lint_support_groovy/GhprbCancelBuildsOnUpdate.groovy
Don't create an artifact upload failure issue if the build has been
aborted.
Issue: [RE-1830](https://rpc-openstack.atlassian.net/browse/RE-1830)
=> RE-1830 Ignore aborted uploads

rpc_jobs/rpc_upgrades.yml
Correct typo on upgrades snapshot capture job
=> Correct typo on upgrades snapshot capture job

job_dsl/standard_job_checkmarx.groovy, pipeline_steps/common.groovy, rpc_jobs/rpc_gating.yml, rpc_jobs/standard_job_checkmarx.yml
* Adds standard job for Checkmarx scans
* Adds checkmarx jobs for rpc-gating and nodepool-agents-plugin
* Adds checkMarx job creator to common.registerComponent
* Adds shared slave type to common.standard_job_slave
Issue: [RE-2078](https://rpc-openstack.atlassian.net/browse/RE-2078)
=> RE-2078 Add Checkmarx Job Template

rpc_jobs/mk8s.yml
Security scan jobs for the repos managed by the K8S team.
Issue: [RE-2184](https://rpc-openstack.atlassian.net/browse/RE-2184)
=> RE-2184 Checkmarx Job for MK8s

rpc_jobs/rpc_ceph.yml
Issue: [CEPHSTORA-490](https://rpc-openstack.atlassian.net/browse/CEPHSTORA-490)
=> CEPHSTORA-490 Add checkmarx job

component_metadata.yml, constraints.txt, job_dsl/standard_job_lint_jenkins.groovy, lint.sh, requirements.txt, rpc_jobs/defaults.yml, rpc_jobs/jjb_setup.yml, rpc_jobs/params.yml, rpc_jobs/standard_job_lint_jenkins.yml, rpc_jobs/unit/artefact_publish.yml, scripts/jjb-path-setup.py, test-requirements.txt
Issue: [RE-2069](https://rpc-openstack.atlassian.net/browse/RE-2069)
Depends-on: https://github.com/rcbops/rpc_component/pull/12
The artefact unit tests fail because the change adds a `component_metadata.yml` file to the repository. The change to address this failure is in `rpc_jobs/unit/artefact_publish.yml` but is not applied because the unit tests do not get rebuild for pull requests.
=> Multi-repository JJB support

rpc_jobs/rpc_upgrades.yml
Creating checkmarx job for RPC-Upgrades in gating.
Issue: [RI-547](https://rpc-openstack.atlassian.net/browse/RI-547)
=> RI-547 Add RPC upgrades checkmarx

rpc_jobs/rpc_designate.yml
Creating checkmarx job for RPC-Designate.
Issue: [RI-547](https://rpc-openstack.atlassian.net/browse/RI-547)
=> RI-547 Add RPC Designate checkmarx job

rpc_jobs/rpc_appformix.yml
Creating RPC Appfromix checkmarx gating job with 'all' and 'pci'
rules.
Issue: [RI-547](https://rpc-openstack.atlassian.net/browse/RI-547)
=> RI-547 Add RPC Appfromix checkmarx

rpc_jobs/rpc_asc.yml
This PR will add Checkmarx scan jobs against ASC team repos. A new job config file 'rpc_asc.yml' was added.
Issue: [ASC-1251](https://rpc-openstack.atlassian.net/browse/ASC-1251)
=> ASC-1251 Add asc checkmarx jobs

rpc_jobs/rpc_maas.yml
Issue: [osp-13](https://rpc-openstack.atlassian.net/browse/osp-13)
=> Add cloud_creds credential to maas osp-13 gate

pipeline_steps/common.groovy
- Added exception catch logic to hold node if so configured
JIRA: RE-2120
Issue: [RE-2120](https://rpc-openstack.atlassian.net/browse/RE-2120)
=> Auto-hold Node Doesn't Work

rpc_jobs/osp_mnaio.yml
Issue: [ASC-1337](https://rpc-openstack.atlassian.net/browse/ASC-1337)
=> ASC-1337 Fix action name for osp13 system tests

rpc_jobs/build_gating_venv.yml, rpc_jobs/standard_job_lint_jenkins.yml
Preivously, an undefined macro branches was referenced, this commit
changes it to branch instead.
Issue: [RE-2070](https://rpc-openstack.atlassian.net/browse/RE-2070)
=> Fix branch param in Jenkins Lint Template

rpc_jobs/rpc_gating.yml
Add checkmarx scans for:
rpc_component
rpc_differ
osa_differ
releases
re-platform
Issue: RE-2240
Issue: [RE-2240](https://rpc-openstack.atlassian.net/browse/RE-2240)
=> [RE-2240] Add checkmarx scans for RE repos

rpc_jobs/rpc_appformix.yml
Issue: [RI-478](https://rpc-openstack.atlassian.net/browse/RI-478)
=> RI-478: Include missing credentials option for PM appformix jobs

pipeline_steps/common.groovy
We've had some jobs fail on git configuration because git can't
lock its own config files to modify them. This commit adds a lock
to ensure jenkins is only trying to configure git in one build at
a time. It also adds sleep+retry incase its a non-jenkins process
thats got the git config locked.
Issue: [RE-2231](https://rpc-openstack.atlassian.net/browse/RE-2231)
=> RE-2231 Mitigate git config races

pipeline_steps/common.groovy
- Use java.security.SecureRandom instead of Random
Issue: RE-2196
Issue: [RE-2196](https://rpc-openstack.atlassian.net/browse/RE-2196)
=> fix "Use of Cryptographically weak PRNG" vulnerability

scripts/add_jenkins_cred.groovy
- CheckMarx Fix - Removed system exit call
JIRA: RE-2204
Issue: [RE-2204](https://rpc-openstack.atlassian.net/browse/RE-2204)
=> Fix Use of System Exit

rpc_jobs/rpc_barbican.yml
Barbican is the secret management as a service for OpenStack. This
pipeline will test the content for rpc-barbican witch will install
Barbican and integrate its backend with Vault using a Rocky AIO.
JIRA: RI-546
Issue: [RI-546](https://rpc-openstack.atlassian.net/browse/RI-546)
=> Initial release of Barbican pipeline

rpc_jobs/rpc_appformix.yml
Issue: [RI-612](https://rpc-openstack.atlassian.net/browse/RI-612)
=> RI-612: Add Rocky testing to rpc-appformix

rpc_jobs/rpc_designate.yml
Issue: [RI-613](https://rpc-openstack.atlassian.net/browse/RI-613)
=> RI-613: Add designate Rocky gate job

rpc_jobs/build_summary.yml
* fixed data.json filename
JIRA: RE-2276
Issue: [RE-2276](https://rpc-openstack.atlassian.net/browse/RE-2276)
=> Fix Typo in Build Summary Upload Stage

job_dsl/standard_job_checkmarx.groovy, pipeline_steps/checkmarx.groovy, rpc_jobs/standard_job_checkmarx.yml
* Added exclude_folders build argument
JIRA: RE-2265
Issue: [RE-2265](https://rpc-openstack.atlassian.net/browse/RE-2265)
=> Allow Checkmarx Jobs to Exclude Folders

pipeline_steps/checkmarx.groovy
* changed scope for excluded folder
JIRA: RE-2265
Issue: [RE-2265](https://rpc-openstack.atlassian.net/browse/RE-2265)
=> Checkmarx Exclude Folder Scope

scripts/build_summary/build.py, scripts/build_summary/build_summary_gh.py
Previously only PM_ and PR_ jobs were allowed, this change
allows a wider range of prefixes.
Issue: [RE-2194](https://rpc-openstack.atlassian.net/browse/RE-2194)
=> RE-2194 Expand jobs eligible for build summary

pipeline_steps/common.groovy, scripts/lint_jjb.py
* Removed node timeout - will rely on job timeout only
* Leveraged BUILD_TIMEOUT_HR for global wraps timeout
* Added lint test for timeout value/range
JIRA: RE-2307
Issue: [RE-2307](https://rpc-openstack.atlassian.net/browse/RE-2307)
=> Externalize Standard Job Timeout

pipeline_steps/common.groovy, rpc_jobs/bump_snapshots.yml, rpc_jobs/defaults.yml
Add comments to time related code to indicate that times are in UTC.
Issue: [RE-2060](https://rpc-openstack.atlassian.net/browse/RE-2060)
=> RE-2060 Clarify Timezones

rpc_jobs/rpc_designate.yml
Issue: [RI-627](https://rpc-openstack.atlassian.net/browse/RI-627)
Issue: [RI-613](https://rpc-openstack.atlassian.net/browse/RI-613)
=> RI-613: Add Bionic Job for Designate

graphite/setup_graphite.yml, nodepool/setup_nodepool.yml, nodepool/templates/nodepool.yml.j2, playbooks/allocate_pubcloud.yml, playbooks/ansible.cfg, playbooks/inventory/openstack.yml, playbooks/phobos_tunnel.yml, playbooks/setup_openstack_instances.yml, playbooks/slave_security.yml, playbooks/webhooks.yml, role_requirements.yml, statsd/setup_statsd.yml, statsd/templates/config.js.j2
Please see the individual commits for more details.
* Correct deprecated syntax
* Correct syntax errors
* Correct type errors
* Correct and improve openstack inventory plugin config
* Correct and improve playbooks
* Update the sshd role
Issue: [RE-1721](https://rpc-openstack.atlassian.net/browse/RE-1721)
=> Further Ansible 2.7 related changes

rpc_jobs/rpc_barbican.yml, rpc_jobs/rpc_designate.yml
Issue: [RI-639](https://rpc-openstack.atlassian.net/browse/RI-639)
=> RI-639: Remove Hold on error for rpc-designate and rpc-barbican

rpc_jobs/rpc_openstack.yml
Issue: [ASC-967](https://rpc-openstack.atlassian.net/browse/ASC-967)
=> ASC-967 add creds to system-staging

rpc_jobs/rpc_upgrades.yml
Adds Newton to Pike test to validate commits
that affect that code path.
=> Adds Newton to Pike PR test

pipeline_steps/common.groovy, rpc_jobs/releases.yml, rpc_jobs/standard_job_release.yml, scripts/confluenceutils.py, scripts/ghutils.py, scripts/jirautils.py, scripts/notifications.py, scripts/reexceptions.py, scripts/release.py
This commit ensures that releases can be re-run by skipping parts
that have already succeeded.
Issue: [RE-2310](https://rpc-openstack.atlassian.net/browse/RE-2310)
=> RE-2310 Idempotent Releases

pipeline_steps/common.groovy, pipeline_steps/docker_utils.groovy, playbooks/templates/vpnc.conf.j2, playbooks/templates/vpnc.service.j2, playbooks/vpn_setup.yml, rpc_jobs/build_gating_venv.yml, rpc_jobs/build_summary.yml, rpc_jobs/kronos_vpn_service.yml, rpc_jobs/periodic_cleanup.yml, rpc_jobs/unit/kronos_vpn.yml, rpc_jobs/unit/re_unit_tests.yml
See individual commits for details
JIRA: RE-404
Issue: [RE-404](https://rpc-openstack.atlassian.net/browse/RE-404)
=> RE-404 Add Kronos registry support

rpc_jobs/unit/kronos_vpn.yml
A boolean was changed to a function, update the test code to match.
Issue: [RE-404](https://rpc-openstack.atlassian.net/browse/RE-404)
=> RE-404 Fix kronos vpn unit test

pipeline_steps/common.groovy, rpc_jobs/rpc_jenkins_etl.yml
Required for the ETL periodic job.
Issue: [RE-2355](https://rpc-openstack.atlassian.net/browse/RE-2355)
=> RE-2355 Add ASC Ops Fabric Goole Vault Cred

rpc_jobs/rpc_upgrades.yml
Drops a number of AIO/MNAIO jobs to start switching to
using MNAIO snaps and adds some incremental
jobs.
=> Drop AIO jobs in favor of MNAIO snaps

rpc_jobs/rpc_openstack.yml
Basically clarify gating job stages from pre-merge, post-merge and
release.
=> RI-643 Adding comment for each section of testing

rpc_jobs/rpc_openstack.yml
This PR adds a heath_check action into project
experimental-asc-rpc-openstack-master-mnaio-postmerge
in order to test RPC-O deploymet status before doing
any modification to the enviroment.
Issue: [ASC-1552](https://rpc-openstack.atlassian.net/browse/ASC-1552)
=> (ASC-1552) Add experiment test for health check tests

constraints.txt, job_dsl/rpc_repo_verify.groovy, requirements.txt, rpc_jobs/rpc_openstack.yml, scripts/apt_repo_hash_check.py
This job recalculates the checksum for every package in rpc-repo
and finds any Packages(index) file SHAs that don't match the packages on
disk.
Issue: [RE-2361](https://rpc-openstack.atlassian.net/browse/RE-2361)
=> RE-2361 Repo Verify Job

pipeline_steps/common.groovy, rpc_jobs/unit/internal_repo.yml, rpc_jobs/unit/re_unit_tests.yml
Issue: [RE-2338](https://rpc-openstack.atlassian.net/browse/RE-2338)
=> RE-2338 Fix internal repo cloning

rpc_jobs/rpc_designate.yml
Issue: [RI-665](https://rpc-openstack.atlassian.net/browse/RI-665)
=> RI-665: Switch newton to non snapshot PM job

rpc_jobs/rpc_ceph.yml
Add mimic gates for xenial and bionic
=> Add rpc-ceph mimic and bionic gates

pipeline_steps/common.groovy, playbooks/vpn_setup.yml, rpc_jobs/unit/kronos_vpn.yml, rpc_jobs/unit/phobos_vpn.yml, rpc_jobs/unit/single_use_slave.yml
us not able to fix it via jenkins(chicken-egg).
I'm moving the REPO_BASE to http to see if it
works around the issue.
=> Venv builds fail due to insecure cert leaving
